Repository hmcts/prl-citizen-frontend, pull requests merged in 2022-07, with the labels that each got.

#119 initial commit
  src/main/steps/applicant/task-list/content.test.ts
  src/main/steps/applicant/task-list/content.ts
  src/main/steps/applicant/task-list/template.njk
  src/main/steps/applicant/task-list/utils.ts
  src/main/steps/common/common.content.ts
  src/main/steps/respondent/task-list/content.test.ts
  src/main/steps/respondent/task-list/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-119

#85 Feature/consent to application 1415
  charts/prl-citizen-frontend/Chart.yaml
  src/main/app/case/case.ts
  src/main/steps/common/form/fields/date.njk
  src/main/steps/common/page.njk
  src/main/steps/common/summary/utils.test.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/common/template.njk
  src/main/steps/respondent/consent-to-application/consent/content.test.ts
  src/main/steps/respondent/consent-to-application/consent/content.ts
  src/main/steps/respondent/consent-to-application/consent/template.njk
  src/main/steps/respondent/consent-to-application/summary/content.ts
  src/main/steps/respondent/consent-to-application/summary/template.njk
  src/main/steps/respondent/respondentcaseSequence.test.ts
  src/main/steps/respondent/respondentcaseSequence.ts
  src/main/steps/respondent/task-list/content.test.ts
  src/main/steps/respondent/task-list/section-titles.ts
  src/main/steps/respondent/task-list/tasklist-items.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/respondent/task-list/utils.ts
  src/main/steps/urls.ts
  src/test/unit/utils/mockUserCase.ts
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-85

#131 Fixed dependency error
  package.json
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-131

#146 Chart version update
  charts/prl-citizen-frontend/Chart.yaml
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-146

#144 Feature/prlc100 2
  src/main/app/form/Form.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/confidentiality/details-know/content.test.ts
  src/main/steps/c100-rebuild/confidentiality/details-know/content.ts
  src/main/steps/c100-rebuild/confidentiality/details-know/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/form.njk
  src/main/steps/common/page.njk
  src/main/steps/constants.ts
  src/main/steps/edge-case/dashboard/template.njk
  src/main/steps/index.ts
  src/main/steps/urls.ts
  tsconfig.json
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-144

#151 Feature/prlc100 6
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/confidentiality/start/content.test.ts
  src/main/steps/c100-rebuild/confidentiality/start/content.ts
  src/main/steps/c100-rebuild/confidentiality/start/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-151

#150 Feature/prlc100 4
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/confidentiality/start-alternative/content.test.ts
  src/main/steps/c100-rebuild/confidentiality/start-alternative/content.ts
  src/main/steps/c100-rebuild/confidentiality/start-alternative/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-150

#153 Feature/prlc100 2 error
  src/main/steps/c100-rebuild/confidentiality/details-know/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-153

#154 Feature/prlc100 6 and 4 error
  src/main/steps/c100-rebuild/confidentiality/start-alternative/content.ts
  src/main/steps/c100-rebuild/confidentiality/start/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-154

#93 Feature/da app confirm contact details 1486
  package-lock.json
  sonar-project.properties
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant/applicantCaseSequence.ts
  src/main/steps/applicant/confirm-contact-details/addressblank/content.ts
  src/main/steps/applicant/confirm-contact-details/addressconfirmation/content.ts
  src/main/steps/applicant/confirm-contact-details/addressdetails/content.ts
  src/main/steps/applicant/confirm-contact-details/addresshistory/content.ts
  src/main/steps/applicant/confirm-contact-details/addresslookup/content.ts
  src/main/steps/applicant/confirm-contact-details/addresslookupcont/content.ts
  src/main/steps/applicant/confirm-contact-details/checkanswers/ApplicantConfirmContactDetailsGetController.ts
  src/main/steps/applicant/confirm-contact-details/checkanswers/content.ts
  src/main/steps/applicant/confirm-contact-details/contactdetails/content.ts
  src/main/steps/applicant/confirm-contact-details/personaldetails/content.ts
  src/main/steps/applicant/task-list/content.test.ts
  src/main/steps/applicant/task-list/tasklist.ts
  src/main/steps/applicant/task-list/utils.test.ts
  src/main/steps/applicant/task-list/utils.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
  src/main/steps/common/confirm-contact-details/checkanswers/content.ts
  src/main/steps/common/confirm-contact-details/checkanswers/template.njk
  src/main/steps/common/summary/utils.test.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/respondent/confirm-contact-details/addressblank/content.ts
  src/main/steps/respondent/confirm-contact-details/addressconfirmation/content.ts
  src/main/steps/respondent/confirm-contact-details/addressdetails/content.ts
  src/main/steps/respondent/confirm-contact-details/addresshistory/content.ts
  src/main/steps/respondent/confirm-contact-details/addresslookup/content.ts
  src/main/steps/respondent/confirm-contact-details/addresslookupcont/content.ts
  src/main/steps/respondent/confirm-contact-details/checkanswers/RespondentConfirmContactDetailsGetController.ts
  src/main/steps/respondent/confirm-contact-details/checkanswers/content.ts
  src/main/steps/respondent/confirm-contact-details/checkanswers/template.njk
  src/main/steps/respondent/confirm-contact-details/contactdetails/content.ts
  src/main/steps/respondent/confirm-contact-details/personaldetails/content.ts
  src/main/steps/respondent/task-list/content.test.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/respondent/task-list/utils.ts
  src/test/unit/utils/defaultViewArgs.ts
  src/test/unit/utils/mockRequest.ts
  src/test/unit/utils/mockResponse.ts
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-93

#124 DA CA Citizen dashboard Your needs when you go to court Dev Part 1
  charts/prl-citizen-frontend/Chart.yaml
  package.json
  sonar-project.properties
  src/main/app/case/case.ts
  src/main/app/form/Form.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/applicant/applicantCaseSequence.test.ts
  src/main/steps/applicant/applicantCaseSequence.ts
  src/main/steps/applicant/support-you-need-during-case/communication-help/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/communication-help/content.ts
  src/main/steps/applicant/support-you-need-during-case/communication-help/template.njk
  src/main/steps/applicant/support-you-need-during-case/court-hearing-support/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/court-hearing-support/content.ts
  src/main/steps/applicant/support-you-need-during-case/court-hearing-support/template.njk
  src/main/steps/applicant/support-you-need-during-case/documents-support/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/documents-support/content.ts
  src/main/steps/applicant/support-you-need-during-case/documents-support/template.njk
  src/main/steps/applicant/support-you-need-during-case/language-requirements/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/language-requirements/content.ts
  src/main/steps/applicant/support-you-need-during-case/language-requirements/template.njk
  src/main/steps/applicant/support-you-need-during-case/reasonable-adjustments/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/reasonable-adjustments/content.ts
  src/main/steps/applicant/support-you-need-during-case/reasonable-adjustments/template.njk
  src/main/steps/applicant/task-list/content.test.ts
  src/main/steps/applicant/task-list/tasklist-items.ts
  src/main/steps/applicant/task-list/tasklist.ts
  src/main/steps/applicant/task-list/utils.ts
  src/main/steps/common/form/fields/checkboxes.njk
  src/main/steps/common/template.njk
  src/main/steps/index.ts
  src/main/steps/urls.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-124

#84 Prl 1460 latest
  package.json
  sonar-project.properties
  src/main/app/case/case.ts
  src/main/steps/common/form/form.njk
  src/main/steps/respondent/respondentcaseSequence.test.ts
  src/main/steps/respondent/respondentcaseSequence.ts
  src/main/steps/respondent/safety_concerns/domestic_abuse_risk/content.ts
  src/main/steps/respondent/safety_concerns/domestic_abuse_risk/template.njk
  src/main/steps/respondent/safety_concerns/domestic_abuse_risk_no/content.ts
  src/main/steps/respondent/safety_concerns/domestic_abuse_risk_no/template.njk
  src/main/steps/respondent/safety_concerns/main_page/content.ts
  src/main/steps/respondent/safety_concerns/main_page/template.njk
  src/main/steps/respondent/safety_concerns/your_safety/content.ts
  src/main/steps/respondent/safety_concerns/your_safety/template.njk
  src/main/steps/respondent/task-list/content.test.ts
  src/main/steps/respondent/task-list/section-titles.ts
  src/main/steps/respondent/task-list/tasklist-items.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/respondent/task-list/utils.ts
  src/main/steps/urls.ts
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-84

#161 Added steps path configurations, added session usercase data for stor…
  charts/prl-citizen-frontend/Chart.yaml
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/confidentiality/feedback/content.test.ts
  src/main/steps/c100-rebuild/confidentiality/feedback/content.ts
  src/main/steps/c100-rebuild/confidentiality/feedback/template.njk
  src/main/steps/index.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-161

#167 added different variable name and screen data
  src/main/app/case/case.ts
  src/main/app/controller/GetController.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/c100-rebuild/confidentiality/feedback/template.njk
  src/main/steps/c100-rebuild/confidentiality/start-alternative/content.test.ts
  src/main/steps/c100-rebuild/confidentiality/start-alternative/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-167

#98 Feature/confirm edit contact 1453
  charts/prl-citizen-frontend/Chart.yaml
  charts/prl-citizen-frontend/values.aat.template.yaml
  charts/prl-citizen-frontend/values.preview.template.yaml
  charts/prl-citizen-frontend/values.yaml
  sonar-project.properties
  src/main/app/case/CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/form/Form.ts
  src/main/steps/common/components/common/address-manual.test.ts
  src/main/steps/common/components/common/address-manual.ts
  src/main/steps/common/components/common/address-select.test.ts
  src/main/steps/common/components/common/address-select.ts
  src/main/steps/common/form/form.njk
  src/main/steps/common/summary/utils.test.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/respondent/confirmcontactdetails/addressblank/content.ts
  src/main/steps/respondent/confirmcontactdetails/addressblank/template.njk
  src/main/steps/respondent/confirmcontactdetails/addressconfirmation/content.ts
  src/main/steps/respondent/confirmcontactdetails/addressconfirmation/template.njk
  src/main/steps/respondent/confirmcontactdetails/addressdetails/content.ts
  src/main/steps/respondent/confirmcontactdetails/addressdetails/template.njk
  src/main/steps/respondent/confirmcontactdetails/addresshistory/content.ts
  src/main/steps/respondent/confirmcontactdetails/addresshistory/template.njk
  src/main/steps/respondent/confirmcontactdetails/addresslookup/content.ts
  src/main/steps/respondent/confirmcontactdetails/addresslookup/template.njk
  src/main/steps/respondent/confirmcontactdetails/addresslookupcont/content.ts
  src/main/steps/respondent/confirmcontactdetails/addresslookupcont/template.njk
  src/main/steps/respondent/confirmcontactdetails/checkanswers/ConfirmContactDetailsGetController.ts
  src/main/steps/respondent/confirmcontactdetails/checkanswers/content.ts
  src/main/steps/respondent/confirmcontactdetails/checkanswers/template.njk
  src/main/steps/respondent/confirmcontactdetails/contactdetails/content.ts
  src/main/steps/respondent/confirmcontactdetails/contactdetails/template.njk
  src/main/steps/respondent/confirmcontactdetails/personaldetails/content.ts
  src/main/steps/respondent/confirmcontactdetails/personaldetails/template.njk
  src/main/steps/respondent/miam/summary/content.ts
  src/main/steps/respondent/respondentcaseSequence.test.ts
  src/main/steps/respondent/respondentcaseSequence.ts
  src/main/steps/respondent/task-list/content.test.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/respondent/task-list/utils.ts
  src/main/steps/respondent/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-98

#142 PRL-1767:Added changes to redirect to login page
  src/main/modules/oidc/index.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-142

#118 CA - Respondent Citizen - Enter Other proceedings - Dev - Part 2
  sonar-project.properties
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/modules/properties-volume/index.ts
  src/main/steps/common/form/fields/date.njk
  src/main/steps/common/summary/utils.test.ts
  src/main/steps/respondent/proceedings/court-proceedings/content.ts
  src/main/steps/respondent/proceedings/court-proceedings/template.njk
  src/main/steps/respondent/proceedings/start/content.ts
  src/main/steps/respondent/proceedings/start/template.njk
  src/main/steps/respondent/proceedings/summary/content.ts
  src/main/steps/respondent/proceedings/summary/template.njk
  src/main/steps/respondent/respondentcaseSequence.test.ts
  src/main/steps/respondent/respondentcaseSequence.ts
  src/main/steps/respondent/task-list/content.test.ts
  src/main/steps/respondent/task-list/section-titles.ts
  src/main/steps/respondent/task-list/tasklist-items.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/respondent/task-list/utils.ts
  src/main/steps/urls.ts
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-118

#172 Testcase/PRL_C100-updated-test-cases
  src/main/app/controller/GetController.test.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-172

#163 Code added for International elements start
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/international-elements/jurisdiction/content.test.ts
  src/main/steps/c100-rebuild/international-elements/jurisdiction/content.ts
  src/main/steps/c100-rebuild/international-elements/jurisdiction/template.njk
  src/main/steps/c100-rebuild/international-elements/parents/content.test.ts
  src/main/steps/c100-rebuild/international-elements/parents/content.ts
  src/main/steps/c100-rebuild/international-elements/parents/template.njk
  src/main/steps/c100-rebuild/international-elements/request/content.test.ts
  src/main/steps/c100-rebuild/international-elements/request/content.ts
  src/main/steps/c100-rebuild/international-elements/request/template.njk
  src/main/steps/c100-rebuild/international-elements/start/content.test.ts
  src/main/steps/c100-rebuild/international-elements/start/content.ts
  src/main/steps/c100-rebuild/international-elements/start/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-163

#178 feat: implement reasonable adjustments hearingType screen(PRLC100-48)
  src/main/app/form/Form.ts
  src/main/modules/nunjucks/index.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/attending-court/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/attending-court/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/attending-court/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-178
