Repository hmcts/prl-citizen-frontend, pull requests merged in 2022-09, with the labels that each got.

#271 Feature/prlc100 66
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/typeoforder/caorder/content.test.ts
  src/main/steps/c100-rebuild/typeoforder/caorder/content.ts
  src/main/steps/c100-rebuild/typeoforder/caorder/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-271

#275 feat(PRLC100-77): Integrate create case and automate commit checks
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/routes.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/landing/content.ts
  src/main/steps/c100-rebuild/landing/get.ts
  src/main/steps/c100-rebuild/landing/landingPageController.test.ts
  src/main/steps/c100-rebuild/landing/landingPageController.ts
  src/main/steps/c100-rebuild/landing/template.njk
  src/main/steps/edge-case/dashboard/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-275

#276 Validation changes
  src/main/steps/c100-rebuild/typeoforder/caorder/content.test.ts
  src/main/steps/c100-rebuild/typeoforder/caorder/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-276

#262 Feature/common code refactor with backend
  src/main/app/auth/user/oidc.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/app/controller/PostController.ts
  src/main/modules/oidc/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/steps/applicant/task-list/tasklist.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/edge-case/dashboard/content.ts
  src/main/steps/edge-case/dashboard/template.njk
  src/main/steps/edge-case/edgecaseSequence.test.ts
  src/main/steps/index.ts
  src/main/steps/prl-cases/citizen-home/contact.ts
  src/main/steps/prl-cases/citizen-home/content.test.ts
  src/main/steps/prl-cases/citizen-home/content.ts
  src/main/steps/prl-cases/citizen-home/template.njk
  src/main/steps/prl-cases/citizenSequence.test.ts
  src/main/steps/prl-cases/citizenSequence.ts
  src/main/steps/prl-cases/dashboard/content.test.ts
  src/main/steps/prl-cases/dashboard/content.ts
  src/main/steps/prl-cases/dashboard/customSummaryList/macro.njk
  src/main/steps/prl-cases/dashboard/customSummaryList/template.njk
  src/main/steps/prl-cases/dashboard/form.njk
  src/main/steps/prl-cases/dashboard/template.njk
  src/main/steps/respondent/task-list/utils.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-262

#285 issue fixes for testing
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/confirmation-page/content.test.ts
  src/main/steps/c100-rebuild/confirmation-page/content.ts
  src/main/steps/c100-rebuild/confirmation-page/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-285

#189 Prl 1532 hyperlink
  src/main/steps/applicant/confirm-contact-details/checkanswers/template.njk
  src/main/steps/common/summary/form.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-189

#177 PRL-1895:made changes to enable fortify scan
  Jenkinsfile_nightly
  test/java/.gitignore
  test/java/build.gradle
  test/java/config/fortify-client.properties
  test/java/gradle/wrapper/gradle-wrapper.jar
  test/java/gradle/wrapper/gradle-wrapper.properties
  test/java/gradlew
  test/java/gradlew.bat
  test/java/settings.gradle
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-177, enable_fortify_scan

#295 Launch darkly changes
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/prl-citizen-frontend/values.aat.template.yaml
  charts/prl-citizen-frontend/values.preview.template.yaml
  charts/prl-citizen-frontend/values.yaml
  config/default.yaml
  config/development.yaml
  package.json
  src/main/app/utils/featureToggles.test.ts
  src/main/app/utils/featureToggles.ts
  src/main/common/clients/launchDarklyClient.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-295

#138 PRL1559:added changes to display safe to call field
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
  src/main/steps/common/confirm-contact-details/checkanswers/content.ts
  src/main/steps/common/confirm-contact-details/contactdetails/content.ts
  src/main/steps/common/summary/utils.test.ts
  src/main/steps/common/summary/utils.ts
  src/test/unit/utils/mockUserCase.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-138

#287 Feature/prlc100 98/ payment url configurations
  README.md
  config/custom-environment-variables.yaml
  config/default.yaml
  config/development.yaml
  src/main/app/case/case.ts
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/modules/payments/paymentApi.test.ts
  src/main/modules/payments/paymentApi.ts
  src/main/modules/payments/paymentController.test.ts
  src/main/modules/payments/paymentController.ts
  src/main/modules/payments/paymentHelper.test.ts
  src/main/modules/payments/paymentHelper.ts
  src/main/routes.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/c100-rebuild/child-details/add-childern/getController.ts
  src/main/steps/c100-rebuild/confirmation-page/template.njk
  src/main/steps/c100-rebuild/landing/landingPageController.ts
  src/main/steps/cookies/get.test.ts
  src/main/steps/edge-case/dashboard/content.ts
  src/main/steps/edge-case/dashboard/template.njk
  src/main/steps/privacy-policy/get.test.ts
  src/main/steps/urls.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-287

#291 feat(PRLC100-83): create other proceedings order details screeen
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/GetController.ts
  src/main/app/form/Form.test.ts
  src/main/app/form/Form.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/getController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/getController.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/postController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/postController.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/template.njk
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/fields.njk
  src/main/steps/urls.ts
  src/test/unit/utils/defaultViewArgs.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-291

#302 Ca da citizen dashboard navigation
  config/default.yaml
  sonar-project.properties
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/GetRespondentCaseController.ts
  src/main/routes.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
  src/main/steps/common/confirm-contact-details/checkanswers/content.ts
  src/main/steps/common/confirm-contact-details/contactdetails/content.ts
  src/main/steps/common/summary/utils.test.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/prl-cases/dashboard/content.ts
  src/test/unit/utils/mockUserCase.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-302

#278 Feature/prl 1673 ca resp error messages
  Jenkinsfile_CNP
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.ts
  src/main/app/form/Form.ts
  src/main/routes.ts
  src/main/steps/applicant/task-list/tasklist.ts
  src/main/steps/applicant/task-list/utils.test.ts
  src/main/steps/applicant/task-list/utils.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/form/form.njk
  src/main/steps/respondent/miam/miam-start/content.test.ts
  src/main/steps/respondent/miam/miam-start/content.ts
  src/main/steps/respondent/miam/summary/content.ts
  src/main/steps/respondent/miam/willingness-to-attend-miam/content.test.ts
  src/main/steps/respondent/miam/willingness-to-attend-miam/content.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/respondent/task-list/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-278, Release 2.3

#292 Updated definition
  sonar-project.properties
  src/main/app/case/CosApiClient.ts
  src/main/app/case/definition.ts
  src/main/app/case/from-api-format.ts
  src/main/app/controller/ConsentGetController.ts
  src/main/app/controller/GetCaseController.ts
  src/main/app/controller/PostController.ts
  src/main/app/controller/SaveRespondentResponseController.ts
  src/main/routes.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/respondent/respondentcaseSequence.test.ts
  src/main/steps/respondent/respondentcaseSequence.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, Release 2.3, rel:prl-citizen-frontend-pr-292

#314 Feature/prlc100 84 upload remove documents
  config/default.yaml
  config/development.yaml
  package.json
  src/main/app/auth/service/get-service-auth-token.integration.test.ts
  src/main/app/auth/service/get-service-auth-token.ts
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/definition.ts
  src/main/modules/fileupload/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/modules/payments/paymentHelper.test.ts
  src/main/server.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/common/fileupload/macro.njk
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/content.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/getController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/getController.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/template.njk
  src/main/steps/urls.ts
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-314

#309 feat(PRLC100-85):Created document summary page
  sonar-project.properties
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/content.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/getController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/getController.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-309

#311 c100 Rebuild - updated contents for international elements post feedback from Legal n Policy
  src/main/steps/c100-rebuild/international-elements/jurisdiction/content.test.ts
  src/main/steps/c100-rebuild/international-elements/jurisdiction/content.ts
  src/main/steps/c100-rebuild/international-elements/parents/content.test.ts
  src/main/steps/c100-rebuild/international-elements/parents/content.ts
  src/main/steps/c100-rebuild/international-elements/request/content.test.ts
  src/main/steps/c100-rebuild/international-elements/request/content.ts
  src/main/steps/c100-rebuild/international-elements/start/content.test.ts
  src/main/steps/c100-rebuild/international-elements/start/content.ts
  src/main/steps/c100-rebuild/start/content.test.ts
  src/main/steps/c100-rebuild/start/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-311

#315 PRLC100-125 feature - Added changes for c1A safety concern about screen
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/safety-concerns/concern-about/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/concern-about/content.ts
  src/main/steps/c100-rebuild/safety-concerns/concern-about/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-315

#330 fix(PRLC100-86): Integrate edit feature for other proceedings documen…
  package.json
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/content.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/template.njk
  src/main/steps/c100-rebuild/other-proceedings/navigationController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/navigationController.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/postController.ts
  src/main/steps/c100-rebuild/other-proceedings/util.test.ts
  src/main/steps/c100-rebuild/other-proceedings/util.ts
  src/main/steps/constants.ts
  src/main/steps/index.ts
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-330

#326 Feature/prlc100 138 test feedback
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/common/fileupload/macro.njk
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/content.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/getController.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-326

#321 feat(PRLC100-86): Handle navigation for other proceedings screens
  package.json
  sonar-project.properties
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/routes.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/common/fileupload/macro.njk
  src/main/steps/c100-rebuild/other-proceedings/document-summary/content.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/getController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/getController.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/routeGuard.test.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/routeGuard.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/template.njk
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/content.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/getController.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/template.njk
  src/main/steps/c100-rebuild/other-proceedings/navigationController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/navigationController.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/getController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/getController.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/postController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/postController.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/routeGuard.test.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/routeGuard.ts
  src/main/steps/c100-rebuild/other-proceedings/proceeding-details/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/proceeding-details/content.ts
  src/main/steps/c100-rebuild/other-proceedings/util.test.ts
  src/main/steps/c100-rebuild/other-proceedings/util.ts
  src/main/steps/constants.ts
  src/main/steps/index.ts
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-321

#331 feat(PRLC100-106) Document Submission screen
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/document-submission/content.test.ts
  src/main/steps/c100-rebuild/document-submission/content.ts
  src/main/steps/c100-rebuild/document-submission/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-331

#338 PRLC100-124 C100 Rebuild safety concerns - Removed warning message ma…
  src/main/steps/c100-rebuild/safety-concerns/concerns-for-safety/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-338

#334 Feature/prlc100 111
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/childaddress/content.test.ts
  src/main/steps/c100-rebuild/childaddress/content.ts
  src/main/steps/c100-rebuild/childaddress/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-334

#340 feat(PRLC100-126):page for child concern about
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/safety-concerns/child/concerns-about/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/child/concerns-about/content.ts
  src/main/steps/c100-rebuild/safety-concerns/child/concerns-about/template.njk
  src/main/steps/c100-rebuild/safety-concerns/child/content.ts
  src/main/steps/c100-rebuild/safety-concerns/child/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-340

#339 [C100-Rebuild ] Feature PRLC100 122 - C1A safety concern guidance screen
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/safety-concerns/concern-guidance/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/concern-guidance/content.ts
  src/main/steps/c100-rebuild/safety-concerns/concern-guidance/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-339

#345 Feature/c100 rebuild prlc100 175
  src/main/app/case/case.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/miam/mediator-document/content.test.ts
  src/main/steps/c100-rebuild/miam/mediator-document/content.ts
  src/main/steps/c100-rebuild/miam/mediator-document/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-345

#349 (PRLC100-159):Page for applicant concern about
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/safety-concerns/applicant/concerns-about/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/applicant/concerns-about/content.ts
  src/main/steps/c100-rebuild/safety-concerns/applicant/concerns-about/template.njk
  src/main/steps/c100-rebuild/safety-concerns/applicant/content.ts
  src/main/steps/c100-rebuild/safety-concerns/applicant/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-349
