Repository hmcts/prl-citizen-frontend, pull requests merged in 2022-08, with the labels that each got.

#185 Feature/prlc100 49 reasonable adjustements
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/language-requirements/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/language-requirements/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/language-requirements/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-185

#191 fix: continue button label change
  src/main/steps/c100-rebuild/reasonable-adjustments/language-requirements/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/language-requirements/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-191

#192 Fixed error scenarios
  src/main/steps/c100-rebuild/reasonable-adjustments/special-arrangements/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/special-arrangements/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-192

#180 Prl 1886 citizen changes bot
  .nvmrc
  package-lock.json
  package.json
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-180

#194 feat: implement reasonable adjustments disability requirements(PRLC10…
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-194

#193 support court code
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/support-court/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/support-court/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/support-court/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-193

#196 feat: implement document information screen(PRLC100-53)
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/document-information/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/document-information/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/document-information/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-196

#197 Updated code for feel-comfortable
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/feel-comfortable/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/feel-comfortable/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/feel-comfortable/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-197

#211 feat: implement reasonable adjustments communication help screen(PRLC…
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/communication-help/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/communication-help/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/communication-help/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-211

#212 Added code for reasonable adjustments travelling courtgit
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/travelling-court/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/travelling-court/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/travelling-court/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-212

#214 Typo fix
  src/main/steps/c100-rebuild/reasonable-adjustments/travelling-court/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/travelling-court/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-214

#125 Feature/da applicant keep details private 1483
  src/main/steps/applicant/applicantCaseSequence.ts
  src/main/steps/applicant/keep-details-private/details_known/content.test.ts
  src/main/steps/applicant/keep-details-private/details_known/content.ts
  src/main/steps/applicant/keep-details-private/details_known/template.njk
  src/main/steps/applicant/keep-details-private/private_details_confirmed/content.test.ts
  src/main/steps/applicant/keep-details-private/private_details_confirmed/content.ts
  src/main/steps/applicant/keep-details-private/private_details_confirmed/template.njk
  src/main/steps/applicant/keep-details-private/private_details_not_confirmed/content.test.ts
  src/main/steps/applicant/keep-details-private/private_details_not_confirmed/content.ts
  src/main/steps/applicant/keep-details-private/private_details_not_confirmed/template.njk
  src/main/steps/applicant/keep-details-private/start_alternative/content.test.ts
  src/main/steps/applicant/keep-details-private/start_alternative/content.ts
  src/main/steps/applicant/keep-details-private/start_alternative/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-125

#139 Feature/da resp db orders 1653
  charts/prl-citizen-frontend/Chart.yaml
  config/default.yaml
  config/development.yaml
  sonar-project.properties
  src/main/app/auth/user/oidc.integration.test.ts
  src/main/app/auth/user/oidc.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/formatter/uploaded-files.test.ts
  src/main/app/case/formatter/uploaded-files.ts
  src/main/app/case/from-api-format.ts
  src/main/app/case/to-api-format.ts
  src/main/app/controller/PostController.ts
  src/main/modules/properties-volume/index.ts
  src/main/steps/applicant/applicantCaseSequence.test.ts
  src/main/steps/applicant/applicantCaseSequence.ts
  src/main/steps/applicant/orders/content.test.ts
  src/main/steps/applicant/orders/content.ts
  src/main/steps/applicant/orders/template.njk
  src/main/steps/applicant/task-list/content.test.ts
  src/main/steps/applicant/task-list/content.ts
  src/main/steps/applicant/task-list/section-titles.ts
  src/main/steps/applicant/task-list/tasklist-items.ts
  src/main/steps/applicant/task-list/tasklist.ts
  src/main/steps/applicant/task-list/template.njk
  src/main/steps/applicant/task-list/utils.ts
  src/main/steps/common/tasklist/template.njk
  src/main/steps/respondent/respondentcaseSequence.ts
  src/main/steps/respondent/task-list/content.test.ts
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/respondent/task-list/section-titles.ts
  src/main/steps/respondent/task-list/tasklist-items.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/respondent/task-list/utils.ts
  src/main/steps/respondent/yourdocuments/alldocuments/orders/content.test.ts
  src/main/steps/respondent/yourdocuments/alldocuments/orders/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/orders/template.njk
  src/main/steps/urls.ts
  src/test/unit/utils/mockUserCase.ts
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-139

#231 Fixing issue with the azure secret fetch logic
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  config/custom-environment-variables.yaml
  config/default.yaml
  config/development.yaml
  src/main/app/auth/user/oidc.ts
  src/main/modules/properties-volume/index.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-231

#232 Fix for issue after code merging
  src/main/app/controller/PostController.ts
  src/main/steps/applicant/confirm-contact-details/addresshistory/content.ts
  src/main/steps/applicant/confirm-contact-details/checkanswers/content.ts
  src/main/steps/common/summary/utils.test.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/respondent/task-list/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-232

#234 Fix for merge conflict issues
  src/main/steps/applicant/support-you-need-during-case/summary/content.ts
  src/main/steps/applicant/support-you-need-during-case/summary/utils.test.ts
  src/main/steps/applicant/support-you-need-during-case/summary/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-234

#235 Fix for issues after code merge
  src/main/steps/applicant/confirm-contact-details/contactdetails/content.ts
  src/main/steps/applicant/support-you-need-during-case/summary/content.ts
  src/main/steps/ca-da-respondent/support-you-need-during-case/summary/content.ts
  src/main/steps/common/support-you-need-during-case/summary/utils.test.ts
  src/main/steps/common/support-you-need-during-case/summary/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-235

#249 Add backstage configuration file
  catalog-info.yaml
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-249

#245 feat(PRLC100-23,PRLC100-24) Code changes for hearing part 1 and part2
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part1/content.test.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part1/content.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part1/form.njk
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part1/template.njk
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part2/content.test.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part2/content.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part2/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-245

#261 Prl 1681 citizen frontend upload remove link
  sonar-project.properties
  src/main/app/case/CosApiClient.ts
  src/main/app/document/DocumentDetail.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/steps/respondent/upload-document/document-sharing-details/content.test.ts
  src/main/steps/respondent/upload-document/document-sharing-details/content.ts
  src/main/steps/respondent/upload-document/upload-documents-success/content.ts
  src/main/steps/respondent/upload-document/upload-documents-success/template.njk
  src/main/steps/respondent/upload-document/upload-your-documents/content.ts
  src/main/steps/respondent/upload-document/upload-your-documents/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-261

#247 Feature/prlc100 65 typeoforder
  src/main/app/form/validation.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/typeoforder/select-courtorder/content.test.ts
  src/main/steps/c100-rebuild/typeoforder/select-courtorder/content.ts
  src/main/steps/c100-rebuild/typeoforder/select-courtorder/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, c100-rebuild, rel:prl-citizen-frontend-pr-247

#258 Feature/prlc100 67/short statement
  sonar-project.properties
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/typeoforder/shortstatement/content.test.ts
  src/main/steps/c100-rebuild/typeoforder/shortstatement/content.ts
  src/main/steps/c100-rebuild/typeoforder/shortstatement/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-258

#260 Feature/prlc100 74
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/other-proceedings/current-previous-proceedings/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/current-previous-proceedings/content.ts
  src/main/steps/c100-rebuild/other-proceedings/current-previous-proceedings/template.njk
  src/main/steps/c100-rebuild/other-proceedings/proceeding-details/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/proceeding-details/content.ts
  src/main/steps/c100-rebuild/other-proceedings/proceeding-details/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-260

#251 Feature/prlc100 63
  src/main/assets/scss/main.scss
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/start/content.test.ts
  src/main/steps/c100-rebuild/start/content.ts
  src/main/steps/c100-rebuild/start/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-251

#268 police reports download docs screen is updated
  src/main/app/case/case.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/routes.ts
  src/main/steps/applicant/yourdocuments/alldocuments/police_disclosures/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/police_disclosures/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-268

#273 Drug paternity tasklist hide
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-273

#252 C100 Rebuild - Need help with fees screens
  config/default.yaml
  config/development.yaml
  sonar-project.properties
  src/main/app/case/case.ts
  src/main/app/controller/GetController.ts
  src/main/app/fees/fees-lookup-api.ts
  src/main/modules/properties-volume/index.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/help-with-fees/fees-applied/content.test.ts
  src/main/steps/c100-rebuild/help-with-fees/fees-applied/content.ts
  src/main/steps/c100-rebuild/help-with-fees/fees-applied/template.njk
  src/main/steps/c100-rebuild/help-with-fees/hwf-guidance/content.test.ts
  src/main/steps/c100-rebuild/help-with-fees/hwf-guidance/content.ts
  src/main/steps/c100-rebuild/help-with-fees/hwf-guidance/template.njk
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/content.test.ts
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/content.ts
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/getController.test.ts
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/getController.ts
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, c100-rebuild, rel:prl-citizen-frontend-pr-252
