Repository hmcts/prl-citizen-frontend, pull requests merged in 2022-11, with the labels that each got.

#485 Feature/prlc100 28 address changes
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/to-api-format.test.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-lookup.test.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-lookup.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-manual.test.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-manual.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-select.test.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-select.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/AddressLookupPostController.test.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/AddressLookupPostController.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/content.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/form.njk
  src/main/steps/c100-rebuild/applicant/address/lookup/template.njk
  src/main/steps/c100-rebuild/applicant/address/manual/ManualAddressPostController.test.ts
  src/main/steps/c100-rebuild/applicant/address/manual/ManualAddressPostController.ts
  src/main/steps/c100-rebuild/applicant/address/manual/content.test.ts
  src/main/steps/c100-rebuild/applicant/address/manual/content.ts
  src/main/steps/c100-rebuild/applicant/address/manual/template.njk
  src/main/steps/c100-rebuild/applicant/address/select/SelectAddressPostController.test.ts
  src/main/steps/c100-rebuild/applicant/address/select/SelectAddressPostController.ts
  src/main/steps/c100-rebuild/applicant/address/select/content.test.ts
  src/main/steps/c100-rebuild/applicant/address/select/content.ts
  src/main/steps/c100-rebuild/applicant/address/select/form.njk
  src/main/steps/c100-rebuild/applicant/address/select/template.njk
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-485

#490 fixed sonar issues on Release_2.2 branch related to 2249
  src/main/app/address/AddressLookupPostControllerBase.ts
  src/main/app/address/ManualAddressPostControllerBase.ts
  src/main/app/address/SelectAddressPostControllerBase.ts
  src/main/steps/applicant/upload-document/DocumentManagementGetController.test.ts
  src/main/steps/common/controller/ViewAllDocumentsPostController.ts
  src/main/steps/respondent/upload-document/RespondentDocumentManagementGetController.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-490

#491 fixed sonar issues on master branch related to 2249
  src/main/app/address/SelectAddressPostControllerBase.ts
  src/main/app/auth/user/oidc.ts
  src/main/app/case/case.ts
  src/main/app/case/to-api-format.ts
  src/main/app/form/Form.ts
  src/main/app/form/validation copy.ts
  src/main/app/form/validation.ts
  src/main/steps/common/components/common/renderSubFields.ts
  src/main/steps/common/keep-details-private/KeepDetailsPrivateGetController.ts
  src/main/steps/common/keep-details-private/KeepDetailsPrivatePostController.ts
  src/main/steps/home/get.ts
  src/main/steps/respondent/consent-to-application/ConsentPostController.ts
  src/main/steps/tasklistresponse/legalrepresentation/start/LegalRepresentationPostController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-491

#498 Remove checkbox - 'All of the children in the application' option fro…
  src/main/steps/c100-rebuild/safety-concerns/child/report-abuse/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/child/report-abuse/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-498

#502 feat(PRLC100-264): Cleanup session data for fields in the same page with conditional rendering
  sonar-project.properties
  src/main/app/controller/PostController.ts
  src/main/steps/c100-rebuild/PreProcessCaseData.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-502

#508 Code smell fix for citizen-frontend
  src/main/app/document/DocumentManagementController.ts
  src/main/app/form/Form.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ContactDetailsMapper.ts
  src/main/steps/common/keep-details-private/KeepDetailsPrivateGetController.ts
  src/main/steps/common/keep-details-private/KeepDetailsPrivatePostController.ts
  src/main/steps/respondent/consent-to-application/ConsentPostController.ts
  src/main/steps/respondent/task-list/utils.ts
Labels: ns:private-law, prd:prl, Release 2.3, rel:prl-citizen-frontend-pr-508

#505 feat(PRLC100-307,PRLC100-308): Change query params to URL params for applicant journey
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/AddressLookupPostController.test.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/AddressLookupPostController.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/content.ts
  src/main/steps/c100-rebuild/applicant/address/manual/ManualAddressPostController.test.ts
  src/main/steps/c100-rebuild/applicant/address/manual/ManualAddressPostController.ts
  src/main/steps/c100-rebuild/applicant/address/manual/content.test.ts
  src/main/steps/c100-rebuild/applicant/address/manual/content.ts
  src/main/steps/c100-rebuild/applicant/address/select/SelectAddressPostController.test.ts
  src/main/steps/c100-rebuild/applicant/address/select/SelectAddressPostController.ts
  src/main/steps/c100-rebuild/applicant/address/select/content.test.ts
  src/main/steps/c100-rebuild/applicant/address/select/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/postContoller.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/postController.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedback/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedback/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedback/postController.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedbackno/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedbackno/postController.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start-alternative/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start-alternative/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start-alternative/postController.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start/postController.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-505

#509 Prlc100 32 respondent name
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/content.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/postController.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/template.njk
  src/main/steps/c100-rebuild/respondent-details/navigationController.test.ts
  src/main/steps/c100-rebuild/respondent-details/navigationController.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/postController.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/template.njk
  src/main/steps/c100-rebuild/respondent-details/util.ts
  src/main/steps/urls.ts
  src/test/unit/mocks/mocked-requests/child-details-mock.ts
  src/test/unit/mocks/mocked-requests/miam-mock.ts
  src/test/unit/mocks/mocked-requests/other-child-mock.ts
  src/test/unit/mocks/mocked-requests/other-proceedings-mock.ts
  src/test/unit/mocks/mocked-requests/respondent-details-mock.ts
  src/test/unit/mocks/mocked-requests/safety-concerns-mock.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-509

#446 feat(PRLC100-192) : Save and come back later
  config/default.yaml
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/get-case/getController.test.ts
  src/main/steps/c100-rebuild/get-case/getController.ts
  src/main/steps/c100-rebuild/miam/upload/postController.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.ts
  src/main/steps/edge-case/dashboard/template.njk
  src/main/steps/prl-cases/dashboard-v1/template.njk
  src/main/steps/urls.ts
  src/test/unit/utils/mockRequest.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-446

#515 PRL-2497 Terms and Conditions
  src/main/steps/privacy-policy/template.njk
  src/main/steps/terms-and-conditions/content.test.ts
  src/main/steps/terms-and-conditions/content.ts
  src/main/steps/terms-and-conditions/template.njk
Labels: ns:private-law, prd:prl, Release 2.3, rel:prl-citizen-frontend-pr-515

#519 PRL-2497 Privacy Policy
  src/main/steps/privacy-policy/content.test.ts
  src/main/steps/privacy-policy/content.ts
  src/main/steps/privacy-policy/template.njk
Labels: ns:private-law, prd:prl, Release 2.3, rel:prl-citizen-frontend-pr-519

#484 C7 citizen cos integration
  src/main/app/case/CosApiClient.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/RespondentSubmitResponseController.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/routes.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
  src/main/steps/common/respondent-summary/template.njk
  src/main/steps/tasklistresponse/summary-confirmation/template.njk
  src/main/steps/tasklistresponse/summary/content.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, Release 2.3, rel:prl-citizen-frontend-pr-484

#520 Prl 2508 da train track
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/utils/progress-bar-utils.test.ts
  src/main/app/utils/progress-bar-utils.ts
  src/main/assets/images/tick.png
  src/main/assets/scss/main.scss
  src/main/steps/applicant/task-list/content.ts
  src/main/steps/applicant/task-list/template.njk
  src/main/steps/common/models/progressBarItems.ts
  src/main/steps/common/progress-bar.njk
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/respondent/task-list/template.njk
Labels: ns:private-law, prd:prl, Release 2.3, rel:prl-citizen-frontend-pr-520

#510 confirm or edit details error messages are updated.
  src/main/steps/common/confirm-contact-details/addressconfirmation/content.ts
  src/main/steps/common/confirm-contact-details/contactdetails/content.ts
Labels: ns:private-law, prd:prl, Release 2.3, rel:prl-citizen-frontend-pr-510

#534 Release 2.2 unit tests quality
  sonar-project.properties
  src/main/app/case/CosApiClient.test.ts
  src/main/app/controller/RespondentSubmitResponseController.test.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/steps/applicant/applicantCaseSequence.test.ts
  src/main/steps/applicant/confirm-contact-details/addressconfirmation/content.test.ts
  src/main/steps/applicant/confirm-contact-details/addressdetails/content.test.ts
  src/main/steps/applicant/confirm-contact-details/addresshistory/content.test.ts
  src/main/steps/applicant/confirm-contact-details/checkanswers/content.test.ts
  src/main/steps/applicant/confirm-contact-details/contactdetails/content.test.ts
  src/main/steps/applicant/confirm-contact-details/personaldetails/content.test.ts
  src/main/steps/applicant/confirm-contact-details/postaladdress/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/summary/content.test.ts
  src/main/steps/applicant/task-list/tasklist.test.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.test.ts
  src/main/steps/common/confirm-contact-details/addressconfirmation/content.test.ts
  src/main/steps/common/confirm-contact-details/addressdetails/content.test.ts
  src/main/steps/common/confirm-contact-details/addresshistory/content.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ContactDetailsMapper.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ContactDetailsMapper.ts
  src/main/steps/common/confirm-contact-details/contactdetails/content.test.ts
  src/main/steps/common/confirm-contact-details/personaldetails/content.test.ts
  src/main/steps/constants.test.ts
  src/main/steps/cookies/content.test.ts
  src/main/steps/prl-cases/dashboard/DashboardGetController.test.ts
  src/main/steps/respondent/confirm-contact-details/addressconfirmation/content.test.ts
  src/main/steps/respondent/confirm-contact-details/addressdetails/content.test.ts
  src/main/steps/respondent/confirm-contact-details/addresshistory/content.test.ts
  src/main/steps/respondent/confirm-contact-details/checkanswers/content.test.ts
  src/main/steps/respondent/confirm-contact-details/contactdetails/content.test.ts
  src/main/steps/respondent/confirm-contact-details/personaldetails/content.test.ts
  src/main/steps/respondent/safety_concerns/domestic_abuse_risk/content.test.ts
  src/main/steps/respondent/safety_concerns/domestic_abuse_risk_no/content.test.ts
  src/main/steps/respondent/safety_concerns/main_page/content.test.ts
  src/main/steps/respondent/safety_concerns/your_safety/content.test.ts
  src/main/steps/respondent/task-list/tasklist.test.ts
  src/main/steps/respondent/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.test.ts
  src/main/steps/save-sign-out/content.test.ts
  src/main/steps/tasklistresponse/consent-to-application/summary/content.test.ts
  src/main/steps/tasklistresponse/miam/summary/content.test.ts
  src/main/steps/tasklistresponse/start/tasklist.test.ts
  src/main/steps/tasklistresponse/start/tasklist.ts
  src/main/steps/tasklistresponse/start/utils.test.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/summary/content.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-534

#522 add respondent address lookup, manual and select screens feature
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/other-person-details/util.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/postController.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-lookup.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-lookup.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-manual.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-manual.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-select.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-select.ts
  src/main/steps/c100-rebuild/respondent-details/address/lookup/AddressLookupPostController.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/lookup/AddressLookupPostController.ts
  src/main/steps/c100-rebuild/respondent-details/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/lookup/content.ts
  src/main/steps/c100-rebuild/respondent-details/address/lookup/form.njk
  src/main/steps/c100-rebuild/respondent-details/address/lookup/template.njk
  src/main/steps/c100-rebuild/respondent-details/address/manual/ManualAddressPostController.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/ManualAddressPostController.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/template.njk
  src/main/steps/c100-rebuild/respondent-details/address/select/SelectAddressPostController.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/SelectAddressPostController.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/content.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/form.njk
  src/main/steps/c100-rebuild/respondent-details/address/select/template.njk
  src/main/steps/c100-rebuild/respondent-details/contact-details/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/contact-details/content.ts
  src/main/steps/c100-rebuild/respondent-details/contact-details/postController.test.ts
  src/main/steps/c100-rebuild/respondent-details/contact-details/postController.ts
  src/main/steps/c100-rebuild/respondent-details/contact-details/template.njk
  src/main/steps/c100-rebuild/respondent-details/navigationController.test.ts
  src/main/steps/c100-rebuild/respondent-details/navigationController.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/postController.test.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/postController.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/template.njk
  src/main/steps/c100-rebuild/respondent-details/util.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-522

#536 feat(PRLC100-38): Add who child live with screen
  config/development.yaml
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/child-details/live-with/content.test.ts
  src/main/steps/c100-rebuild/child-details/live-with/content.ts
  src/main/steps/c100-rebuild/child-details/live-with/postController.test.ts
  src/main/steps/c100-rebuild/child-details/live-with/postController.ts
  src/main/steps/c100-rebuild/child-details/live-with/routeGuard.test.ts
  src/main/steps/c100-rebuild/child-details/live-with/routeGuard.ts
  src/main/steps/c100-rebuild/child-details/live-with/template.njk
  src/main/steps/c100-rebuild/child-details/navigationController.test.ts
  src/main/steps/c100-rebuild/child-details/navigationController.ts
  src/main/steps/c100-rebuild/child-details/util.ts
  src/main/steps/c100-rebuild/respondent-details/navigationController.test.ts
  src/main/steps/common/string-parser.ts
  src/main/steps/urls.ts
  src/test/unit/mocks/mocked-requests/child-details-mock.ts
  src/test/unit/mocks/mocked-requests/people-mock.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-536

#539 C100-Rebuild - Added CCD fields for mappers
  src/main/app/case/C100CaseApi.ts
  src/main/steps/c100-rebuild/childaddress/content.test.ts
  src/main/steps/c100-rebuild/childaddress/content.ts
  src/main/steps/c100-rebuild/help-with-fees/fees-applied/content.test.ts
  src/main/steps/c100-rebuild/help-with-fees/fees-applied/content.ts
  src/main/steps/c100-rebuild/help-with-fees/hwf-guidance/content.test.ts
  src/main/steps/c100-rebuild/help-with-fees/hwf-guidance/content.ts
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/content.test.ts
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/content.ts
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/getController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-539

#514 feat(PRLC100-307,PRLC100-309): Change query params to URL params for other proceedings orders journey
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/content.ts
  src/main/steps/c100-rebuild/other-proceedings/document-summary/routeGuard.test.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/getController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/getController.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/template.njk
  src/main/steps/c100-rebuild/other-proceedings/navigationController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/navigationController.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/postController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/postController.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/routeGuard.test.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/routeGuard.ts
  src/main/steps/c100-rebuild/other-proceedings/util.test.ts
  src/main/steps/c100-rebuild/other-proceedings/util.ts
  src/main/steps/common/url-parser.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-514

#523 PRLC100-26 - Added screen changes for applicant relationshop to child
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/AddressLookupPostController.ts
  src/main/steps/c100-rebuild/applicant/address/manual/ManualAddressPostController.ts
  src/main/steps/c100-rebuild/applicant/address/select/SelectAddressPostController.ts
  src/main/steps/c100-rebuild/applicant/navigationController.test.ts
  src/main/steps/c100-rebuild/applicant/navigationController.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/postController.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/template.njk
  src/main/steps/c100-rebuild/applicant/util.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/urls.ts
  src/test/unit/mocks/mocked-requests/applicant-details-mock.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-523

#544 Feature/plc100 respondent prvious name change
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/postController.test.ts
  src/main/steps/c100-rebuild/respondent-details/contact-details/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/contact-details/content.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.ts
  src/main/steps/c100-rebuild/respondent-details/util.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-544

#518 feat(PLRC100-25) add:Applicant Personal Details
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/content.test.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/common/postController.test.ts
  src/main/steps/c100-rebuild/applicant/personal-details/content.test.ts
  src/main/steps/c100-rebuild/applicant/personal-details/content.ts
  src/main/steps/c100-rebuild/applicant/personal-details/postController.test.ts
  src/main/steps/c100-rebuild/applicant/personal-details/postController.ts
  src/main/steps/c100-rebuild/applicant/personal-details/template.njk
  src/main/steps/c100-rebuild/applicant/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/applicant/util.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-518

#517 feat: implement applicant contact detail screen(PRLC100-29)
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/content.test.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/content.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/postController.test.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/postController.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/template.njk
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-517

#549 PRLC100-288 - Added navigation linking for other persons
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/lookup/AddressLookupPostController.ts
  src/main/steps/c100-rebuild/other-person-details/address/lookup/content.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/content.ts
  src/main/steps/c100-rebuild/other-person-details/address/select/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/select/content.ts
  src/main/steps/c100-rebuild/other-person-details/navigationController.test.ts
  src/main/steps/c100-rebuild/other-person-details/navigationController.ts
  src/main/steps/c100-rebuild/other-person-details/personal-details/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/personal-details/content.ts
  src/main/steps/c100-rebuild/other-person-details/personal-details/postController.test.ts
  src/main/steps/c100-rebuild/other-person-details/routeGuard.test.ts
  src/main/steps/c100-rebuild/other-person-details/util.test.ts
  src/main/steps/c100-rebuild/other-person-details/util.ts
  src/main/steps/c100-rebuild/people/address/address-lookup.test.ts
  src/main/steps/c100-rebuild/people/address/address-lookup.ts
  src/main/steps/c100-rebuild/people/address/address-manual.test.ts
  src/main/steps/c100-rebuild/people/address/address-manual.ts
  src/main/steps/c100-rebuild/people/address/address-select.test.ts
  src/main/steps/c100-rebuild/people/address/address-select.ts
  src/main/steps/c100-rebuild/respondent-details/contact-details/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/contact-details/content.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.ts
  src/main/steps/c100-rebuild/respondent-details/util.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-549

#551 PVT-Law - C100-Rebuild common issue fixes
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/development.yaml
  src/main/app/case/CosApiClient.ts
  src/main/modules/oidc/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-551

#553 fix issues according to the prototype
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-lookup.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-lookup.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-manual.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-manual.ts
  src/main/steps/c100-rebuild/respondent-details/address/lookup/form.njk
  src/main/steps/c100-rebuild/respondent-details/address/lookup/template.njk
  src/main/steps/c100-rebuild/respondent-details/address/manual/ManualAddressPostController.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/template.njk
  src/main/steps/c100-rebuild/respondent-details/address/select/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/content.ts
  src/main/steps/c100-rebuild/respondent-details/contact-details/content.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.ts
  src/main/steps/c100-rebuild/respondent-details/util.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-553

#554 feat(PRLC100-314): Add applicant feature screens linking
  sonar-project.properties
  src/main/steps/c100-rebuild/applicant/confidentiality/feedback/postController.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedback/postController.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedbackno/postController.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedbackno/postController.ts
  src/main/steps/c100-rebuild/applicant/navigationController.test.ts
  src/main/steps/c100-rebuild/applicant/navigationController.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/child-details/live-with/content.ts
  src/main/steps/common/string-parser.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-554

#552 feat: amend applicant contact details (PRLC100-29)
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/content.test.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/content.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/postController.test.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/postController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-552

#468 PRLC100-232-Consent-Order-Upload-Confirmation
  src/main/app/case/case.ts
  src/main/steps/c100-rebuild/applicant/navigationController.test.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/consent-order/upload-confirmation/content.test.ts
  src/main/steps/c100-rebuild/consent-order/upload-confirmation/content.ts
  src/main/steps/c100-rebuild/consent-order/upload-confirmation/template.njk
  src/main/steps/c100-rebuild/consent-order/upload/content.test.ts
  src/main/steps/c100-rebuild/consent-order/upload/content.ts
  src/main/steps/c100-rebuild/consent-order/upload/getController.test.ts
  src/main/steps/c100-rebuild/consent-order/upload/getController.ts
  src/main/steps/c100-rebuild/consent-order/upload/postController.test.ts
  src/main/steps/c100-rebuild/consent-order/upload/postController.ts
  src/main/steps/c100-rebuild/consent-order/upload/template.njk
  src/main/steps/c100-rebuild/other-person-details/address/common/address-lookup.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/common/address-lookup.ts
  src/main/steps/c100-rebuild/other-person-details/address/common/address-manual.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/common/address-manual.ts
  src/main/steps/c100-rebuild/other-person-details/address/common/address-select.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/common/address-select.ts
  src/main/steps/c100-rebuild/other-person-details/address/lookup/content.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/content.ts
  src/main/steps/c100-rebuild/other-person-details/address/select/content.ts
  src/main/steps/urls.ts
  src/test/unit/mocks/mocked-requests/applicant-details-mock.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-468

#557 feat: remove not providing email address reason(PRLC100-29)
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/content.test.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/content.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/postController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-557

#558 fix(PLRC100-33) fix:PO asked to change for Have they change their nam…
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-558

#565 C100-Rebuild - Linking basic screen flows & added serviceName
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/default.yaml
  config/development.yaml
  src/main/app/case/case.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/other-proceedings/navigationController.ts
  src/main/steps/c100-rebuild/respondent-details/navigationController.ts
  src/main/steps/common/common.content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-565

#567 PRLC100-284,PRLC100-288 - Added linking for child lives with screen
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/other-person-details/navigationController.test.ts
  src/main/steps/c100-rebuild/other-person-details/navigationController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-567

#569 C100-rebuild - refactored common address files for respondent & other person
  sonar-project.properties
  src/main/steps/c100-rebuild/other-person-details/address/lookup/AddressLookupPostController.ts
  src/main/steps/c100-rebuild/other-person-details/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/lookup/content.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/ManualAddressPostController.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/content.ts
  src/main/steps/c100-rebuild/other-person-details/address/select/SelectAddressPostController.ts
  src/main/steps/c100-rebuild/other-person-details/address/select/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/select/content.ts
  src/main/steps/c100-rebuild/other-person-details/address/select/form.njk
  src/main/steps/c100-rebuild/people/address/address-lookup.test.ts
  src/main/steps/c100-rebuild/people/address/address-lookup.ts
  src/main/steps/c100-rebuild/people/address/address-manual.test.ts
  src/main/steps/c100-rebuild/people/address/address-manual.ts
  src/main/steps/c100-rebuild/people/address/address-select.test.ts
  src/main/steps/c100-rebuild/people/address/address-select.ts
  src/main/steps/c100-rebuild/people/util.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-lookup.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-lookup.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-manual.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-manual.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-select.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/common/address-select.ts
  src/main/steps/c100-rebuild/respondent-details/address/lookup/AddressLookupPostController.ts
  src/main/steps/c100-rebuild/respondent-details/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/lookup/content.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/SelectAddressPostController.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/content.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/form.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-569

#575 PRLC100-331 - Refactored reasonable adjustments sub fields for check your answers screen
  src/main/steps/c100-rebuild/get-case/getController.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/attending-court/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/attending-court/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/communication-help/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/communication-help/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/document-information/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/document-information/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/feel-comfortable/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/feel-comfortable/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/support-court/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/support-court/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/travelling-court/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/travelling-court/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/language-requirements/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/language-requirements/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/special-arrangements/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/special-arrangements/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-575

#573 feat(PRLC100-329): Add save & comeback back later for address journey across features
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-manual.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/AddressLookupPostController.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/content.ts
  src/main/steps/c100-rebuild/applicant/address/manual/ManualAddressPostController.ts
  src/main/steps/c100-rebuild/applicant/address/manual/content.test.ts
  src/main/steps/c100-rebuild/applicant/address/manual/content.ts
  src/main/steps/c100-rebuild/applicant/address/select/SelectAddressPostController.test.ts
  src/main/steps/c100-rebuild/applicant/address/select/SelectAddressPostController.ts
  src/main/steps/c100-rebuild/applicant/address/select/content.test.ts
  src/main/steps/c100-rebuild/applicant/address/select/content.ts
  src/main/steps/c100-rebuild/child-details/navigationController.ts
  src/main/steps/c100-rebuild/child-details/other-children/names/content.test.ts
  src/main/steps/c100-rebuild/child-details/other-children/navigationController.ts
  src/main/steps/c100-rebuild/child-details/other-children/personal-details/content.test.ts
  src/main/steps/c100-rebuild/child-details/other-children/personal-details/content.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/content.ts
  src/main/steps/c100-rebuild/child-details/personal-details/content.test.ts
  src/main/steps/c100-rebuild/child-details/personal-details/content.ts
  src/main/steps/c100-rebuild/other-person-details/address/lookup/AddressLookupPostController.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/ManualAddressPostController.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/ManualAddressPostController.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/content.ts
  src/main/steps/c100-rebuild/other-person-details/address/select/SelectAddressPostController.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/select/SelectAddressPostController.ts
  src/main/steps/c100-rebuild/other-person-details/address/select/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/select/content.ts
  src/main/steps/c100-rebuild/other-person-details/navigationController.ts
  src/main/steps/c100-rebuild/other-person-details/personal-details/content.test.ts
  src/main/steps/c100-rebuild/people/address/address-manual.ts
  src/main/steps/c100-rebuild/people/util.ts
  src/main/steps/c100-rebuild/respondent-details/address/lookup/AddressLookupPostController.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/ManualAddressPostController.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/ManualAddressPostController.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/SelectAddressPostController.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/SelectAddressPostController.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/content.ts
  src/main/steps/c100-rebuild/respondent-details/navigationController.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-573

#477 Downloadcheckapplicationaoh
  src/main/app/auth/service/get-service-auth-token.ts
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/modules/oidc/index.ts
  src/main/routes.ts
  src/main/steps/common/common.content.ts
  src/main/steps/constants.ts
  src/main/steps/prl-cases/dashboard/content.ts
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/respondent/task-list/tasklist.test.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/respondent/task-list/utils.ts
Labels: ns:private-law, prd:prl, Release 2.3, rel:prl-citizen-frontend-pr-477

#576 PRLC100-332 Fix Code Smells
  sonar-project.properties
  src/main/steps/c100-rebuild/applicant/address/lookup/AddressLookupPostController.ts
  src/main/steps/c100-rebuild/applicant/address/manual/ManualAddressPostController.ts
  src/main/steps/c100-rebuild/applicant/address/select/SelectAddressPostController.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/child-details/child-matters/content.ts
  src/main/steps/c100-rebuild/child-details/child-matters/postController.ts
  src/main/steps/c100-rebuild/child-details/live-with/content.ts
  src/main/steps/c100-rebuild/child-details/live-with/postController.ts
  src/main/steps/c100-rebuild/child-details/live-with/routeGuard.ts
  src/main/steps/c100-rebuild/child-details/other-children/personal-details/content.ts
  src/main/steps/c100-rebuild/child-details/other-children/personal-details/postController.ts
  src/main/steps/c100-rebuild/child-details/other-children/routeGuard.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/content.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/postController.ts
  src/main/steps/c100-rebuild/child-details/personal-details/content.ts
  src/main/steps/c100-rebuild/child-details/personal-details/postController.ts
  src/main/steps/c100-rebuild/child-details/routeGuard.ts
  src/main/steps/c100-rebuild/other-person-details/address/lookup/AddressLookupPostController.ts
  src/main/steps/c100-rebuild/other-person-details/address/lookup/content.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/ManualAddressPostController.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/content.ts
  src/main/steps/c100-rebuild/other-person-details/address/select/SelectAddressPostController.ts
  src/main/steps/c100-rebuild/other-person-details/address/select/content.ts
  src/main/steps/c100-rebuild/other-person-details/personal-details/content.ts
  src/main/steps/c100-rebuild/other-person-details/personal-details/postController.ts
  src/main/steps/c100-rebuild/other-person-details/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/other-person-details/relationship-to-child/postController.ts
  src/main/steps/c100-rebuild/other-person-details/routeGuard.ts
  src/main/steps/c100-rebuild/other-proceedings/navigationController.ts
  src/main/steps/c100-rebuild/people/AddPeoplePostContoller.ts
  src/main/steps/c100-rebuild/people/util.test.ts
  src/main/steps/c100-rebuild/people/util.ts
  src/main/steps/c100-rebuild/respondent-details/address/lookup/AddressLookupPostController.ts
  src/main/steps/c100-rebuild/respondent-details/address/lookup/content.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/ManualAddressPostController.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/SelectAddressPostController.ts
  src/main/steps/c100-rebuild/respondent-details/address/select/content.ts
  src/main/steps/c100-rebuild/respondent-details/contact-details/content.ts
  src/main/steps/c100-rebuild/respondent-details/contact-details/postController.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/postController.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/postController.ts
  src/main/steps/c100-rebuild/safety-concerns/navigationController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-576

#472 Prlc100 227 featureflagging
  Jenkinsfile_CNP
  charts/prl-citizen-frontend/Chart.yaml
  charts/prl-citizen-frontend/values.preview.template.yaml
  charts/prl-citizen-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/development.yaml
  src/main/app/controller/AppRequest.ts
  src/main/app/utils/featureToggles.test.ts
  src/main/app/utils/featureToggles.ts
  src/main/common/clients/launchDarklyClient.test.ts
  src/main/common/clients/launchDarklyClient.ts
  src/main/modules/feature-toggle/index.ts
  src/main/modules/oidc/index.ts
  src/main/modules/properties-volume/index.ts
  src/main/server.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-472

#578 increase test coverage from 80% to 91%
  src/main/app/utils/featureToggles.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-578

#571 PRLC100-330 Improve Code Coverage
  src/main/app/case/C100CaseApi.test.ts
  src/main/steps/c100-rebuild/PreProcessCaseData.test.ts
  src/main/steps/c100-rebuild/miam/upload/postController.test.ts
  src/main/steps/c100-rebuild/miam/util.test.ts
  src/main/steps/c100-rebuild/other-person-details/add-other-persons/postController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-571

#577 C100rebuild code smell fix
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/child-details/child-matters/content.ts
  src/main/steps/c100-rebuild/child-details/child-matters/postController.test.ts
  src/main/steps/c100-rebuild/child-details/child-matters/postController.ts
  src/main/steps/c100-rebuild/child-details/childDetailPostController.test.ts
  src/main/steps/c100-rebuild/child-details/childDetailPostController.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/content.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/postController.test.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/postController.ts
  src/main/steps/c100-rebuild/child-details/personal-details/content.ts
  src/main/steps/c100-rebuild/child-details/personal-details/postController.test.ts
  src/main/steps/c100-rebuild/child-details/personal-details/postController.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-577

#581 feat(PRLC100-329): Add alternate flows screen linking
  src/main/app/case/case.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-manual.ts
  src/main/steps/c100-rebuild/applicant/address/manual/ManualAddressPostController.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/child-details/navigationController.ts
  src/main/steps/c100-rebuild/miam/navigationController.ts
  src/main/steps/c100-rebuild/other-proceedings/navigationController.ts
  src/main/steps/c100-rebuild/people/address/address-manual.ts
  src/main/steps/c100-rebuild/people/util.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-581

#537 Release 2.2 unit tests quality
  src/main/app/case/DgsApiClient.ts
  src/main/app/controller/GetCaseController.test.ts
  src/main/app/controller/PostController.test.ts
  src/main/assets/images/tick.png
  src/main/assets/scss/main.scss
  src/main/public/img/icon-progress-tick.png
  src/main/steps/applicant/task-list/get.test.ts
  src/main/steps/applicant/task-list/get.ts
  src/main/steps/applicant/upload-document/get.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/content.test.ts
  src/main/steps/respondent/proceedings/court-proceedings/content.test.ts
  src/main/steps/respondent/proceedings/start/content.test.ts
  src/main/steps/respondent/proceedings/summary/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/summary/content.test.ts
  src/main/steps/respondent/task-list/get.test.ts
  src/main/steps/respondent/upload-document/get.test.ts
  src/main/steps/tasklistresponse/international-factors/summary/content.test.ts
  src/main/steps/tasklistresponse/proceedings/court-proceedings/content.test.ts
  src/main/steps/tasklistresponse/proceedings/start/content.test.ts
  src/main/steps/tasklistresponse/proceedings/summary/content.test.ts
  src/main/steps/tasklistresponse/safety_concerns/domestic_abuse_risk/content.test.ts
  src/main/steps/tasklistresponse/safety_concerns/domestic_abuse_risk_no/content.test.ts
  src/main/steps/tasklistresponse/safety_concerns/main_page/content.test.ts
  src/main/steps/tasklistresponse/safety_concerns/your_safety/content.test.ts
  src/main/steps/tasklistresponse/start/content.ts
  src/main/steps/tasklistresponse/start/get.test.ts
  src/main/steps/tasklistresponse/start/get.ts
  src/main/steps/tasklistresponse/summary-confirmation/content.test.ts
  src/main/steps/tasklistresponse/summary/content.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-537

#469 PRLC100-148-Other-Concerns
  src/main/steps/c100-rebuild/safety-concerns/other-concerns/other-issues/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/other-concerns/other-issues/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-469

#584 Prl 2579 bug fxes
  src/main/steps/applicant/task-list/content.test.ts
  src/main/steps/applicant/task-list/tasklist.test.ts
  src/main/steps/applicant/task-list/tasklist.ts
  src/main/steps/common/keep-details-private/KeepDetailsPrivateGetController.ts
  src/main/steps/common/respondent-task-list/template.njk
  src/main/steps/constants.test.ts
  src/main/steps/constants.ts
  src/main/steps/respondent/support-you-need-during-case/attending-the-court/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/attending-the-court/content.ts
  src/main/steps/respondent/support-you-need-during-case/communication-help/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/communication-help/content.ts
  src/main/steps/respondent/support-you-need-during-case/court-hearing-comfort/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/court-hearing-comfort/content.ts
  src/main/steps/respondent/support-you-need-during-case/court-hearing-support/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/court-hearing-support/content.ts
  src/main/steps/respondent/support-you-need-during-case/documents-support/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/documents-support/content.ts
  src/main/steps/respondent/support-you-need-during-case/language-requirements/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/language-requirements/content.ts
  src/main/steps/respondent/support-you-need-during-case/reasonable-adjustments/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/reasonable-adjustments/content.ts
  src/main/steps/respondent/support-you-need-during-case/special-arrangements/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/special-arrangements/content.ts
  src/main/steps/respondent/support-you-need-during-case/travelling-to-court/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/travelling-to-court/content.ts
  src/main/steps/respondent/task-list/tasklist.test.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/respondent/task-list/utils.ts
  src/main/steps/tasklistresponse/summary-confirmation/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-584

#585 PRLC100-358 Remove Duplication for other person Manul and lookup addr…
  config/development.yaml
  src/main/common/clients/launchDarklyClient.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/other-person-details/address/lookup/AddressLookupPostController.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/lookup/AddressLookupPostController.ts
  src/main/steps/c100-rebuild/other-person-details/address/lookup/content.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/ManualAddressPostController.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/ManualAddressPostController.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/content.ts
  src/main/steps/c100-rebuild/people/LookupAndManualAddressPostController.test.ts
  src/main/steps/c100-rebuild/people/LookupAndManualAddressPostController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-585

#587 PRLC100-361 C100 Rebuild Improve Code Coverage
  src/main/app/fees/fees-lookup-api.test.ts
  src/main/app/form/Form.test.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/postController.test.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/postController.test.ts
  src/main/steps/common/string-parser.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-587

#586 test case coverage
  src/main/steps/c100-rebuild/other-person-details/navigationController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/navigationController.test.ts
  src/main/steps/c100-rebuild/people/LookupAndManualAddressPostController.test.ts
  src/main/steps/c100-rebuild/people/address/address-manual.ts
  src/main/steps/c100-rebuild/respondent-details/address/lookup/AddressLookupPostController.test.ts
  src/main/steps/c100-rebuild/respondent-details/navigationController.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-586

#572 added mesasge
  sonar-project.properties
  src/main/steps/c100-rebuild/applicant/add-applicants/getController.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-manual.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/common/commonConfidentialityPostController.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/common/commonConfidentialityPostController.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/common/index.d.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/common/postController.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/common/postController.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/postContoller.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/postController.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start-alternative/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start-alternative/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start-alternative/postController.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start-alternative/postController.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start/postController.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start/postController.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/content.ts
  src/main/steps/c100-rebuild/applicant/personal-details/content.ts
  src/main/steps/c100-rebuild/c100sequence.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-572

#574 Fix sonar code-smell for PreProcessCaseData
  src/main/steps/c100-rebuild/PageStepConfigurator.ts
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/getController.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.test.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-574

#579 remove upload postcontroller for Miam and Consent Order ,Added test c…
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/consent-order/upload/postController.test.ts
  src/main/steps/c100-rebuild/consent-order/upload/postController.ts
  src/main/steps/c100-rebuild/miam/upload/postController.test.ts
  src/main/steps/c100-rebuild/miam/upload/postController.ts
  src/main/steps/c100-rebuild/uploadDocumentController.test.ts
  src/main/steps/c100-rebuild/uploadDocumentController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-579

#589 Release 2.2 bug fix
  src/main/steps/tasklistresponse/start/content.test.ts
  src/main/steps/tasklistresponse/start/tasklist.test.ts
  src/main/steps/tasklistresponse/start/tasklist.ts
  src/main/steps/tasklistresponse/summary/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-589

#560 Feature/prl 2498 terms and conditions
  src/main/steps/terms-and-conditions/content.test.ts
  src/main/steps/terms-and-conditions/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-560

#595 feat(PRLC100-329): Add dashboard for C100 application
  src/main/app/case/C100CaseApi.test.ts
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/case/case.ts
  src/main/app/controller/GetCaseController.test.ts
  src/main/app/controller/GetCaseController.ts
  src/main/app/controller/PostController.ts
  src/main/routes.ts
  src/main/steps/c100-rebuild/applicant/navigationController.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/get-case/getController.test.ts
  src/main/steps/c100-rebuild/get-case/getController.ts
  src/main/steps/c100-rebuild/landing/content.ts
  src/main/steps/c100-rebuild/landing/get.ts
  src/main/steps/c100-rebuild/landing/landingPageController.test.ts
  src/main/steps/c100-rebuild/landing/landingPageController.ts
  src/main/steps/c100-rebuild/landing/template.njk
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.test.ts
  src/main/steps/common/dashboard-page.njk
  src/main/steps/common/summary/utils.ts
  src/main/steps/edge-case/dashboard/template.njk
  src/main/steps/index.test.ts
  src/main/steps/prl-cases/citizenSequence.test.ts
  src/main/steps/prl-cases/dashboard-v1/template.njk
  src/main/steps/prl-cases/dashboard/DashboardGetController.test.ts
  src/main/steps/prl-cases/dashboard/DashboardGetController.ts
  src/main/steps/prl-cases/dashboard/content.test.ts
  src/main/steps/prl-cases/dashboard/content.ts
  src/main/steps/prl-cases/dashboard/controller/GetCaseController.test.ts
  src/main/steps/prl-cases/dashboard/controller/GetCaseController.ts
  src/main/steps/prl-cases/dashboard/form.njk
  src/main/steps/prl-cases/dashboard/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-595

#599 feat(PLRC100-321) add: added feature for Ask applicant Case Name befo…
  src/main/app/form/validation.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/case-name/content.test.ts
  src/main/steps/c100-rebuild/case-name/content.ts
  src/main/steps/c100-rebuild/case-name/template.njk
  src/main/steps/c100-rebuild/start/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-599

#601 Feature/c100 check your answer/sonar
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/peopleHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/reasonableAdjustment.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/safetyConcernHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/satetyConcernHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/check-your-answers/util/helpWithFee.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/miam.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/miam.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/otherProceeding.util.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-601

#605 Feature/check your answer/test
  src/main/modules/payments/paymentHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/courtOrderHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/peopleHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/safetyConcernHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/satetyConcernHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/util/hearingwithout.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/hearingwithout.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/miam.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/otherProceeding.util.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-605

#606 PRLC100-344 - Submit case/Pay & submit changes
  src/main/app/case/C100CaseApi.test.ts
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.ts
  src/main/modules/payments/paymentController.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-606

#594 C100 rebuild test coverage improvement
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.test.ts
  src/main/steps/c100-rebuild/applicant/navigationController.test.ts
  src/main/steps/c100-rebuild/child-details/live-with/postController.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-594

#593 fix(PLRC100-337) fix:address validation fixes for other-person,Respon…
  src/main/steps/c100-rebuild/applicant/address/common/address-manual.ts
  src/main/steps/c100-rebuild/applicant/address/manual/content.test.ts
  src/main/steps/c100-rebuild/applicant/address/manual/content.ts
  src/main/steps/c100-rebuild/applicant/address/select/content.test.ts
  src/main/steps/c100-rebuild/applicant/address/select/content.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/address/manual/content.ts
  src/main/steps/c100-rebuild/people/address/address-manual.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-593

#609 PRLC100-321 Added save and comeback later feature for Applicant Case …
  package.json
  src/main/app/case/C100CaseApi.test.ts
  src/main/app/case/C100CaseApi.ts
  src/main/app/controller/GetCaseController.ts
  src/main/modules/oidc/index.ts
  src/main/steps/c100-rebuild/applicant/navigationController.test.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/start/template.njk
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-609

#608 Feature/check your answer/test case and code
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/check-your-answers/util/miam.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/otherProceeding.util.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-608

#612 PRLC100-361-Test-Coverage-Improvements
  src/main/app/form/validation.test.ts
  src/main/app/utils/featureToggles.test.ts
  src/main/steps/c100-rebuild/applicant/util.test.ts
  src/main/steps/c100-rebuild/miam/util.test.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.test.ts
  src/main/steps/common/string-parser.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-612

#598 Fixed issue reported in testing
  src/main/steps/common/summary/utils.ts
  src/main/steps/tasklistresponse/start/content.test.ts
  src/main/steps/tasklistresponse/start/section-titles.ts
  src/main/steps/tasklistresponse/start/tasklist.test.ts
  src/main/steps/tasklistresponse/summary/content.test.ts
  src/main/steps/tasklistresponse/summary/content.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-598

#616 PRLC100-344 - Added changes to create only service in case of help with fees
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/case.ts
  src/main/modules/payments/paymentApi.test.ts
  src/main/modules/payments/paymentApi.ts
  src/main/modules/payments/paymentController.ts
  src/main/modules/payments/paymentHelper.test.ts
  src/main/modules/payments/paymentHelper.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-616

#611 added log for c100 rebuild LD flag
  config/default.yaml
  config/development.yaml
  src/main/common/clients/launchDarklyClient.ts
  src/main/modules/feature-toggle/index.ts
  src/main/modules/oidc/index.ts
  src/main/server.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-611

#618 fix issue - added hint text and fixed error messages
  src/main/steps/c100-rebuild/screening-questions/permissions-why/content.test.ts
  src/main/steps/c100-rebuild/screening-questions/permissions-why/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-618

#613 fix(PLRC100-341 fix: upload file dot issue fix & add-applicant getcon…
  src/main/steps/c100-rebuild/applicant/add-applicants/getController.test.ts
  src/main/steps/c100-rebuild/uploadDocumentController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-613

#627 Security scan fix
  audit.json
  package.json
  security.sh
  src/test/mutation/stryker.conf.js
  yarn.lock
Labels: ns:private-law, prd:prl, enable_security_scan, rel:prl-citizen-frontend-pr-627, enable_mutation_test

#629 test coverage for Address controller
  src/main/steps/c100-rebuild/applicant/address/lookup/AddressLookupPostController.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/ManualAddressPostController.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-629

#631 C100 rebuild test coverage improvement
  src/main/steps/c100-rebuild/applicant/address/manual/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/navigationController.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-631

#615 Feature/prlc100 302/dynamic screen routings
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts
  src/main/steps/c100-rebuild/check-your-answers/common/dateformatter.test.ts
  src/main/steps/c100-rebuild/check-your-answers/common/dateformatter.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/hearingdetailHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/hearingdetailHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/safetyConcernHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/satetyConcernHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/hearingwithout.util.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part1/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-615

#625 PR for C100 Rebuild Base Branch
  README.md
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/default.yaml
  config/development.yaml
  sonar-project.properties
  src/main/app/auth/user/oidc.ts
  src/main/app/case/C100CaseApi.test.ts
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/case/from-api-format.ts
  src/main/app/controller/PostController.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/modules/oidc/index.ts
  src/main/modules/payments/paymentController.ts
  src/main/modules/payments/paymentHelper.ts
  src/main/modules/session/index.ts
  src/main/routes/home.ts
  src/main/steps/applicant/task-list/utils.test.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/AddressLookupPostController.test.ts
  src/main/steps/c100-rebuild/applicant/address/manual/content.test.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts
  src/main/steps/c100-rebuild/check-your-answers/common/dateformatter.test.ts
  src/main/steps/c100-rebuild/check-your-answers/common/dateformatter.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/hearingdetailHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/hearingdetailHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/safetyConcernHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/satetyConcernHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/hearingwithout.util.ts
  src/main/steps/c100-rebuild/child-details/child-matters/content.test.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part1/content.ts
  src/main/steps/c100-rebuild/miam/get-doc/postController.ts
  src/main/steps/c100-rebuild/other-person-details/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.ts
  src/main/steps/c100-rebuild/other-proceedings/navigationController.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/ManualAddressPostController.test.ts
  src/main/steps/c100-rebuild/screening-questions/contact-representative/postController.ts
  src/main/steps/common/confirm-contact-details/checkanswers/content.ts
  src/main/steps/prl-cases/dashboard/DashboardGetController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-625

#614 Chart Upgrade for citizen-frontend
  charts/prl-citizen-frontend/Chart.yaml
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-614

#493 PRLC100-237-Welsh translation
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.ts
  src/main/steps/c100-rebuild/childaddress/content.test.ts
  src/main/steps/c100-rebuild/childaddress/content.ts
  src/main/steps/c100-rebuild/childaddress/template.njk
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part1/content.test.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part1/content.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part2/content.test.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part2/content.ts
  src/main/steps/c100-rebuild/typeoforder/caorder/content.test.ts
  src/main/steps/c100-rebuild/typeoforder/caorder/content.ts
  src/main/steps/c100-rebuild/typeoforder/select-courtorder/content.test.ts
  src/main/steps/c100-rebuild/typeoforder/select-courtorder/content.ts
  src/main/steps/c100-rebuild/typeoforder/shortstatement/content.test.ts
  src/main/steps/c100-rebuild/typeoforder/shortstatement/content.ts
  src/main/steps/common/common.content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-493

#641 Feature/test case fixes for c100 rebuild base
  src/main/steps/c100-rebuild/check-your-answers/util/miam.util.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-641

#636 fixes
  src/main/app/case/CosApiClient.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/modules/csrf/index.ts
  src/main/modules/fileupload/index.ts
  src/main/routes.ts
  src/main/server.ts
  src/main/steps/applicant/task-list/content.test.ts
  src/main/steps/applicant/task-list/content.ts
  src/main/steps/applicant/task-list/get.test.ts
  src/main/steps/applicant/task-list/tasklist.ts
  src/main/steps/applicant/task-list/template.njk
  src/main/steps/applicant/task-list/utils.ts
  src/main/steps/applicant/upload-document/DocumentManagementGetController.test.ts
  src/main/steps/applicant/upload-document/DocumentManagementGetController.ts
  src/main/steps/applicant/upload-document/template.njk
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
  src/main/steps/applicant/yourdocuments/alldocuments/digitaldownloads/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/drug_alcohol_tests/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/paternity_test_reports/content.ts
  src/main/steps/c100-rebuild/consent-order/upload/content.ts
  src/main/steps/common/page.njk
  src/main/steps/common/tasklist/template.njk
  src/main/steps/common/webpack/css.njk
  src/main/steps/respondent/task-list/content.test.ts
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/respondent/task-list/get.test.ts
  src/main/steps/respondent/task-list/tasklist.test.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/respondent/task-list/template.njk
  src/main/steps/respondent/task-list/utils.ts
  src/main/steps/respondent/upload-document/RespondentDocumentManagementGetController.test.ts
  src/main/steps/respondent/upload-document/RespondentDocumentManagementGetController.ts
  src/main/steps/respondent/upload-document/template.njk
  src/main/steps/respondent/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
  src/main/steps/respondent/yourdocuments/alldocuments/drug_alcohol_tests/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/paternity_test_reports/content.ts
  src/test/unit/utils/mockUserCase.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-636

#642 fix issue - minor edits for po signoff
  src/main/steps/c100-rebuild/child-details/further-information/content.test.ts
  src/main/steps/c100-rebuild/child-details/further-information/content.ts
  src/main/steps/c100-rebuild/screening-questions/consent-agreement/content.test.ts
  src/main/steps/c100-rebuild/screening-questions/consent-agreement/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-642

#634 Release 2.2 bug fix
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
  src/main/steps/common/respondent-summary/form.njk
  src/main/steps/tasklistresponse/summary/content.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-634

#653 fix issue - save and come back button not working
  src/main/steps/c100-rebuild/applicant/contact-detail/postController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-653

#654 added check for the backbutton to be disbaled so that check your answ…
  src/main/steps/c100-rebuild/check-your-answers/helpers/hearingdetailHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-654

#637 feature/2075-cookies
  src/main/steps/cookies/content.test.ts
  src/main/steps/cookies/content.ts
  src/main/steps/cookies/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-637

#656 testcases
  src/main/steps/c100-rebuild/applicant/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/applicant/address/lookup/content.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/child-details/further-information/content.test.ts
  src/main/steps/c100-rebuild/child-details/further-information/content.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/content.test.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/content.ts
  src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-656
