Repository hmcts/prl-citizen-frontend, pull requests merged in 2023-03, with the labels that each got.

#815 Testcase coverage for task-list
  sonar-project.properties
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/progress-bar/utils.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.test.ts
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/common/task-list/content.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.test.ts
  src/main/steps/common/task-list/utils.test.ts
  src/main/steps/common/task-list/utils.ts
  src/test/end-to-end/pages/C100-Rebuild/CreateApplication.js
  src/test/end-to-end/pages/C100-Rebuild/MiniDashboard.js
  src/test/end-to-end/steps_file.js
  src/test/end-to-end/tests/C100Rebuild-BaseFlow.js
  src/test/end-to-end/tests/C100Rebuild-MiamDocumentFlow.js
  src/test/end-to-end/tests/C100Rebuild-OtherProceedingsFlow.js
  src/test/end-to-end/tests/C100Rebuild-WithAgreement.js
  src/test/end-to-end/tests/C100Rebuild-WithUrgencyFlow.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-815

#830 keep helm
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
  README.md
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-830

#832 Cross browser fix
  Jenkinsfile_nightly
Labels: ns:private-law, prd:prl, enable_fortify_scan, enable_security_scan, enable_full_functional_tests, keep-helm, enable_cross_browser_test, rel:prl-citizen-frontend-pr-832

#834 code smell major minor info
  src/main/app/case/case.ts
  src/main/steps/applicant/support-you-need-during-case/SupportYouNeedDuringCaseController.ts
  src/main/steps/applicant/task-list/navigationController.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/InternationElementsHelper.ts
  src/main/steps/common/summary-international/utils.ts
  src/main/steps/respondent/task-list/navigationController.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/helpers/satetyConcernHelper.ts
  src/main/steps/tasklistresponse/proceedings/documentUpload/getController.ts
  src/main/steps/tasklistresponse/proceedings/order-details/postController.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/navigationController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-834

#843 Zap fix
  Jenkinsfile_nightly
  audit.json
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-843

#837 info screen
  src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/content.ts
  src/main/steps/c100-rebuild/screening-questions/contact-representative/content.test.ts
  src/main/steps/c100-rebuild/screening-questions/contact-representative/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/common/task-list/components/progress-bar/content.ts
  src/main/steps/common/task-list/components/side-links/content.ts
  src/main/steps/common/task-list/components/tasklist/content.ts
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/common/task-list/content.ts
  src/main/steps/prl-cases/dashboard/content.test.ts
  src/main/steps/prl-cases/dashboard/content.ts
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-837

#831 Feature/task list withdrawcase
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/GetController.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/applicant/applicantCaseSequence.test.ts
  src/main/steps/applicant/applicantCaseSequence.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/withdraw/confirmation/content.test.ts
  src/main/steps/c100-rebuild/withdraw/confirmation/content.ts
  src/main/steps/c100-rebuild/withdraw/confirmation/template.njk
  src/main/steps/c100-rebuild/withdraw/content.test.ts
  src/main/steps/c100-rebuild/withdraw/content.ts
  src/main/steps/c100-rebuild/withdraw/postController.ts
  src/main/steps/c100-rebuild/withdraw/template.njk
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/common/task-list/components/notification-banner/notification-banner.macro.njk
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  src/main/steps/common/task-list/components/progress-bar/utils.test.ts
  src/main/steps/common/task-list/components/progress-bar/utils.ts
  src/main/steps/common/task-list/components/tasklist/content.ts
  src/main/steps/common/task-list/components/tasklist/utils.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/common/task-list/content.ts
  src/main/steps/common/task-list/utils.ts
  src/main/steps/prl-cases/dashboard/content.ts
  src/main/steps/prl-cases/dashboard/tabView.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-831

#841 bug fixes check your answer
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-841

#838 Revert "c100 - payment stub for case submission"
  src/main/app/case/definition.ts
  src/main/app/controller/GetCaseController.ts
  src/main/app/controller/PostController.ts
  src/main/steps/c100-rebuild/applicant/contact-preference/content.test.ts
  src/main/steps/c100-rebuild/applicant/contact-preference/content.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.ts
  src/main/steps/prl-cases/dashboard/content.test.ts
  src/main/steps/prl-cases/dashboard/content.ts
  src/main/steps/prl-cases/dashboard/tabView.test.ts
  src/main/steps/prl-cases/dashboard/tabView.ts
  src/main/steps/prl-cases/dashboard/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-838

#850 Release 4 0 sonar fixes
  charts/prl-citizen-frontend/values.preview.template.yaml
  sonar-project.properties
  src/main/app/form/validation.test.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/postController.test.ts
  src/main/steps/common/summary-international/utils.test.ts
  src/main/steps/prl-cases/dashboard/utils.test.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/navigationController.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-850

#853 bug fixes check your answer
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-853

#851 increase test coverage for branch c100-dashboard-tasklist
  src/main/steps/applicant/contact-preferences/contact-email/content.test.ts
  src/main/steps/applicant/contact-preferences/contact-post/contest.test.ts
  src/main/steps/applicant/contact-preferences/contact-preferences/contest.test.ts
  src/main/steps/c100-rebuild/applicant/contact-preference/content.test.ts
  src/main/steps/common/contact-preferences/ContactPreferencesGetController.test.ts
  src/main/steps/common/contact-preferences/ContactPreferencesMapper.test.ts
  src/main/steps/common/contact-preferences/contact-email/content.test.ts
  src/main/steps/common/contact-preferences/contact-post/content.test.ts
  src/main/steps/common/contact-preferences/contact-preferences/content.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-851

#854 Increasing coverage to fix sonar build issues
  src/main/steps/applicant/applicantCaseSequence.test.ts
  src/main/steps/applicant/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.test.ts
  src/main/steps/common/contact-preferences/ContactPreferencesGetController.test.ts
  src/main/steps/common/contact-preferences/ContactPreferencesMapper.test.ts
  src/main/steps/common/contact-preferences/ContactPreferencesPostController.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-854

#847 COURT ORDER
  config/default.yaml
  src/main/steps/applicant/applicantCaseSequence.ts
  src/main/steps/common/task-list/components/tasklist/content.ts
  src/main/steps/common/task-list/components/tasklist/utils.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-847

#856 testcase coverage
  src/main/steps/c100-rebuild/withdraw/postController.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/progress-bar/utils.test.ts
  src/main/steps/common/task-list/utils.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-856

#858 upload document on task-list
  src/main/app/document/DocumentManagementController.ts
  src/main/steps/common/task-list/components/tasklist/content.ts
  src/main/steps/common/task-list/components/tasklist/utils.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-858

#859 feature/PRL3304
  src/main/steps/applicant/applicantCaseSequence.test.ts
  src/main/steps/applicant/applicantCaseSequence.ts
  src/main/steps/applicant/hearing-needs/support-help/content.test.ts
  src/main/steps/applicant/hearing-needs/support-help/content.ts
  src/main/steps/applicant/hearing-needs/support-help/template.njk
  src/main/steps/common/hearing-needs/content.test.ts
  src/main/steps/common/hearing-needs/content.ts
  src/main/steps/common/hearing-needs/template.njk
  src/main/steps/common/task-list/components/tasklist/content.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-859

#802 added few welsh translations
  src/main/steps/applicant/task-list/content.ts
  src/main/steps/applicant/task-list/tasklist-items.ts
  src/main/steps/applicant/task-list/tasklist.test.ts
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-802

#862 feat(PRL-3335): Add breadcrumb feature to application
  src/main/app/controller/GetController.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/applicant/confirm-contact-details/checkanswers/content.test.ts
  src/main/steps/applicant/confirm-contact-details/checkanswers/content.ts
  src/main/steps/applicant/confirm-contact-details/checkanswers/template.njk
  src/main/steps/applicant/upload-document/content.test.ts
  src/main/steps/applicant/upload-document/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/content.ts
  src/main/steps/common/breadcrumb/BreadcrumbController.ts
  src/main/steps/common/breadcrumb/breadcrumb.macro.njk
  src/main/steps/common/breadcrumb/content.ts
  src/main/steps/common/breadcrumb/template.njk
  src/main/steps/common/task-list/content.ts
  src/main/steps/common/task-list/template.njk
  src/main/steps/common/tasklistalldocuments/template.njk
  src/main/steps/common/upload-document/template.njk
  src/main/steps/prl-cases/dashboard/DashboardGetController.test.ts
  src/main/steps/prl-cases/dashboard/DashboardGetController.ts
  src/main/steps/prl-cases/dashboard/tabView.ts
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-862

#804 fixed check ans screen , date issue , yesnoempty issues
  config/development.yaml
  src/main/steps/applicant/task-list/content.ts
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/respondent/task-list/tasklist.test.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/tasklistresponse/proceedings/ProceedingDetailsMapper.ts
  src/main/steps/tasklistresponse/proceedings/navigationController.test.ts
  src/main/steps/tasklistresponse/proceedings/navigationController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-804, keep-helm

#866 fixing the minor code smell in ContactPreferencesPostController.ts
  src/main/steps/common/contact-preferences/ContactPreferencesPostController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-866

#836 Feature/prl 3239
  src/main/app/controller/PostController.ts
  src/main/modules/oidc/index.ts
  src/main/routes.ts
  src/main/steps/prl-cases/CaseActivationPostController.test.ts
  src/main/steps/prl-cases/CaseActivationPostController.ts
  src/main/steps/prl-cases/citizenSequence.test.ts
  src/main/steps/prl-cases/citizenSequence.ts
  src/main/steps/prl-cases/dashboard/template.njk
  src/main/steps/prl-cases/pin-activation/case-activated/content.test.ts
  src/main/steps/prl-cases/pin-activation/case-activated/content.ts
  src/main/steps/prl-cases/pin-activation/case-activated/template.njk
  src/main/steps/prl-cases/pin-activation/enter-pin/content.test.ts
  src/main/steps/prl-cases/pin-activation/enter-pin/content.ts
  src/main/steps/prl-cases/pin-activation/enter-pin/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-836

#860 Testcase/coverage
  sonar-project.properties
  src/main/steps/common/task-list/components/tasklist/utils.test.ts
  src/main/steps/common/task-list/utils.test.ts
  src/main/steps/prl-cases/dashboard/tabView.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-860

#869 increasing code coverage for getController.ts
  src/main/app/controller/GetController.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-869

#868 testcases
  src/main/steps/applicant/applicantCaseSequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/utils.test.ts
  src/main/steps/prl-cases/CaseActivationPostController.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-868

#871 tasklist notification banner
  src/main/steps/common/breadcrumb/content.ts
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/prl-cases/dashboard/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-871

#870 welsh translation for tasklist and 1 missing translation on C100 journey
  src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.ts
  src/main/steps/common/task-list/components/progress-bar/content.ts
  src/main/steps/common/task-list/components/side-links/content.ts
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/prl-cases/dashboard/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-870

#852 Revert "bug fixes check your answer"
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-852

#810 Prl 3032 citizen accessibility statement
  src/main/steps/accessibility-statement/content.test.ts
  src/main/steps/accessibility-statement/content.ts
  src/main/steps/accessibility-statement/template.njk
  src/main/steps/c100-rebuild/check-your-answers/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-810, keep-helm

#873 fix (c100-withdrawal-case-status): Fix c100 case withdrawal status update
  src/main/steps/c100-rebuild/withdraw/confirmation/content.ts
  src/main/steps/c100-rebuild/withdraw/confirmation/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-873
