Repository hmcts/prl-citizen-frontend, pull requests merged in 2023-01, with the labels that each got.

#602 tick image to train track CA Respondent
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/default.yaml
  config/development.yaml
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/definition.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/utils/progress-bar-utils.test.ts
  src/main/app/utils/progress-bar-utils.ts
  src/main/assets/images/icon-progress-tick.png
  src/main/assets/scss/main.scss
  src/main/public/img/icon-progress-tick.png
  src/main/routes.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/applicant/task-list/content.ts
  src/main/steps/applicant/task-list/get.test.ts
  src/main/steps/applicant/upload-document/get.test.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/controller/ViewAllDocumentsPostController.test.ts
  src/main/steps/common/controller/ViewAllDocumentsPostController.ts
  src/main/steps/common/progress-bar.njk
  src/main/steps/contact-us/get.test.ts
  src/main/steps/cookies/get.test.ts
  src/main/steps/privacy-policy/get.test.ts
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/respondent/task-list/get.test.ts
  src/main/steps/respondent/task-list/tasklist.test.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/respondent/upload-document/get.test.ts
  src/main/steps/tasklistresponse/start/get.test.ts
  src/main/steps/terms-and-conditions/get.test.ts
  src/main/steps/urls.ts
  webpack.config.js
  webpack/hmctsFrontend.js
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-602

#726 Nightly build fix
  package.json
  src/main/modules/payments/paymentApi.test.ts
  src/main/modules/payments/paymentController.test.ts
  src/main/modules/payments/paymentHelper.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-726

#304 Create e2e for PRL-2064
  src/test/end-to-end/pages/uploadDocuments.js
  src/test/end-to-end/steps_file.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-304, PRLFeatureTeam, Release 3.1

#543 Crossbrowser setup
  Jenkinsfile_nightly
  bin/run-crossbrowser-tests.sh
  package.json
  saucelabs.conf.js
  src/test/end-to-end/crossbrowser/supportedBrowsers.js
  src/test/end-to-end/helpers/SauceLabsReportingHelper.js
  src/test/end-to-end/pages/ConsentToApplication.js
  src/test/end-to-end/pages/EnterPinPage.js
  src/test/end-to-end/pages/LoginPage.js
  src/test/end-to-end/pages/SupportYouNeedDuringYourCase-Applicant.js
  src/test/end-to-end/pages/SupportYouNeedDuringYourCase-RespondentCADA.js
  src/test/end-to-end/pages/uploadDocuments.js
  src/test/end-to-end/steps_file.js
  src/test/end-to-end/tests/CurrentOrPreviousProceedings.js
  src/test/end-to-end/tests/InternationalElement.js
  src/test/end-to-end/tests/SupportYouNeedDuringYourCaseApplicant.js
  src/test/end-to-end/tests/SupportYouNeedDuringYourCaseRespondent.js
Labels: ns:private-law, prd:prl, Release 2.3, rel:prl-citizen-frontend-pr-543, PRLFeatureTeam, Release 3.1

#731 bug fix+6/1 translation
  src/main/steps/c100-rebuild/applicant/contact-preference/content.test.ts
  src/main/steps/c100-rebuild/applicant/contact-preference/content.ts
  src/main/steps/c100-rebuild/check-your-answers/common/dateformatter.test.ts
  src/main/steps/c100-rebuild/check-your-answers/common/dateformatter.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/InternationElementsHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/InternationElementsHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/hearingdetailHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/hearingdetailHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/peopleHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/peopleHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/safetyConcernHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/satetyConcernHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/check-your-answers/util/miam.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/otherProceeding.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/otherProceeding.util.ts
  src/main/steps/c100-rebuild/child-details/other-children/personal-details/content.test.ts
  src/main/steps/c100-rebuild/child-details/other-children/personal-details/content.ts
  src/main/steps/c100-rebuild/child-details/personal-details/content.test.ts
  src/main/steps/c100-rebuild/child-details/personal-details/content.ts
  src/main/steps/c100-rebuild/childaddress/content.test.ts
  src/main/steps/c100-rebuild/childaddress/content.ts
  src/main/steps/c100-rebuild/hearing-urgency/urgent/content.test.ts
  src/main/steps/c100-rebuild/hearing-urgency/urgent/content.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part1/content.test.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part1/content.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part2/content.test.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part2/content.ts
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/content.test.ts
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/content.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.ts
  src/main/steps/c100-rebuild/safety-concerns/applicant/report-abuse/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/applicant/report-abuse/content.ts
  src/main/steps/c100-rebuild/safety-concerns/child/report-abuse/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/child/report-abuse/content.ts
  src/main/steps/c100-rebuild/safety-concerns/concern-guidance/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/concern-guidance/content.ts
  src/main/steps/c100-rebuild/screening-questions/consent-agreement/content.test.ts
  src/main/steps/c100-rebuild/screening-questions/consent-agreement/content.ts
  src/main/steps/c100-rebuild/screening-questions/consent-agreement/template.njk
  src/main/steps/c100-rebuild/start/content.test.ts
  src/main/steps/c100-rebuild/start/content.ts
  src/main/steps/common/common.content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-731

#735 fix(vulnerability-issues): Update yarn-audit for vulnerability
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-735

#738 Crossbrowser Nightly build fixes
  src/test/end-to-end/helpers/generalHelper.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-738

#739 fix(PRL-2897): Remove custom.css
  src/main/steps/common/webpack/css-template.njk
  src/main/steps/common/webpack/css.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-739

#725 Release 3.0 rebase
  charts/prl-citizen-frontend/values.preview.template.yaml
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/definition.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/utils/progress-bar-utils.test.ts
  src/main/app/utils/progress-bar-utils.ts
  src/main/assets/images/icon-progress-tick.png
  src/main/assets/scss/main.scss
  src/main/public/img/icon-progress-tick.png
  src/main/routes.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/applicant/task-list/content.ts
  src/main/steps/applicant/task-list/get.test.ts
  src/main/steps/applicant/task-list/utils.test.ts
  src/main/steps/applicant/upload-document/get.test.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/controller/ViewAllDocumentsPostController.test.ts
  src/main/steps/common/controller/ViewAllDocumentsPostController.ts
  src/main/steps/common/progress-bar.njk
  src/main/steps/contact-us/get.test.ts
  src/main/steps/cookies/get.test.ts
  src/main/steps/privacy-policy/get.test.ts
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/respondent/task-list/get.test.ts
  src/main/steps/respondent/task-list/tasklist.test.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/respondent/upload-document/get.test.ts
  src/main/steps/tasklistresponse/start/get.test.ts
  src/main/steps/terms-and-conditions/get.test.ts
  src/main/steps/urls.ts
  webpack.config.js
  webpack/hmctsFrontend.js
Labels: ns:private-law, prd:prl, PRLFeatureTeam, Release 3.1, rel:prl-citizen-frontend-pr-725

#693 PRL-2628/International_Elements
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/default.yaml
  config/development.yaml
  src/main/steps/common/summary-international/form.njk
  src/main/steps/common/summary-international/template.njk
  src/main/steps/common/summary-international/utils.test.ts
  src/main/steps/common/summary-international/utils.ts
  src/main/steps/tasklistresponse/international-factors/jurisdiction/content.test.ts
  src/main/steps/tasklistresponse/international-factors/jurisdiction/content.ts
  src/main/steps/tasklistresponse/international-factors/parents/content.test.ts
  src/main/steps/tasklistresponse/international-factors/parents/content.ts
  src/main/steps/tasklistresponse/international-factors/request/content.test.ts
  src/main/steps/tasklistresponse/international-factors/request/content.ts
  src/main/steps/tasklistresponse/international-factors/start/content.test.ts
  src/main/steps/tasklistresponse/international-factors/start/content.ts
  src/main/steps/tasklistresponse/international-factors/summary/content.test.ts
  src/main/steps/tasklistresponse/international-factors/summary/content.ts
  src/main/steps/tasklistresponse/international-factors/summary/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-693, PRLFeatureTeam, Release 3.1

#730 PRL-2494:C7 changes-ther-proceeding
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/app/case/definition.ts
  src/main/routes.ts
  src/main/steps/tasklistresponse/proceedings/ProceedingDetailsMapper.test.ts
  src/main/steps/tasklistresponse/proceedings/ProceedingDetailsMapper.ts
  src/main/steps/tasklistresponse/proceedings/ProceedingGetController.test.ts
  src/main/steps/tasklistresponse/proceedings/ProceedingGetController.ts
  src/main/steps/tasklistresponse/proceedings/ProceedingPostController.test.ts
  src/main/steps/tasklistresponse/proceedings/ProceedingPostController.ts
  src/main/steps/tasklistresponse/proceedings/courtproceedings/content.test.ts
  src/main/steps/tasklistresponse/proceedings/courtproceedings/content.ts
  src/main/steps/tasklistresponse/proceedings/document-summary/content.ts
  src/main/steps/tasklistresponse/proceedings/navigationController.ts
  src/main/steps/tasklistresponse/proceedings/proceeding-details/content.test.ts
  src/main/steps/tasklistresponse/proceedings/proceeding-details/content.ts
  src/main/steps/tasklistresponse/responseCaseSequence.ts
  src/main/steps/tasklistresponse/start/content.test.ts
  src/main/steps/tasklistresponse/start/tasklist.test.ts
  src/main/steps/tasklistresponse/start/tasklist.ts
  src/main/steps/tasklistresponse/start/utils.ts
  src/main/steps/tasklistresponse/summary/content.ts
  src/main/steps/urls.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, PRLFeatureTeam, Release 3.1, rel:prl-citizen-frontend-pr-730

#719 Ithc text box validation
  sonar-project.properties
  src/main/steps/applicant/confirm-contact-details/contactdetails/content.test.ts
  src/main/steps/applicant/confirm-contact-details/personaldetails/content.test.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/content.test.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/content.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/content.test.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/content.ts
  src/main/steps/c100-rebuild/applicant/personal-details/content.test.ts
  src/main/steps/c100-rebuild/applicant/personal-details/content.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/case-name/content.test.ts
  src/main/steps/c100-rebuild/case-name/content.ts
  src/main/steps/c100-rebuild/child-details/add-children/content.test.ts
  src/main/steps/c100-rebuild/child-details/add-children/content.ts
  src/main/steps/c100-rebuild/child-details/other-children/names/content.test.ts
  src/main/steps/c100-rebuild/child-details/other-children/names/content.ts
  src/main/steps/c100-rebuild/child-details/other-children/personal-details/content.test.ts
  src/main/steps/c100-rebuild/child-details/other-children/personal-details/content.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/content.test.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/content.ts
  src/main/steps/c100-rebuild/child-details/personal-details/content.test.ts
  src/main/steps/c100-rebuild/child-details/personal-details/content.ts
  src/main/steps/c100-rebuild/hearing-urgency/urgent-details/content.test.ts
  src/main/steps/c100-rebuild/hearing-urgency/urgent-details/content.ts
  src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.ts
  src/main/steps/c100-rebuild/other-person-details/personal-details/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/personal-details/content.ts
  src/main/steps/c100-rebuild/other-person-details/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/people/AddPeoplePostContoller.test.ts
  src/main/steps/c100-rebuild/people/AddPeoplePostContoller.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/content.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/content.ts
  src/main/steps/common/confirm-contact-details/contactdetails/content.test.ts
  src/main/steps/common/confirm-contact-details/contactdetails/content.ts
  src/main/steps/common/confirm-contact-details/personaldetails/content.test.ts
  src/main/steps/common/confirm-contact-details/personaldetails/content.ts
  src/main/steps/respondent/confirm-contact-details/contactdetails/content.test.ts
  src/main/steps/respondent/confirm-contact-details/personaldetails/content.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-719

#717 feat(PRL-2841): Update dashboard to show only sections having cases
  src/main/steps/prl-cases/dashboard/content.ts
  src/main/steps/prl-cases/dashboard/form.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-717, PRLFeatureTeam, Release 3.1

#513 Dac aapplicant reasonable adjustments
  src/main/steps/applicant/support-you-need-during-case/communication-help/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/communication-help/content.ts
  src/main/steps/applicant/support-you-need-during-case/court-hearing-comfort/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/court-hearing-comfort/content.ts
  src/main/steps/applicant/support-you-need-during-case/court-hearing-support/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/court-hearing-support/content.ts
  src/main/steps/applicant/support-you-need-during-case/documents-support/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/documents-support/content.ts
  src/main/steps/applicant/support-you-need-during-case/language-requirements/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/language-requirements/content.ts
  src/main/steps/applicant/support-you-need-during-case/reasonable-adjustments/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/reasonable-adjustments/content.ts
  src/main/steps/applicant/support-you-need-during-case/safety-arrangements/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/safety-arrangements/content.ts
  src/main/steps/applicant/support-you-need-during-case/summary/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/summary/content.ts
  src/main/steps/applicant/support-you-need-during-case/travelling-to-court/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/travelling-to-court/content.ts
  src/main/steps/applicant/support-you-need-during-case/unable-to-take-court-proceedings/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/unable-to-take-court-proceedings/content.ts
  src/main/steps/respondent/support-you-need-during-case/communication-help/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/communication-help/content.ts
  src/main/steps/respondent/support-you-need-during-case/court-hearing-comfort/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/court-hearing-comfort/content.ts
  src/main/steps/respondent/support-you-need-during-case/court-hearing-support/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/court-hearing-support/content.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/attending-the-court/content.test.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/attending-the-court/content.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/communication-help/content.test.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/communication-help/content.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/court-hearing-comfort/content.test.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/court-hearing-comfort/content.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/court-hearing-support/content.test.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/court-hearing-support/content.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/documents-support/content.test.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/documents-support/content.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/language-requirements/content.test.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/language-requirements/content.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/reasonable-adjustments/content.test.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/reasonable-adjustments/content.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/special-arrangements/content.test.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/special-arrangements/content.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/travelling-to-court/content.test.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/travelling-to-court/content.ts
  src/test/end-to-end/pages/SupportYouNeedDuringYourCase-Applicant.js
Labels: ns:private-law, prd:prl, Release 2.3, rel:prl-citizen-frontend-pr-513, Release 3.1

#754 feat(PRL-2931): Update service name
  src/main/steps/common/common.content.ts
  src/main/steps/prl-cases/dashboard/DashboardGetController.ts
  src/main/steps/prl-cases/dashboard/content.test.ts
  src/main/steps/prl-cases/dashboard/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-754

#752 feat(PRL-2842): Update case dashboard to show relevant section for closed state
  src/main/steps/applicant/task-list/content.test.ts
  src/main/steps/applicant/task-list/tasklist.ts
  src/main/steps/common/tasklist/template.njk
  src/main/steps/respondent/task-list/tasklist.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-752

#756 Upgrade node version 3.1
  charts/prl-citizen-frontend/Chart.yaml
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/default.yaml
  config/development.yaml
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-756

#661 guide respondent to tasklist from the url in the no…
  src/main/app/controller/GetCaseController.test.ts
  src/main/app/controller/GetCaseController.ts
  src/main/modules/oidc/index.ts
  src/main/routes.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-661, PRLFeatureTeam, Release 3.1

#757 Prl 2940
  config/development.yaml
  src/main/app/controller/GetController.ts
  src/main/app/form/Form.ts
  src/main/steps/applicant/task-list/content.test.ts
  src/main/steps/applicant/task-list/content.ts
  src/main/steps/applicant/task-list/utils.ts
  src/main/steps/applicant/upload-document/document-sharing-details/template.njk
  src/main/steps/applicant/upload-document/upload-documents-success/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.test.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
  src/main/steps/c100-rebuild/address-select-util.test.ts
  src/main/steps/c100-rebuild/address-select-util.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-select.test.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-select.ts
  src/main/steps/c100-rebuild/applicant/navigationController.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/InternationElementsHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/InternationElementsHelper.ts
  src/main/steps/c100-rebuild/child-details/childDetailPostController.ts
  src/main/steps/c100-rebuild/people/address/address-select.test.ts
  src/main/steps/c100-rebuild/people/address/address-select.ts
  src/main/steps/common/components/address-select.test.ts
  src/main/steps/common/components/address-select.ts
  src/main/steps/common/dashboard-page.njk
  src/main/steps/common/summary/utils.ts
  src/main/steps/common/support-you-need-during-case/summary/utils.ts
  src/main/steps/common/tasklist/template.njk
  src/main/steps/common/template.njk
  src/main/steps/common/yourhearings/hearings/content.ts
  src/main/steps/index.ts
  src/main/steps/respondent/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
  src/main/steps/respondent/respondentcaseSequence.test.ts
  src/main/steps/respondent/respondentcaseSequence.ts
  src/main/steps/respondent/task-list/content.test.ts
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/tasklistresponse/responseCaseSequence.test.ts
  src/main/steps/tasklistresponse/responseCaseSequence.ts
  src/main/steps/tasklistresponse/start/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-757

#475 Prl 1882 1883 citizen tests
  Jenkinsfile_nightly
  codecept.conf.js
  jest.pact.config.js
  package.json
  pact/pacts/prl-citizen-frontend-ccddatastoreapi_cases.json
  pact/pacts/prl-citizen-frontend-idamapi_oidc.json
  pact/pacts/prl-citizen-frontend-s2s_auth.json
  src/main/modules/oidc/index.ts
  src/main/steps/applicant/confirm-contact-details/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/util/safetyConcerns.util.test.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/util/safetyConcerns.util.ts
  src/main/steps/urls.ts
  src/test/a11y/a11y.ts
  src/test/end-to-end/actors/base.js
  src/test/end-to-end/actors/main.js
  src/test/end-to-end/actors/tabs.js
  src/test/end-to-end/helpers/browser_helper.js
  src/test/end-to-end/helpers/dump_browser_logs_helper.js
  src/test/end-to-end/helpers/event_listener.js
  src/test/end-to-end/helpers/hooks_helper.js
  src/test/end-to-end/helpers/stepListener.js
  src/test/end-to-end/hooks/aggregate-metrics.js
  src/test/pact/ccd-data-store-api.test.ts
  src/test/pact/idam-api.test.ts
  src/test/pact/postcode-lookup-api.test.ts
  src/test/pact/rpe-service-auth-provider.test.ts
  src/test/smoke/smoke.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, Release 2.3, rel:prl-citizen-frontend-pr-475, PRLFeatureTeam, Release 3.1

#764 Test cases coverage improvements
  sonar-project.properties
  src/main/app/case/CaseApi.test.ts
  src/main/app/document/DeleteDocumentRequest.test.ts
  src/main/app/document/DocumentDetail.test.ts
  src/main/app/document/GenerateAndUploadDocumentRequest.test.ts
  src/main/steps/applicant/confirm-contact-details/checkanswers/controller/ApplicantConfirmContactDetailsGetController.test.ts
  src/main/steps/applicant/confirm-contact-details/checkanswers/controller/ApplicantConfirmContactDetailsPostController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.test.ts
  src/main/steps/respondent/task-list/utils.test.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/mainUtil.test.ts
  src/main/steps/tasklistresponse/proceedings/mainUtils.test.ts
  src/main/steps/tasklistresponse/proceedings/proceedingUtils.test.ts
  src/main/steps/tasklistresponse/responseCaseSequence.test.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, Release 3.1, rel:prl-citizen-frontend-pr-764

#748 C100 rebuild base functional tests
  bin/run-crossbrowser-tests.sh
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/default.yaml
  config/development.yaml
  package-lock.json
  package.json
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/contents/ApplicantDetails-content.js
  src/test/end-to-end/contents/CheckYourAnswers-content.js
  src/test/end-to-end/contents/ChildrenDetails-content.js
  src/test/end-to-end/contents/ConsentOrder-content.js
  src/test/end-to-end/contents/HelpWithFees-content.js
  src/test/end-to-end/contents/InternationalElement-content.js
  src/test/end-to-end/contents/Miam-content.js
  src/test/end-to-end/contents/OtherPersonDetails-content.js
  src/test/end-to-end/contents/OtherProceedings-content.js
  src/test/end-to-end/contents/ReasonableAdjustments-content.js
  src/test/end-to-end/contents/RespondentDetails-content.js
  src/test/end-to-end/contents/SafetyConcerns-content.js
  src/test/end-to-end/contents/ScreeningQuestions-content.js
  src/test/end-to-end/contents/TypeOfOrder-content.js
  src/test/end-to-end/contents/UrgencyWithoutNotice-content.js
  src/test/end-to-end/crossbrowser/supportedBrowsers.js
  src/test/end-to-end/pages/C100-Rebuild/ApplicantDetails.js
  src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswers.js
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswersSimple.js
  src/test/end-to-end/pages/C100-Rebuild/ChildrenDetails.js
  src/test/end-to-end/pages/C100-Rebuild/CitizenLoginPage.js
  src/test/end-to-end/pages/C100-Rebuild/ConsentOrder.js
  src/test/end-to-end/pages/C100-Rebuild/CreateApplication.js
  src/test/end-to-end/pages/C100-Rebuild/GoToMiam.js
  src/test/end-to-end/pages/C100-Rebuild/HelpWithFees.js
  src/test/end-to-end/pages/C100-Rebuild/InternationElement.js
  src/test/end-to-end/pages/C100-Rebuild/OtherPersonDetails.js
  src/test/end-to-end/pages/C100-Rebuild/OtherProceedings.js
  src/test/end-to-end/pages/C100-Rebuild/ReasonableAdjustments.js
  src/test/end-to-end/pages/C100-Rebuild/RespondentDetails.js
  src/test/end-to-end/pages/C100-Rebuild/SafetyConcerns.js
  src/test/end-to-end/pages/C100-Rebuild/ScreeningQuestions.js
  src/test/end-to-end/pages/C100-Rebuild/TypeOfOrder.js
  src/test/end-to-end/pages/C100-Rebuild/UrgencyWithoutNotice.js
  src/test/end-to-end/steps_file.js
  src/test/end-to-end/tests/C100Rebuild-BaseFlow.js
  src/test/end-to-end/tests/C100Rebuild-MiamDocumentFlow.js
  src/test/end-to-end/tests/C100Rebuild-OtherProceedingsFlow.js
  src/test/end-to-end/tests/C100Rebuild-WithAgreement.js
  src/test/end-to-end/tests/C100Rebuild-WithUrgencyFlow.js
  src/test/end-to-end/tests/CurrentOrPreviousProceedings.js
  src/test/end-to-end/tests/InternationalElement.js
  src/test/end-to-end/tests/SupportYouNeedDuringYourCase.js
  src/test/end-to-end/tests/SupportYouNeedDuringYourCaseApplicant.js
  src/test/end-to-end/tests/SupportYouNeedDuringYourCaseRespondent.js
  src/test/resource/dummy.pdf
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-748

#772 Bump the version
  charts/prl-citizen-frontend/Chart.yaml
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-772

#774 Update CaseNameAndPostCode.js
  src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
  src/test/end-to-end/pages/C100-Rebuild/CreateApplication.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-774

#785 PVT-LAW - Enable Pact tests
  Jenkinsfile_CNP
  broker-compose.yaml
  package.json
  src/main/app/postcode/postcode-lookup-api.ts
  src/main/steps/applicant/confirm-contact-details/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/util/safetyConcerns.util.test.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/util/safetyConcerns.util.ts
  src/test/pact/postcode-lookup-api.test.ts
  src/test/pact/rpe-service-auth-provider.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-785

#789 using LoginPage.js for all tests
  package.json
  src/test/end-to-end/pages/C100-Rebuild/CitizenLoginPage.js
  src/test/end-to-end/pages/LoginPage.js
  src/test/end-to-end/steps_file.js
  src/test/end-to-end/tests/C100Rebuild-BaseFlow.js
  src/test/end-to-end/tests/C100Rebuild-MiamDocumentFlow.js
  src/test/end-to-end/tests/C100Rebuild-OtherProceedingsFlow.js
  src/test/end-to-end/tests/C100Rebuild-WithAgreement.js
  src/test/end-to-end/tests/C100Rebuild-WithUrgencyFlow.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-789
