Repository hmcts/prl-citizen-frontend, pull requests merged in 2023-07, with the labels that each got.

#1004 ft test issues
  src/test/end-to-end/pages/C100-Rebuild/ApplicantDetails.js
  src/test/end-to-end/pages/C100-Rebuild/ScreeningQuestions.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1004

#989 response submitted by other respondent
  sonar-project.properties
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/routes.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-989

#1003 PRL-3915: Get agreement for your request
  src/main/app/case/case.ts
  src/main/steps/application-within-proceedings/agreement-for-request/content.test.ts
  src/main/steps/application-within-proceedings/agreement-for-request/content.ts
  src/main/steps/application-within-proceedings/agreement-for-request/template.njk
  src/main/steps/application-within-proceedings/navigationController.test.ts
  src/main/steps/application-within-proceedings/navigationController.ts
  src/main/steps/applicationWithinProceedingsSequence.test.ts
  src/main/steps/applicationWithinProceedingsSequence.ts
  src/main/steps/urls.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1003

#1007 FT test issues
  src/test/end-to-end/pages/C100-Rebuild/ApplicantDetails.js
  src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswers.js
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswersSimple.js
  src/test/end-to-end/pages/C100-Rebuild/ChildrenDetails.js
  src/test/end-to-end/pages/C100-Rebuild/ConsentOrder.js
  src/test/end-to-end/pages/C100-Rebuild/CreateApplication.js
  src/test/end-to-end/pages/C100-Rebuild/GoToMiam.js
  src/test/end-to-end/pages/C100-Rebuild/HelpWithFees.js
  src/test/end-to-end/pages/C100-Rebuild/InternationElement.js
  src/test/end-to-end/pages/C100-Rebuild/MiniDashboard.js
  src/test/end-to-end/pages/C100-Rebuild/OtherPersonDetails.js
  src/test/end-to-end/pages/C100-Rebuild/OtherProceedings.js
  src/test/end-to-end/pages/C100-Rebuild/ReasonableAdjustments.js
  src/test/end-to-end/pages/C100-Rebuild/RespondentDetails.js
  src/test/end-to-end/pages/C100-Rebuild/SafetyConcerns.js
  src/test/end-to-end/pages/C100-Rebuild/ScreeningQuestions.js
  src/test/end-to-end/pages/C100-Rebuild/TypeOfOrder.js
  src/test/end-to-end/pages/C100-Rebuild/UrgencyWithoutNotice.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1007

#1012 C100 Respondent Event Workflow
  src/test/end-to-end/config.js
  src/test/end-to-end/pages/LoginPage.js
  src/test/end-to-end/pages/RespondentEvents.js
  src/test/end-to-end/steps_file.js
  src/test/end-to-end/tests/C100Respondent-Flow.js
  src/test/end-to-end/tests/C100RespondentAboutYou-Flow.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1012

#1006 PRL-3916: Inform the other parties
  src/main/app/case/case.ts
  src/main/steps/application-within-proceedings/inform-other-parties/content.test.ts
  src/main/steps/application-within-proceedings/inform-other-parties/content.ts
  src/main/steps/application-within-proceedings/inform-other-parties/template.njk
  src/main/steps/application-within-proceedings/list-of-applications/content.test.ts
  src/main/steps/application-within-proceedings/list-of-applications/content.ts
  src/main/steps/application-within-proceedings/navigationController.test.ts
  src/main/steps/application-within-proceedings/navigationController.ts
  src/main/steps/applicationWithinProceedingsSequence.test.ts
  src/main/steps/applicationWithinProceedingsSequence.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1006

#1011 FT tests
  src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswersSimple.js
  src/test/end-to-end/pages/C100-Rebuild/ChildrenDetails.js
  src/test/end-to-end/pages/C100-Rebuild/MiniDashboard.js
  src/test/end-to-end/pages/C100-Rebuild/OtherPersonDetails.js
  src/test/end-to-end/pages/C100-Rebuild/OtherProceedings.js
  src/test/end-to-end/pages/C100-Rebuild/ReasonableAdjustments.js
  src/test/end-to-end/pages/C100-Rebuild/RespondentDetails.js
  src/test/end-to-end/pages/C100-Rebuild/SafetyConcerns.js
  src/test/end-to-end/pages/C100-Rebuild/ScreeningQuestions.js
  src/test/end-to-end/pages/C100-Rebuild/TypeOfOrder.js
  src/test/end-to-end/pages/C100-Rebuild/UrgencyWithoutNotice.js
  src/test/end-to-end/steps_file.js
  src/test/end-to-end/tests/C100Rebuild-BaseFlow.js
  src/test/end-to-end/tests/C100Rebuild-MiamDocumentFlow.js
  src/test/end-to-end/tests/C100Rebuild-OtherProceedingsFlow.js
  src/test/end-to-end/tests/C100Rebuild-WithAgreement.js
  src/test/end-to-end/tests/C100Rebuild-WithUrgencyFlow.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1011

#1018 FT test fix
  src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
  src/test/end-to-end/pages/C100-Rebuild/MiniDashboard.js
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1018

#1024 PRL-4052: Submission confirmation screens
  src/main/steps/application-within-proceedings/application-submitted/content.test.ts
  src/main/steps/application-within-proceedings/application-submitted/content.ts
  src/main/steps/application-within-proceedings/application-submitted/template.njk
  src/main/steps/application-within-proceedings/pay-and-submit/content.test.ts
  src/main/steps/application-within-proceedings/pay-and-submit/content.ts
  src/main/steps/application-within-proceedings/pay-and-submit/template.njk
  src/main/steps/applicationWithinProceedingsSequence.test.ts
  src/main/steps/applicationWithinProceedingsSequence.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1024

#1029 Fix for C100 applicant journey
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/common/task-list/content.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-1029

#1022 fixed bugs for consent to application , documents , check answers of …
  src/main/app/case/definition.ts
  src/main/steps/applicant/contact-preferences/contact-email-success/content.test.ts
  src/main/steps/applicant/contact-preferences/contact-email/content.test.ts
  src/main/steps/applicant/contact-preferences/contact-post-success/content.test.ts
  src/main/steps/applicant/contact-preferences/contact-post/contest.test.ts
  src/main/steps/applicant/contact-preferences/contact-preferences/contest.test.ts
  src/main/steps/applicant/orders/template.njk
  src/main/steps/applicant/task-list/template.njk
  src/main/steps/applicant/upload-document/content.test.ts
  src/main/steps/applicant/upload-document/content.ts
  src/main/steps/applicant/witnessstatements/template.njk
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/common/alldocuments/template.njk
  src/main/steps/common/contact-preferences/contact-email-success/content.test.ts
  src/main/steps/common/contact-preferences/contact-email-success/content.ts
  src/main/steps/common/contact-preferences/contact-email/content.test.ts
  src/main/steps/common/contact-preferences/contact-email/content.ts
  src/main/steps/common/contact-preferences/contact-post-success/content.test.ts
  src/main/steps/common/contact-preferences/contact-post-success/content.ts
  src/main/steps/common/contact-preferences/contact-post/content.test.ts
  src/main/steps/common/contact-preferences/contact-post/content.ts
  src/main/steps/common/contact-preferences/contact-preferences/content.test.ts
  src/main/steps/common/contact-preferences/contact-preferences/content.ts
  src/main/steps/common/remove-legal-representative/start/template.njk
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/common/task-list/content.ts
  src/main/steps/common/tasklistalldocuments/template.njk
  src/main/steps/common/yourhearings/hearings/template.njk
  src/main/steps/prl-cases/pin-activation/case-activated/content.test.ts
  src/main/steps/prl-cases/pin-activation/case-activated/content.ts
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/respondent/upload-document/content.test.ts
  src/main/steps/respondent/upload-document/content.ts
  src/main/steps/tasklistresponse/consent-to-application/consent/content.test.ts
  src/main/steps/tasklistresponse/consent-to-application/consent/content.ts
  src/main/steps/tasklistresponse/start/content.test.ts
  src/main/steps/tasklistresponse/start/tasklist-items.ts
  src/main/steps/tasklistresponse/start/tasklist.test.ts
  src/main/steps/tasklistresponse/summary/content.ts
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-1022
