Repository hmcts/prl-citizen-frontend, pull requests merged in 2023-06, with the labels that each got.

#952 accessability test fixes
  charts/prl-citizen-frontend/values.preview.template.yaml
  src/main/steps/tasklistresponse/proceedings/ProceedingDetailsMapper.test.ts
  src/test/a11y/a11y.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-952

#955 flow fix
  config/development.yaml
  src/main/steps/applicant/confirm-contact-details/checkanswers/content.ts
  src/main/steps/applicant/task-list/utils.ts
  src/main/steps/common/confirm-contact-details/checkanswers/content.ts
  src/main/steps/respondent/confirm-contact-details/checkanswers/content.ts
  src/main/steps/respondent/task-list/tasklist.test.ts
  src/main/steps/respondent/task-list/tasklist.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-955

#954 Support you need during case flow corrections
  src/main/steps/applicant/support-you-need-during-case/court-hearing-comfort/content.ts
  src/main/steps/applicant/support-you-need-during-case/summary/content.test.ts
  src/main/steps/applicant/support-you-need-during-case/summary/content.ts
  src/main/steps/common/support-you-need-during-case/summary/handler.ts
  src/main/steps/respondent/support-you-need-during-case/summary/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/summary/content.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/summary/content.test.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/summary/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-954

#965 Ga dynatrace managing
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/default.yaml
  config/development.yaml
  src/main/assets/js/cookie.ts
  src/main/assets/js/data-layer.ts
  src/main/steps/common/common.content.ts
  src/main/steps/cookie-banner/template.njk
  src/test/pact/idam-api.test.ts
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-965

#966 welsh and bug fix
  src/main/steps/applicant/upload-document/upload-document-list-items.ts
  src/main/steps/applicant/upload-document/upload-your-documents/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/digitaldownloads/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/drug_alcohol_tests/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/lettersfromschool/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/medicalrecords/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/medicalreports/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/otherDocuments/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/otherpeoplewitnessstatement/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/paternity_test_reports/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/police_disclosures/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/positionstatements/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/previousorders/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/tenancy_and_mortgage_availability/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/witness_availability/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/yourwitnessstatements/content.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/common/app-survey/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/contact-us-c100.njk
  src/main/steps/common/keep-details-private/KeepDetailsPrivatePostController.ts
  src/main/steps/common/task-list/template.njk
  src/main/steps/respondent/task-list/content.test.ts
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/respondent/task-list/template.njk
  src/main/steps/respondent/upload-document/upload-your-documents/content.test.ts
  src/main/steps/respondent/upload-document/upload-your-documents/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/digitaldownloads/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/drug_alcohol_tests/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/lettersfromschool/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/medicalrecords/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/medicalreports/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/otherDocuments/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/otherpeoplewitnessstatement/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/paternity_test_reports/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/police_disclosures/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/positionstatements/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/previousorders/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/tenancy_and_mortgage_availability/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/witness_availability/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/yourwitnessstatements/content.ts
  src/main/steps/tasklistresponse/consent-to-application/consent/content.test.ts
  src/main/steps/tasklistresponse/consent-to-application/consent/content.ts
  src/main/steps/tasklistresponse/consent-to-application/summary/content.ts
  src/main/steps/tasklistresponse/legalrepresentation/start/content.test.ts
  src/main/steps/tasklistresponse/legalrepresentation/start/content.ts
  src/main/steps/tasklistresponse/proceedings/courtproceedings/content.test.ts
  src/main/steps/tasklistresponse/proceedings/courtproceedings/content.ts
  src/main/steps/tasklistresponse/proceedings/document-summary/content.test.ts
  src/main/steps/tasklistresponse/proceedings/document-summary/content.ts
  src/main/steps/tasklistresponse/proceedings/documentUpload/content.test.ts
  src/main/steps/tasklistresponse/proceedings/documentUpload/content.ts
  src/main/steps/tasklistresponse/proceedings/start/content.test.ts
  src/main/steps/tasklistresponse/proceedings/start/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-966

#968 feat(PRL-3770): AWP - foundation framework changes, add guidance page
  sonar-project.properties
  src/main/app/case/definition.ts
  src/main/app/form/Form.ts
  src/main/steps/application-within-proceedings/content.ts
  src/main/steps/application-within-proceedings/guidance/content.ts
  src/main/steps/application-within-proceedings/guidance/routeGuard.ts
  src/main/steps/application-within-proceedings/guidance/template.njk
  src/main/steps/application-within-proceedings/utils.ts
  src/main/steps/applicationWithinProceedingsSequence.ts
  src/main/steps/common/breadcrumb/content.ts
  src/main/steps/common/form/fields/button.njk
  src/main/steps/common/form/form.njk
  src/main/steps/constants.ts
  src/main/steps/index.ts
  src/main/steps/prl-cases/dashboard/DashboardGetController.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-968

#971 Help with fees and HWF reference screen
  src/main/app/case/case.ts
  src/main/steps/application-within-proceedings/help-with-fees/content.test.ts
  src/main/steps/application-within-proceedings/help-with-fees/content.ts
  src/main/steps/application-within-proceedings/help-with-fees/reference/content.test.ts
  src/main/steps/application-within-proceedings/help-with-fees/reference/content.ts
  src/main/steps/application-within-proceedings/help-with-fees/reference/template.njk
  src/main/steps/application-within-proceedings/help-with-fees/template.njk
  src/main/steps/applicationWithinProceedingsSequence.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-971

#972 added doc changes for welsh on respondent and applicant
  config/development.yaml
  src/main/app/case/definition.ts
  src/main/steps/applicant/support-you-need-during-case/SupportYouNeedDuringCaseController.ts
  src/main/steps/applicant/upload-document/content.test.ts
  src/main/steps/applicant/upload-document/upload-documents-list.ts
  src/main/steps/applicant/upload-document/upload-your-documents/content.test.ts
  src/main/steps/applicant/upload-document/upload-your-documents/content.ts
  src/main/steps/applicant/upload-document/upload-your-documents/template.njk
  src/main/steps/applicant/yourdocuments/alldocuments/digitaldownloads/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/drug_alcohol_tests/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/lettersfromschool/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/medicalrecords/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/otherDocuments/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/otherpeoplewitnessstatement/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/paternity_test_reports/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/police_disclosures/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/positionstatements/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/previousorders/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/witness_availability/content.ts
  src/main/steps/applicant/yourdocuments/alldocuments/yourwitnessstatements/content.ts
  src/main/steps/c100-rebuild/applicant/contact-preference/content.test.ts
  src/main/steps/c100-rebuild/applicant/contact-preference/content.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.ts
  src/main/steps/respondent/upload-document/content.test.ts
  src/main/steps/respondent/upload-document/upload-your-documents/content.test.ts
  src/main/steps/respondent/upload-document/upload-your-documents/content.ts
  src/main/steps/respondent/upload-document/upload-your-documents/template.njk
  src/main/steps/respondent/yourdocuments/alldocuments/digitaldownloads/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/drug_alcohol_tests/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/lettersfromschool/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/medicalrecords/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/medicalreports/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/otherDocuments/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/otherpeoplewitnessstatement/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/paternity_test_reports/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/police_disclosures/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/positionstatements/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/previousorders/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/tenancy_and_mortgage_availability/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/witness_availability/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/yourwitnessstatements/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-972

#986 Sonar fix master
  sonar-project.properties
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklist-items-all-documents.ts
  src/main/steps/c100-rebuild/check-your-answers/common/dateformatter.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/check-your-answers/util/otherProceeding.util.ts
  src/main/steps/common/dateformatter.test.ts
  src/main/steps/common/dateformatter.ts
  src/main/steps/common/summary-international/utils.test.ts
  src/main/steps/common/summary-international/utils.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/helpers/satetyConcernHelper.ts
  src/main/steps/tasklistresponse/proceedings/dateformatter.test.ts
  src/main/steps/tasklistresponse/proceedings/proceedingUtils.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-986

#988 fix applicant doc upload issue
  src/main/app/case/from-api-format.ts
  src/main/steps/agree-court-fee/content.test.ts
  src/main/steps/agree-court-fee/content.ts
  src/main/steps/complete-your-application-guidance/content.ts
  src/main/steps/complete-your-application-legal-representative/content.test.ts
  src/main/steps/complete-your-application-legal-representative/content.ts
  src/main/steps/legal-representative-proceedings/content.test.ts
  src/main/steps/legal-representative-proceedings/content.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-988

#973 PRL-3772 - Apply for HWF guidance
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/steps/application-within-proceedings/help-with-fees/apply-for-hwf/content.test.ts
  src/main/steps/application-within-proceedings/help-with-fees/apply-for-hwf/content.ts
  src/main/steps/application-within-proceedings/help-with-fees/apply-for-hwf/template.njk
  src/main/steps/applicationWithinProceedingsSequence.ts
  src/main/steps/urls.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-973

#975 PRL-3874 - Upload your application
  src/main/app/case/case.ts
  src/main/steps/application-within-proceedings/guidance/content.test.ts
  src/main/steps/application-within-proceedings/guidance/routeGuard.test.ts
  src/main/steps/application-within-proceedings/upload-your-application/content.test.ts
  src/main/steps/application-within-proceedings/upload-your-application/content.ts
  src/main/steps/application-within-proceedings/upload-your-application/template.njk
  src/main/steps/application-within-proceedings/utils.test.ts
  src/main/steps/applicationWithinProceedingsSequence.test.ts
  src/main/steps/applicationWithinProceedingsSequence.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-975

#981 PRL-3592 - Download application form
  src/main/steps/application-within-proceedings/download-form/content.test.ts
  src/main/steps/application-within-proceedings/download-form/content.ts
  src/main/steps/application-within-proceedings/download-form/template.njk
  src/main/steps/application-within-proceedings/utils.test.ts
  src/main/steps/application-within-proceedings/utils.ts
  src/main/steps/applicationWithinProceedingsSequence.test.ts
  src/main/steps/applicationWithinProceedingsSequence.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-981

#990 Fix Cross browser and Functional Nightly tests
  src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
  src/test/end-to-end/pages/C100-Rebuild/ConsentOrder.js
  src/test/end-to-end/pages/C100-Rebuild/CreateApplication.js
  src/test/end-to-end/pages/C100-Rebuild/MiniDashboard.js
  src/test/end-to-end/tests/C100Rebuild-MiamDocumentFlow.js
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-990

#998 fix:(testingsupport-ldflag): Fix testingsupport ld flag implementation
  src/main/modules/oidc/index.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-998

#999 C100 Citizen Functional Test Fixes Nightly
  src/test/end-to-end/pages/C100-Rebuild/ApplicantDetails.js
  src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswers.js
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswersSimple.js
  src/test/end-to-end/pages/C100-Rebuild/ChildrenDetails.js
  src/test/end-to-end/pages/C100-Rebuild/ConsentOrder.js
  src/test/end-to-end/pages/C100-Rebuild/CreateApplication.js
  src/test/end-to-end/pages/C100-Rebuild/GoToMiam.js
  src/test/end-to-end/pages/C100-Rebuild/HelpWithFees.js
  src/test/end-to-end/pages/C100-Rebuild/InternationElement.js
  src/test/end-to-end/pages/C100-Rebuild/MiniDashboard.js
  src/test/end-to-end/pages/C100-Rebuild/OtherPersonDetails.js
  src/test/end-to-end/pages/C100-Rebuild/OtherProceedings.js
  src/test/end-to-end/pages/C100-Rebuild/ReasonableAdjustments.js
  src/test/end-to-end/pages/C100-Rebuild/RespondentDetails.js
  src/test/end-to-end/pages/C100-Rebuild/SafetyConcerns.js
  src/test/end-to-end/pages/C100-Rebuild/ScreeningQuestions.js
  src/test/end-to-end/pages/C100-Rebuild/TypeOfOrder.js
  src/test/end-to-end/pages/C100-Rebuild/UrgencyWithoutNotice.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-999
