Repository hmcts/prl-citizen-frontend, pull requests merged in 2023-08, with the labels that each got.

#1020 removing hint text that defines the relationships 'Guardian' and 'Sp…
  src/main/steps/c100-rebuild/applicant/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/other-person-details/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/content.ts
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-1020

#1014 bug bash/bug fix1
  src/main/modules/oidc/index.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedback/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedback/content.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/postController.test.ts
  src/main/steps/c100-rebuild/confidentiality/feedback/content.test.ts
  src/main/steps/c100-rebuild/confidentiality/feedback/content.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.test.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/postController.test.ts
  src/main/steps/common/keep-details-private/private_details_confirmed/content.test.ts
  src/main/steps/common/keep-details-private/private_details_confirmed/content.ts
  src/main/steps/home/get.ts
  src/main/steps/index.test.ts
  src/main/steps/index.ts
  src/main/steps/prl-cases/citizenSequence.test.ts
  src/main/steps/prl-cases/citizenSequence.ts
  src/main/steps/respondent/keep-details-private/private_details_confirmed/content.test.ts
  src/main/steps/urls.ts
  src/test/a11y/a11y.ts
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-1014

#1039 master sonar fix
  src/main/steps/home/get.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1039

#1035 added a conditional routing for party types
  src/main/modules/oidc/index.ts
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-1035

#1044 Disable Pact test
  Jenkinsfile_CNP
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1044

#1042 Added screens and navigation for need permission on docs
  src/main/steps/applicant/applicantCaseSequence.test.ts
  src/main/steps/applicant/applicantCaseSequence.ts
  src/main/steps/applicant/upload-document/submit-extra-evidence/content.test.ts
  src/main/steps/applicant/upload-document/submit-extra-evidence/content.ts
  src/main/steps/applicant/upload-document/submit-extra-evidence/template.njk
  src/main/steps/respondent/respondentcaseSequence.test.ts
  src/main/steps/respondent/respondentcaseSequence.ts
  src/main/steps/respondent/upload-document/submit-extra-evidence/content.test.ts
  src/main/steps/respondent/upload-document/submit-extra-evidence/content.ts
  src/main/steps/respondent/upload-document/submit-extra-evidence/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1042

#1043 PRL-3964: AWP - Have supporting documents screen
  src/main/app/case/case.ts
  src/main/steps/application-within-proceedings/navigationController.test.ts
  src/main/steps/application-within-proceedings/navigationController.ts
  src/main/steps/application-within-proceedings/supporting-documents/content.test.ts
  src/main/steps/application-within-proceedings/supporting-documents/content.ts
  src/main/steps/application-within-proceedings/supporting-documents/template.njk
  src/main/steps/applicationWithinProceedingsSequence.test.ts
  src/main/steps/applicationWithinProceedingsSequence.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1043

#1049 Fix - Fixed redirecting to confirmation page on successful payment
  src/main/modules/oidc/index.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1049

#1050 upload success
  src/main/steps/applicant/applicantCaseSequence.test.ts
  src/main/steps/applicant/applicantCaseSequence.ts
  src/main/steps/applicant/upload-document/document-sharing-details/content.test.ts
  src/main/steps/applicant/upload-document/document-sharing-details/content.ts
  src/main/steps/applicant/upload-document/document-sharing-details/template.njk
  src/main/steps/applicant/upload-document/upload-documents-success/content.test.ts
  src/main/steps/applicant/upload-document/upload-documents-success/content.ts
  src/main/steps/applicant/upload-document/upload-documents-success/template.njk
  src/main/steps/respondent/respondentcaseSequence.ts
  src/main/steps/respondent/upload-document/document-sharing-details/content.test.ts
  src/main/steps/respondent/upload-document/document-sharing-details/content.ts
  src/main/steps/respondent/upload-document/document-sharing-details/template.njk
  src/main/steps/respondent/upload-document/upload-documents-success/content.test.ts
  src/main/steps/respondent/upload-document/upload-documents-success/content.ts
  src/main/steps/respondent/upload-document/upload-documents-success/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1050

#1052 Prl 4176
  config/development.yaml
  sonar-project.properties
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/case/formatter/uploaded-files.test.ts
  src/main/app/case/formatter/uploaded-files.ts
  src/main/app/controller/PostController.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/routes.ts
  src/main/steps/applicant/applicantCaseSequence.ts
  src/main/steps/applicant/upload-document/content.test.ts
  src/main/steps/applicant/upload-document/document-sharing-details/content.test.ts
  src/main/steps/applicant/upload-document/document-sharing-details/content.ts
  src/main/steps/applicant/upload-document/upload-documents-success/template.njk
  src/main/steps/applicant/upload-document/upload-your-documents/content.ts
  src/main/steps/applicant/upload-document/upload-your-documents/template.njk
  src/main/steps/applicant/yourdocuments/alldocuments/allDocumentsGetController.test.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/utils.test.ts
  src/main/steps/common/task-list/utils.test.ts
  src/main/steps/common/task-list/utils.ts
  src/main/steps/common/upload-document/DocumentUploadPostController.test.ts
  src/main/steps/common/upload-document/DocumentUploadPostController.ts
  src/main/steps/common/upload-document/util.ts
  src/main/steps/respondent/respondentcaseSequence.ts
  src/main/steps/respondent/upload-document/content.test.ts
  src/main/steps/respondent/upload-document/document-sharing-details/content.test.ts
  src/main/steps/respondent/upload-document/document-sharing-details/content.ts
  src/main/steps/respondent/upload-document/upload-documents-success/template.njk
  src/main/steps/respondent/upload-document/upload-your-documents/content.ts
  src/main/steps/respondent/upload-document/upload-your-documents/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1052

#1026 PRL-4053: Urgent request screen
  src/main/app/case/case.ts
  src/main/steps/application-within-proceedings/error/summary.njk
  src/main/steps/application-within-proceedings/navigationController.test.ts
  src/main/steps/application-within-proceedings/navigationController.ts
  src/main/steps/application-within-proceedings/urgent-request/content.test.ts
  src/main/steps/application-within-proceedings/urgent-request/content.ts
  src/main/steps/application-within-proceedings/urgent-request/template.njk
  src/main/steps/applicationWithinProceedingsSequence.test.ts
  src/main/steps/applicationWithinProceedingsSequence.ts
  src/main/steps/common/common.content.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1026

#980 feat:(prl-3887 : added intial setup for CosApiClient,GetController on…
  config/development.yaml
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/case/definition.ts
  src/main/app/case/formatter/uploaded-files.test.ts
  src/main/modules/properties-volume/index.ts
  src/main/routes.ts
  src/main/steps/applicant/applicantCaseSequence.test.ts
  src/main/steps/applicant/applicantCaseSequence.ts
  src/main/steps/applicant/task-list/content.test.ts
  src/main/steps/applicant/task-list/get.test.ts
  src/main/steps/applicant/task-list/get.ts
  src/main/steps/applicant/task-list/tasklist.test.ts
  src/main/steps/applicant/task-list/tasklist.ts
  src/main/steps/applicant/task-list/utils.test.ts
  src/main/steps/applicant/yourhearings/hearings/content.test.ts
  src/main/steps/applicant/yourhearings/hearings/content.ts
  src/main/steps/common/breadcrumb/content.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.test.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.ts
  src/main/steps/common/task-list/utils.test.ts
  src/main/steps/common/tasklist/template.njk
  src/main/steps/common/yourhearings/hearings/HearingGetController.test.ts
  src/main/steps/common/yourhearings/hearings/HearingsGetController.ts
  src/main/steps/common/yourhearings/hearings/content.test.ts
  src/main/steps/common/yourhearings/hearings/content.ts
  src/main/steps/common/yourhearings/hearings/template.njk
  src/main/steps/respondent/respondentcaseSequence.ts
  src/main/steps/respondent/task-list/get.test.ts
  src/main/steps/respondent/task-list/get.ts
  src/main/steps/respondent/task-list/tasklist.test.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/respondent/task-list/utils.test.ts
  src/main/steps/respondent/task-list/utils.ts
  src/main/steps/respondent/yourhearings/hearings/content.test.ts
  src/main/steps/respondent/yourhearings/hearings/content.ts
Labels: ns:private-law, prd:prl, keep-helm, rel:prl-citizen-frontend-pr-980

#1023 feat(PRL-3914): Add cancel/delay case hearing selection page
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/form/validation.ts
  src/main/steps/application-within-proceedings/navigationController.test.ts
  src/main/steps/application-within-proceedings/navigationController.ts
  src/main/steps/application-within-proceedings/select-hearing/content.test.ts
  src/main/steps/application-within-proceedings/select-hearing/content.ts
  src/main/steps/application-within-proceedings/select-hearing/postController.test.ts
  src/main/steps/application-within-proceedings/select-hearing/postController.ts
  src/main/steps/application-within-proceedings/select-hearing/template.njk
  src/main/steps/applicationWithinProceedingsSequence.test.ts
  src/main/steps/applicationWithinProceedingsSequence.ts
  src/main/steps/common/task-list/components/tasklist/utils.test.ts
  src/main/steps/common/yourhearings/hearings/HearingsGetController.ts
  src/main/steps/respondent/task-list/get.ts
  src/main/steps/respondent/task-list/utils.test.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1023

#1054 secret changes from demo to aat
  config/development.yaml
  src/main/modules/properties-volume/index.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1054

#1055 Fix
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/steps/applicant/upload-document/upload-documents-success/template.njk
  src/main/steps/applicant/upload-document/upload-your-documents/content.ts
  src/main/steps/applicant/upload-document/upload-your-documents/template.njk
  src/main/steps/common/upload-document/DocumentUploadPostController.test.ts
  src/main/steps/common/upload-document/DocumentUploadPostController.ts
  src/main/steps/respondent/upload-document/upload-documents-success/template.njk
  src/main/steps/respondent/upload-document/upload-your-documents/content.test.ts
  src/main/steps/respondent/upload-document/upload-your-documents/content.ts
  src/main/steps/respondent/upload-document/upload-your-documents/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1055

#1059 PRL-4215: Align AWP error messages with design
  src/main/steps/application-within-proceedings/agreement-for-request/content.test.ts
  src/main/steps/application-within-proceedings/agreement-for-request/content.ts
  src/main/steps/application-within-proceedings/agreement-for-request/template.njk
  src/main/steps/application-within-proceedings/document-upload/content.ts
  src/main/steps/application-within-proceedings/document-upload/template.njk
  src/main/steps/application-within-proceedings/error/summary.njk
  src/main/steps/application-within-proceedings/help-with-fees/reference/template.njk
  src/main/steps/application-within-proceedings/help-with-fees/template.njk
  src/main/steps/application-within-proceedings/inform-other-parties/template.njk
  src/main/steps/application-within-proceedings/select-hearing/content.test.ts
  src/main/steps/application-within-proceedings/select-hearing/content.ts
  src/main/steps/application-within-proceedings/select-hearing/template.njk
  src/main/steps/application-within-proceedings/supporting-document-upload/template.njk
  src/main/steps/application-within-proceedings/supporting-documents/template.njk
  src/main/steps/application-within-proceedings/upload-your-application/template.njk
  src/main/steps/common/common.content.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1059

#1046 Feature/prl 3922
  src/main/steps/application-within-proceedings/checkanswers/content.test.ts
  src/main/steps/application-within-proceedings/checkanswers/content.ts
  src/main/steps/application-within-proceedings/checkanswers/routeGuard.test.ts
  src/main/steps/application-within-proceedings/checkanswers/routeGuard.ts
  src/main/steps/application-within-proceedings/checkanswers/template.njk
  src/main/steps/application-within-proceedings/checkanswers/utils.test.ts
  src/main/steps/application-within-proceedings/checkanswers/utils.ts
  src/main/steps/application-within-proceedings/document-upload/postController.test.ts
  src/main/steps/application-within-proceedings/navigationController.test.ts
  src/main/steps/application-within-proceedings/navigationController.ts
  src/main/steps/applicationWithinProceedingsSequence.test.ts
  src/main/steps/applicationWithinProceedingsSequence.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1046

#1058 PRL-4233: Remove url query params
  src/main/app/case/definition.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/modules/oidc/index.ts
  src/main/steps/applicant/yourdocuments/alldocuments/allDocumentsGetController.test.ts
  src/main/steps/applicant/yourdocuments/alldocuments/allDocumentsGetController.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.test.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/utils.test.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/utils.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
  src/main/steps/constants.ts
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/respondent/task-list/tasklist.test.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/urls.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1058

#1061 update create payment
  config/development.yaml
  src/main/modules/payments/paymentApi.test.ts
  src/main/modules/payments/paymentApi.ts
  src/main/modules/payments/paymentController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1061
