Repository hmcts/prl-citizen-frontend, pull requests merged in 2023-09, with the labels that each got.

#1062 Fixed text for error messages
  src/main/app/form/validation.test.ts
  src/main/steps/application-within-proceedings/checkanswers/content.test.ts
  src/main/steps/application-within-proceedings/checkanswers/utils.test.ts
  src/main/steps/application-within-proceedings/error/summary.njk
  src/main/steps/application-within-proceedings/upload-your-application/content.test.ts
  src/main/steps/application-within-proceedings/upload-your-application/content.ts
  src/main/steps/applicationWithinProceedingsSequence.test.ts
  src/main/steps/common/common.content.ts
  src/main/steps/respondent/task-list/get.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1062

#1069 remove keep-helm
  .github/PULL_REQUEST_TEMPLATE.md
  Jenkinsfile_CNP
  README.md
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1069

#1068 Fixes for sonar issues
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/modules/payments/paymentApi.ts
  src/main/modules/payments/paymentController.ts
  src/main/steps/applicant/task-list/content.test.ts
  src/main/steps/applicant/task-list/content.ts
  src/main/steps/applicant/task-list/tasklist.test.ts
  src/main/steps/applicant/upload-document/content.ts
  src/main/steps/applicant/upload-document/routeGuard.test.ts
  src/main/steps/applicant/upload-document/routeGuard.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.test.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/common/utils.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/common/utils.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start-alternative/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start/content.ts
  src/main/steps/c100-rebuild/applicant/personal-details/content.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/child-details/child-matters/content.ts
  src/main/steps/c100-rebuild/child-details/other-children/personal-details/content.ts
  src/main/steps/c100-rebuild/child-details/personal-details/content.ts
  src/main/steps/c100-rebuild/other-person-details/personal-details/content.ts
  src/main/steps/c100-rebuild/people/AddPeoplePostContoller.ts
  src/main/steps/c100-rebuild/people/util.test.ts
  src/main/steps/c100-rebuild/people/util.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.ts
  src/main/steps/common/add-legal-representative/content.ts
  src/main/steps/common/task-list/components/tasklist/utils.test.ts
  src/main/steps/common/upload-document/util.ts
  src/main/steps/common/yourhearings/hearings/content.test.ts
  src/main/steps/common/yourhearings/hearings/content.ts
  src/main/steps/respondent/task-list/content.test.ts
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/respondent/task-list/tasklist.test.ts
  src/main/steps/respondent/task-list/utils.ts
  src/main/steps/respondent/upload-document/content.ts
  src/main/steps/respondent/upload-document/routeGuard.test.ts
  src/main/steps/respondent/upload-document/routeGuard.ts
  src/main/steps/respondent/upload-document/upload-your-documents/content.ts
  src/main/steps/tasklistresponse/proceedings/proceedingUtils.ts
  src/main/steps/tasklistresponse/start/content.test.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1068

#1073 Renovate Inclusion
  .github/renovate.json
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1073

#1041 Reduce time for Functional tests in PRs
  src/test/end-to-end/contents/CheckYourAnswers-content.js
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswers.js
  src/test/end-to-end/pages/C100-Rebuild/HelpWithFees.js
  src/test/end-to-end/pages/C100-Rebuild/ReasonableAdjustments.js
  src/test/end-to-end/steps_file.js
  src/test/end-to-end/tests/C100Flow-Master.js
  src/test/end-to-end/tests/C100Rebuild-BaseFlow.js
  src/test/end-to-end/tests/C100Rebuild-MiamDocumentFlow.js
  src/test/end-to-end/tests/C100Rebuild-OtherProceedingsFlow.js
  src/test/end-to-end/tests/C100Rebuild-WithAgreement.js
  src/test/end-to-end/tests/C100Rebuild-WithUrgencyFlow.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1041
