Repository hmcts/prl-citizen-frontend, pull requests merged in 2023-10, with the labels that each got.

#1118 E2E FL401 Respondent Flow
  src/test/end-to-end/pages/FL-401Applicant/ApplicantAboutYouFL401.js
  src/test/end-to-end/tests/FL401ApplicantAboutYou-Flow.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1118

#1108 Refactor tasklist
  src/main/routes.ts
  src/main/steps/applicant/support-you-need-during-case/SupportYouNeedDuringCaseController.test.ts
  src/main/steps/applicant/support-you-need-during-case/SupportYouNeedDuringCaseController.ts
  src/main/steps/applicant/task-list/content.test.ts
  src/main/steps/applicant/task-list/content.ts
  src/main/steps/applicant/task-list/get.test.ts
  src/main/steps/applicant/task-list/get.ts
  src/main/steps/applicant/task-list/index.ts
  src/main/steps/applicant/task-list/section-titles.ts
  src/main/steps/applicant/task-list/tasklist-items.ts
  src/main/steps/applicant/task-list/tasklist.test.ts
  src/main/steps/applicant/task-list/tasklist.ts
  src/main/steps/applicant/task-list/template.njk
  src/main/steps/applicant/task-list/utils.test.ts
  src/main/steps/applicant/task-list/utils.ts
  src/main/steps/common/add-legal-representative/content.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.ts
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  src/main/steps/common/task-list/components/progress-bar/utils.test.ts
  src/main/steps/common/task-list/components/progress-bar/utils.ts
  src/main/steps/common/task-list/components/side-links/content.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.ts
  src/main/steps/common/task-list/components/tasklist/config/da_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/index.ts
  src/main/steps/common/task-list/components/tasklist/content.ts
  src/main/steps/common/task-list/components/tasklist/index.ts
  src/main/steps/common/task-list/components/tasklist/tasklist.macro.njk
  src/main/steps/common/task-list/components/tasklist/utils.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/common/task-list/content.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.test.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.ts
  src/main/steps/common/task-list/template.njk
  src/main/steps/common/task-list/utils.test.ts
  src/main/steps/common/task-list/utils.ts
  src/main/steps/prl-cases/CaseActivationPostController.test.ts
  src/main/steps/prl-cases/CaseActivationPostController.ts
  src/main/steps/prl-cases/dashboard/tabView.ts
  src/main/steps/respondent/respondentcaseSequence.test.ts
  src/main/steps/respondent/respondentcaseSequence.ts
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/respondent/task-list/tasklist.test.ts
  src/main/steps/respondent/task-list/tasklist.ts
  src/main/steps/respondent/task-list/utils.test.ts
  src/main/steps/respondent/task-list/utils.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1108

#1131 feat(PRL-4360): Add foundation framework for RA common component
  charts/prl-citizen-frontend/Chart.yaml
  charts/prl-citizen-frontend/values.preview.template.yaml
  charts/prl-citizen-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/development.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/utils/featureToggles.ts
  src/main/modules/oidc/index.ts
  src/main/modules/reasonable-adjustements/controller.test.ts
  src/main/modules/reasonable-adjustements/controller.ts
  src/main/modules/reasonable-adjustements/index.ts
  src/main/modules/reasonable-adjustements/interface.ts
  src/main/modules/reasonable-adjustements/route.ts
  src/main/modules/reasonable-adjustements/service.ts
  src/main/server.ts
  src/main/steps/common/reasonable-adjustements/confirmation/content.ts
  src/main/steps/common/reasonable-adjustements/confirmation/template.njk
  src/main/steps/common/reasonable-adjustements/guidance/content.ts
  src/main/steps/common/reasonable-adjustements/guidance/template.njk
  src/main/steps/common/reasonable-adjustements/utils.ts
  src/main/steps/common/task-list/components/tasklist/content.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1131

#1144 Prl 4369 upgrade to playwright
  .gitignore
  audit.json
  package.json
  src/test/end-to-end/actors/base.js
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/config.js
  src/test/end-to-end/helpers/browser_helper.js
  src/test/end-to-end/helpers/dump_browser_logs_helper.js
  src/test/end-to-end/helpers/generalHelper.js
  src/test/end-to-end/helpers/hooks_helper.js
  src/test/end-to-end/helpers/playwrightHelper.js
  src/test/end-to-end/output/C100_Rebuild_-_basic_journey_@nightly_@wip.failed.png
  src/test/end-to-end/pages/C100-Rebuild/ApplicantDetails.js
  src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswers.js
  src/test/end-to-end/pages/C100-Rebuild/ChildrenDetails.js
  src/test/end-to-end/pages/C100-Rebuild/CreateApplication.js
  src/test/end-to-end/pages/C100-Rebuild/GoToMiam.js
  src/test/end-to-end/pages/C100-Rebuild/HelpWithFees.js
  src/test/end-to-end/pages/C100-Rebuild/MiniDashboard.js
  src/test/end-to-end/pages/C100-Rebuild/OtherPersonDetails.js
  src/test/end-to-end/pages/C100-Rebuild/OtherProceedings.js
  src/test/end-to-end/pages/C100-Rebuild/ReasonableAdjustments.js
  src/test/end-to-end/pages/C100-Rebuild/RespondentDetails.js
  src/test/end-to-end/pages/C100-Rebuild/SafetyConcerns.js
  src/test/end-to-end/pages/C100-Rebuild/ScreeningQuestions.js
  src/test/end-to-end/pages/C100-Rebuild/TypeOfOrder.js
  src/test/end-to-end/pages/C100-Rebuild/UrgencyWithoutNotice.js
  src/test/end-to-end/pages/LoginPage.js
  src/test/end-to-end/pages/RespondentEvents.js
  src/test/end-to-end/tests/C100Flow-Master.js
  src/test/end-to-end/tests/C100Rebuild-BaseFlow.js
  src/test/end-to-end/tests/C100Rebuild-MiamDocumentFlow.js
  src/test/end-to-end/tests/C100Rebuild-OtherProceedingsFlow.js
  src/test/end-to-end/tests/C100Rebuild-WithAgreement.js
  src/test/end-to-end/tests/C100Rebuild-WithUrgencyFlow.js
  src/test/end-to-end/tests/C100Respondent-Flow.js
  src/test/end-to-end/tests/C100RespondentAboutYou-Flow.js
  src/test/end-to-end/tests/CurrentOrPreviousProceedings.js
  src/test/end-to-end/tests/FL401ApplicantAboutYou-Flow.js
  src/test/end-to-end/tests/InternationalElement.js
  src/test/end-to-end/tests/SupportYouNeedDuringYourCase.js
  src/test/end-to-end/tests/SupportYouNeedDuringYourCaseApplicant.js
  src/test/end-to-end/tests/SupportYouNeedDuringYourCaseRespondent.js
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1144

#1146 suppress security warning
  audit.json
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1146

#1155 Add smoke test coverage
  audit.json
  package.json
  src/test/end-to-end/codecept.smoke.conf.js
  src/test/end-to-end/tests/C100Flow-Master.js
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1155

#1168 Upgrade helm chart for nodejs
  charts/prl-citizen-frontend/Chart.yaml
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswers.js
  src/test/end-to-end/pages/C100-Rebuild/HelpWithFees.js
  src/test/end-to-end/pages/LoginPage.js
  src/test/end-to-end/tests/C100Flow-Master.js
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1168
