Repository hmcts/prl-citizen-frontend, pull requests merged in 2023-02, with the labels that each got.

#786 added the private law in title for upload , view all docs
  src/main/steps/common/page.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-786

#783 welsh translations changes as per 3 sheets
  src/main/steps/c100-rebuild/applicant/add-applicants/content.test.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/content.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-manual.test.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-manual.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedback/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedback/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedbackno/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedbackno/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start-alternative/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start-alternative/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start/content.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/child-details/add-children/content.test.ts
  src/main/steps/c100-rebuild/child-details/add-children/content.ts
  src/main/steps/c100-rebuild/child-details/other-children/names/content.test.ts
  src/main/steps/c100-rebuild/child-details/other-children/names/content.ts
  src/main/steps/c100-rebuild/confidentiality/details-know/content.test.ts
  src/main/steps/c100-rebuild/confidentiality/details-know/content.ts
  src/main/steps/c100-rebuild/confidentiality/feedback/content.test.ts
  src/main/steps/c100-rebuild/confidentiality/feedback/content.ts
  src/main/steps/c100-rebuild/confidentiality/feedbackno/content.test.ts
  src/main/steps/c100-rebuild/confidentiality/feedbackno/content.ts
  src/main/steps/c100-rebuild/confidentiality/start-alternative/content.test.ts
  src/main/steps/c100-rebuild/confidentiality/start-alternative/content.ts
  src/main/steps/c100-rebuild/confidentiality/start/content.test.ts
  src/main/steps/c100-rebuild/confidentiality/start/content.ts
  src/main/steps/c100-rebuild/confirmation-page/content.test.ts
  src/main/steps/c100-rebuild/confirmation-page/content.ts
  src/main/steps/c100-rebuild/consent-order/upload/content.ts
  src/main/steps/c100-rebuild/consent-order/upload/template.njk
  src/main/steps/c100-rebuild/hearing-urgency/urgent-details/content.test.ts
  src/main/steps/c100-rebuild/hearing-urgency/urgent-details/content.ts
  src/main/steps/c100-rebuild/help-with-fees/hwf-guidance/content.test.ts
  src/main/steps/c100-rebuild/help-with-fees/hwf-guidance/content.ts
  src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.ts
  src/main/steps/c100-rebuild/other-person-details/personal-details/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/personal-details/content.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/content.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/safety-concerns/applicant/report-abuse/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/applicant/report-abuse/content.ts
  src/main/steps/c100-rebuild/safety-concerns/child/report-abuse/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/child/report-abuse/content.ts
  src/main/steps/c100-rebuild/safety-concerns/concerns-for-safety/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/concerns-for-safety/content.ts
  src/main/steps/common/common.content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-783

#805 welsh translation QA fix
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/default.yaml
  config/development.yaml
  src/main/steps/c100-rebuild/applicant/address/common/address-manual.test.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-manual.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/template.njk
  src/main/steps/c100-rebuild/applicant/confidentiality/feedback/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedback/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/feedback/template.njk
  src/main/steps/c100-rebuild/applicant/confidentiality/start/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/start/template.njk
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/peopleHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/other-proceedings/current-previous-proceedings/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/current-previous-proceedings/content.ts
  src/main/steps/c100-rebuild/safety-concerns/applicant/concerns-about/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/applicant/concerns-about/content.ts
  src/main/steps/c100-rebuild/safety-concerns/child/template.njk
  src/main/steps/c100-rebuild/safety-concerns/concerns-for-safety/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/concerns-for-safety/content.ts
  src/main/steps/c100-rebuild/safety-concerns/orders-required/unsupervised/content.test.ts
  src/main/steps/c100-rebuild/safety-concerns/orders-required/unsupervised/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-805

#808 Added a new event for citizen case submit with hwf
  src/main/app/case/C100CaseApi.test.ts
  src/main/app/case/definition.ts
  src/main/modules/payments/paymentController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-808

#807 welsh Translation fixes
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-807

#794 prl 3044 citizen respondent dashboard welsh translations
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.ts
  src/main/steps/respondent/safety_concerns/domestic_abuse_risk/content.test.ts
  src/main/steps/respondent/safety_concerns/domestic_abuse_risk/content.ts
  src/main/steps/respondent/safety_concerns/domestic_abuse_risk_no/content.test.ts
  src/main/steps/respondent/safety_concerns/domestic_abuse_risk_no/content.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/child/concerns-about/content.test.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/child/concerns-about/content.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/child/content.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/child/report-abuse/content.test.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/child/report-abuse/content.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/respondent/concerns-about/content.test.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/respondent/concerns-about/content.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/respondent/content.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/respondent/report-abuse/content.test.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/respondent/report-abuse/content.ts
  src/main/steps/tasklistresponse/safety_concerns/domestic_abuse_risk/content.test.ts
  src/main/steps/tasklistresponse/safety_concerns/domestic_abuse_risk/content.ts
  src/main/steps/tasklistresponse/safety_concerns/domestic_abuse_risk_no/content.test.ts
  src/main/steps/tasklistresponse/safety_concerns/domestic_abuse_risk_no/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-794

#779 [DO NOT MERGE] C100-Rebuild Release 4.0 Changes - WIP
  charts/prl-citizen-frontend/Chart.yaml
  src/main/app/case/C100CaseApi.test.ts
  src/main/app/case/definition.ts
  src/main/modules/payments/paymentController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-779

#814 Nightly-fix: Remove unwanted Pact test from Nightly build
  Jenkinsfile_nightly
  charts/prl-citizen-frontend/Chart.yaml
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-814

#816 c100 - payment stub for case submission
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-816

#819 ITHC Vulnerabilities
  package-lock.json
  package.json
  src/test/reporters/accessibility-reporter/resources/angular.min.js
  test/java/gradle/wrapper/gradle-wrapper-7.2.jar
  test/java/gradle/wrapper/gradle-wrapper.jar
  test/java/gradle/wrapper/gradle-wrapper.properties
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-819

#821 PRL-3156 Issue fix - Fixed issue in the account dashboard for submitted cases
  src/main/steps/prl-cases/dashboard/tabView.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-821

#811 fixed issue 2,4,5
  src/main/steps/c100-rebuild/check-your-answers/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-811

#823 upgraded gradle to 8.0.1
  test/java/.gradle/6.5.1/executionHistory/executionHistory.bin
  test/java/.gradle/6.5.1/executionHistory/executionHistory.lock
  test/java/.gradle/6.5.1/fileChanges/last-build.bin
  test/java/.gradle/6.5.1/fileContent/fileContent.lock
  test/java/.gradle/6.5.1/fileHashes/fileHashes.lock
  test/java/.gradle/6.5.1/gc.properties
  test/java/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  test/java/.gradle/buildOutputCleanup/cache.properties
  test/java/.gradle/buildOutputCleanup/outputFiles.bin
  test/java/gradle/wrapper/gradle-wrapper-7.2.jar
  test/java/gradle/wrapper/gradle-wrapper.jar
  test/java/gradle/wrapper/gradle-wrapper.properties
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-823

#820 fix for issue 1,3,6,6.1,7
  src/main/app/form/validation.ts
  src/main/steps/c100-rebuild/applicant/personal-details/content.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/content.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-820

#824 upgraded gradle to 8.0.1
  test/java/build.gradle
Labels: ns:private-law, prd:prl, enable_fortify_scan, rel:prl-citizen-frontend-pr-824

#818 PRL-3178 - changing checkboxes to radios in applicant contact preferences
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/postController.ts
  src/main/steps/c100-rebuild/applicant/contact-preference/content.test.ts
  src/main/steps/c100-rebuild/applicant/contact-preference/content.ts
  src/main/steps/c100-rebuild/applicant/util.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-818
