Repository hmcts/prl-citizen-frontend, pull requests merged in 2023-04, with the labels that each got.

#877 mapper+test+get+post
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ContactDetailsMapper.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ContactDetailsMapper.ts
  src/main/steps/respondent/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-877

#881 Updating the service url to platform.hmcts.net from .internal
  Jenkinsfile_CNP
  config/default.yaml
  config/development.yaml
  src/test/end-to-end/config.js
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-881

#883 International factors data clean up
  src/main/app/controller/GetCaseController.ts
  src/main/steps/tasklistresponse/international-factors/InternationalFactorsGetController.ts
  src/main/steps/tasklistresponse/international-factors/InternationalFactorsMapper.test.ts
  src/main/steps/tasklistresponse/international-factors/InternationalFactorsMapper.ts
  src/main/steps/tasklistresponse/international-factors/InternationalFactorsPostController.test.ts
  src/main/steps/tasklistresponse/international-factors/InternationalFactorsPostController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-883

#888 Citizen refactor allegations of harm violence
  Jenkinsfile_CNP
  src/main/app/case/definition.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/SafetyConcernsMapper.test.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/SafetyConcernsMapper.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/SafetyConcernsPostController.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/mainUtil.test.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/mainUtil.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-888

#884 modified post and get methods for proceedings
  src/main/steps/tasklistresponse/proceedings/ProceedingDetailsMapper.test.ts
  src/main/steps/tasklistresponse/proceedings/ProceedingDetailsMapper.ts
  src/main/steps/tasklistresponse/proceedings/ProceedingGetController.ts
  src/main/steps/tasklistresponse/proceedings/ProceedingPostController.ts
  src/main/steps/tasklistresponse/proceedings/mainUtils.test.ts
  src/main/steps/tasklistresponse/proceedings/mainUtils.ts
  src/main/steps/tasklistresponse/proceedings/proceedingUtils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-884

#886 reverting url migration for citizen frontnd urls
  Jenkinsfile_CNP
  src/test/end-to-end/config.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-886

#875 Missing translation/prl 3059
  src/main/steps/applicant/upload-document/content.ts
  src/main/steps/applicant/upload-document/upload-document-list-items.ts
  src/main/steps/common/components/address-select.test.ts
  src/main/steps/common/components/address-select.ts
  src/main/steps/common/support-you-need-during-case/summary/utils.ts
  src/main/steps/common/tasklistalldocuments/template.njk
  src/main/steps/common/upload-document/template.njk
  src/main/steps/respondent/support-you-need-during-case/attending-the-court/content.ts
  src/main/steps/respondent/support-you-need-during-case/attending-the-court/template.njk
  src/main/steps/respondent/support-you-need-during-case/court-hearing-comfort/content.ts
  src/main/steps/respondent/support-you-need-during-case/language-requirements/content.ts
  src/main/steps/respondent/support-you-need-during-case/reasonable-adjustments/content.ts
  src/main/steps/respondent/support-you-need-during-case/special-arrangements/content.ts
  src/main/steps/respondent/support-you-need-during-case/summary/content.test.ts
  src/main/steps/respondent/support-you-need-during-case/summary/content.ts
  src/main/steps/respondent/task-list/content.ts
  src/main/steps/respondent/task-list/template.njk
  src/main/steps/respondent/upload-document/content.ts
  src/main/steps/respondent/upload-document/section-titles.ts
  src/main/steps/respondent/yourdocuments/alldocuments/alldocuments/content.test.ts
  src/main/steps/respondent/yourdocuments/alldocuments/alldocuments/content.ts
  src/main/steps/respondent/yourdocuments/alldocuments/alldocuments/section-titles-all-documents.ts
  src/main/steps/respondent/yourdocuments/alldocuments/medicalreports/content.test.ts
  src/main/steps/respondent/yourdocuments/alldocuments/medicalreports/content.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/court-hearing-comfort/content.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/reasonable-adjustments/content.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/special-arrangements/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-875

#887 cleaning up respondent consent to application data
  src/main/steps/respondent/consent-to-application/ConsentGetController.ts
  src/main/steps/respondent/consent-to-application/ConsentMapper.test.ts
  src/main/steps/respondent/consent-to-application/ConsentMapper.ts
  src/main/steps/respondent/consent-to-application/ConsentPostController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-887

#896 Nightly security build fix
  package.json
  security.sh
Labels: ns:private-law, prd:prl, enable_security_scan, enable_full_functional_tests, rel:prl-citizen-frontend-pr-896

#892 feat(PRl-3509): Refactor update case API data payload - safety concerns
  src/main/app/case/CosApiClient.ts
  src/main/app/case/definition.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/SafetyConcernsPostController.test.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/SafetyConcernsPostController.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-892

#903 added test cases for uncovered lines
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklist-items-all-documents.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.test.ts
  src/main/steps/applicant/yourdocuments/alldocuments/alldocuments/tasklistalldocuments.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-903

#901 Full Functional test fix
  src/test/end-to-end/pages/C100-Rebuild/ConsentOrder.js
  src/test/end-to-end/pages/C100-Rebuild/GoToMiam.js
  src/test/end-to-end/pages/C100-Rebuild/OtherProceedings.js
Labels: ns:private-law, prd:prl, enable_full_functional_tests, enable_cross_browser_tests, rel:prl-citizen-frontend-pr-901
