Repository hmcts/prl-citizen-frontend, pull requests merged in 2024-08, with the labels that each got.

#1620 SOS missing error
  src/main/modules/properties-volume/index.ts
  src/main/steps/common/statement-of-service/upload/postController.test.ts
  src/main/steps/common/statement-of-service/upload/postController.ts
  src/main/steps/common/statement-of-service/upload/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1620

#1619 PRL-6040
  src/main/steps/common/task-list/components/notification-banner/config/base.config.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/definitions.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1619

#1621 feat(PRL-6041, PRL-6045, PRL-6046, PRL-6040): Integrate DA notifications
  src/main/app/case/case.ts
  src/main/steps/common/statement-of-service/who-was-served/content.ts
  src/main/steps/common/task-list/components/notification-banner/config/base.config.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/definitions.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1621

#1480 feat(PRL-5898): Handle various AWP payment & application submission errors
  charts/prl-citizen-frontend/Chart.yaml
  src/main/steps/application-within-proceedings/checkanswers/content.test.ts
  src/main/steps/application-within-proceedings/checkanswers/content.ts
  src/main/steps/application-within-proceedings/checkanswers/postController.ts
  src/main/steps/application-within-proceedings/pay-and-submit/postController.ts
  src/main/steps/application-within-proceedings/utils.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1480

#1502 issue -sev low
  src/main/steps/common/summary/utils.ts
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/common/task-list/content.ts
  src/main/steps/tasklistresponse/summary/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1502

#1625 sonar fix and test cases
  src/main/steps/common/documents/download/DownloadDocumentController.test.ts
  src/main/steps/common/documents/download/DownloadDocumentController.ts
  src/main/steps/common/documents/view/utils.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/common/task-list/utils.test.ts
  src/main/steps/common/task-list/utils.ts
  src/main/steps/tasklistresponse/TasklistGetController.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1625

#1615 PRL-6098-link update
  src/main/steps/common/task-list/components/side-links/content.ts
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/common/task-list/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1615

#1626 PRL-6143-translation-notification
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/base.content.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1626

#1627 update sonar exclusiion
  sonar-project.properties
  src/main/steps/application-within-proceedings/checkanswers/postController.ts
  src/main/steps/application-within-proceedings/checkanswers/utils.ts
  src/main/steps/application-within-proceedings/document-upload/postController.ts
  src/main/steps/application-within-proceedings/pay-and-submit/postController.ts
  src/main/steps/application-within-proceedings/select-hearing/routeGuard.test.ts
  src/main/steps/application-within-proceedings/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1627

#1473 C7 template fix
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/controller/RespondentSubmitResponseController.ts
  src/main/steps/common/respondent-summary/template.njk
  src/main/steps/common/summary/utils.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.test.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.ts
  src/main/steps/common/task-list/components/tasklist/content.ts
  src/main/steps/common/task-list/components/tasklist/index.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/common/task-list/content.ts
  src/main/steps/tasklistresponse/summary-confirmation/content.test.ts
  src/main/steps/tasklistresponse/summary-confirmation/content.ts
  src/main/steps/tasklistresponse/summary-confirmation/template.njk
  src/main/steps/tasklistresponse/summary/content.ts
  src/main/steps/urls.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1473
