Repository hmcts/prl-citizen-frontend, pull requests merged in 2024-04, with the labels that each got.

#1384 Update README.md
  README.md
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1384

#1368 Fix for citizen concurrency
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/app/auth/user/oidc.ts
  src/main/app/case/C100CaseApi.test.ts
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/CosApiClient.integration.test.ts
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/case/definition.ts
  src/main/app/controller/GetCaseController.ts
  src/main/app/controller/PostController.ts
  src/main/app/controller/RespondentSubmitResponseController.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/app/testingsupport/TSDraftController.test.ts
  src/main/app/testingsupport/TSDraftController.ts
  src/main/modules/oidc/index.ts
  src/main/modules/payments/paymentController.test.ts
  src/main/modules/payments/paymentController.ts
  src/main/steps/applicant/support-you-need-during-case/SupportYouNeedDuringCaseController.ts
  src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/routeGuard.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.ts
  src/main/steps/common/contact-preferences/ContactPreferencesGetController.ts
  src/main/steps/common/contact-preferences/ContactPreferencesPostController.ts
  src/main/steps/common/controller/ViewAllDocumentsPostController.test.ts
  src/main/steps/common/controller/ViewAllDocumentsPostController.ts
  src/main/steps/common/keep-details-private/KeepDetailsPrivatePostController.ts
  src/main/steps/common/remove-legal-representative/RemoveLegalRepresentativePostController.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.ts
  src/main/steps/respondent/consent-to-application/ConsentPostController.ts
  src/main/steps/tasklistresponse/TasklistGetController.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/SafetyConcernsPostController.ts
  src/main/steps/tasklistresponse/international-factors/InternationalFactorsPostController.ts
  src/main/steps/tasklistresponse/legalrepresentation/start/LegalRepresentationPostController.ts
  src/main/steps/tasklistresponse/miam/MIAMPostController.ts
  src/main/steps/tasklistresponse/proceedings/ProceedingPostController.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1368

#1341 CAN 4 in english
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  src/main/steps/common/task-list/utils.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1341

#1366 PRL-5275: Suppress new document notification for CA cases
  src/main/app/case/definition.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/routes.ts
  src/main/steps/common/controller/ViewAllDocumentsPostController.test.ts
  src/main/steps/common/controller/ViewAllDocumentsPostController.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  src/main/steps/respondent/task-list/index.test.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1366

#1396 PRL-5432: Stop citizen respondent submitting response multiple times
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/case/definition.ts
  src/main/routes.ts
  src/main/steps/common/CaseDataController.test.ts
  src/main/steps/common/CaseDataController.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.ts
  src/main/steps/common/task-list/components/tasklist/index.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.test.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.ts
  src/main/steps/tasklistresponse/TasklistGetController.test.ts
  src/main/steps/tasklistresponse/TasklistGetController.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1396

#1352 PRL-5248: Add notifications for applicant after response is submitted
  src/main/steps/common/documents/definitions.ts
  src/main/steps/common/documents/view/application-pack-documents/content.test.ts
  src/main/steps/common/documents/view/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/index.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  src/main/steps/common/task-list/components/tasklist/index.test.ts
  src/main/steps/common/task-list/components/tasklist/index.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/common/task-list/utils.test.ts
  src/main/steps/common/task-list/utils.ts
Labels: enable_keep_helm

#1398 PRL-5178: Add notification for respondent post SOA
  charts/prl-citizen-frontend/values.preview.template.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.test.ts
  src/main/steps/common/documents/view/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  src/main/steps/common/task-list/utils.ts
  src/main/steps/tasklistresponse/utils.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1398

#1253 PRL-5139: Citizen Dashboard MVP
  src/main/steps/c100-rebuild/confirmation-page/content.test.ts
  src/main/steps/c100-rebuild/confirmation-page/content.ts
  src/main/steps/tasklistresponse/international-factors/summary/content.test.ts
  src/main/steps/tasklistresponse/international-factors/summary/content.ts
  src/main/steps/tasklistresponse/proceedings/summary/template.njk
  src/main/steps/tasklistresponse/summary/content.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1253

#1394 DO NOT MERGE - Citizen base branch
  src/main/app/case/definition.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1394
