Repository hmcts/prl-citizen-frontend, pull requests merged in 2024-11, with the labels that each got.

#1701 Disable tests and enable nightly pipeline
  Jenkinsfile_nightly
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1701

#1702 Prl 6576
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/modules/reasonable-adjustments/navigationController.ts
  src/main/steps/application-within-proceedings/checkanswers/postController.test.ts
  src/main/steps/application-within-proceedings/pay-and-submit/postController.test.ts
  src/main/steps/application-within-proceedings/utils.test.ts
  src/main/steps/application-within-proceedings/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1702

#1700 PRL-6483 - Review Kubernetes requests & limits for memory, cpu usage
  charts/prl-citizen-frontend/values.aat.template.yaml
  charts/prl-citizen-frontend/values.preview.template.yaml
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1700

#1705 PRL-6620: Fix submitting refuge without refuge document
  config/development.yaml
  src/main/app/case/case.ts
  src/main/steps/applicant/confirm-contact-details/checkanswers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.ts
  src/main/steps/c100-rebuild/check-your-answers/common/htmlSelectors.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/lib/lib.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ContactDetailsMapper.ts
  src/main/steps/common/confirm-contact-details/checkanswers/content.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/content.ts
  src/main/steps/common/confirm-contact-details/checkanswers/utils.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/utils.ts
  src/main/steps/common/contact-preference/review/ReviewContactPreferencePostController.test.ts
  src/main/steps/common/safety-concerns/review/content.test.ts
  src/main/steps/common/summary/utils.test.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/respondent/confirm-contact-details/checkanswers/content.test.ts
  src/main/steps/tasklistresponse/proceedings/mainUtils.test.ts
  src/main/steps/tasklistresponse/start/utils.ts
  src/main/steps/tasklistresponse/summary/content.test.ts
  src/main/steps/tasklistresponse/summary/content.ts
  src/main/steps/tasklistresponse/summary/handler.test.ts
  src/main/steps/tasklistresponse/summary/handler.ts
  src/main/steps/tasklistresponse/summary/routeGuard.test.ts
  src/main/steps/tasklistresponse/summary/routeGuard.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1705
