Repository hmcts/prl-citizen-frontend, pull requests merged in 2024-07, with the labels that each got.

#1505 PRL-5558: Fix welsh content
  charts/prl-citizen-frontend/values.preview.template.yaml
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/miam/no-access-to-mediator/content.test.ts
  src/main/steps/c100-rebuild/miam/no-access-to-mediator/content.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1505

#1507 Smoketest/CUIRA
  src/test/end-to-end/contents/Miam-content.js
  src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswers.js
  src/test/end-to-end/pages/C100-Rebuild/GoToMiam.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1507

#1506 PRL-6083: Fix contact preference submit button not disabling
  src/main/steps/common/contact-preference/review/content.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1506

#1509 PRL-6081 - Fixed generating document from free text input in citizen document upload
  src/main/app/case/CosApiClient.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1509

#1510 framework enhancements and prl-4422 and prl-4423
  .gitignore
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/codecept.smoke.conf.js
  src/test/end-to-end/config.js
  src/test/end-to-end/contents/ScreeningQuestions-content.js
  src/test/end-to-end/exuiSupport/helpers/testLogger.js
  src/test/end-to-end/exuiSupport/pages/Login.js
  src/test/end-to-end/exuiSupport/restApiData/CaseDataSetupV2.js
  src/test/end-to-end/exuiSupport/restApiData/DataSetupManager.js
  src/test/end-to-end/exuiSupport/restApiData/accessCodeExtractor/index.js
  src/test/end-to-end/exuiSupport/restApiData/dataSetupRequest.json
  src/test/end-to-end/exuiSupport/restApiData/dummy.pdf
  src/test/end-to-end/exuiSupport/restApiData/prlapps.js
  src/test/end-to-end/exuiSupport/steps_file.js
  src/test/end-to-end/pages/ActivateAccessCode.js
  src/test/end-to-end/pages/C100-Rebuild/C100CreateCaseE2E.js
  src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
  src/test/end-to-end/pages/C100-Rebuild/ScreeningQuestions.js
  src/test/end-to-end/pages/LoginPage.js
  src/test/end-to-end/pages/RespondentEvents.js
  src/test/end-to-end/pages/commonActions.js
  src/test/end-to-end/steps_file.js
  src/test/end-to-end/tests/C100CreateCaseE2EFlow_new.js
  src/test/end-to-end/tests/C100Flow-Master.js
  src/test/end-to-end/tests/C100Rebuild-BaseFlow.js
  src/test/end-to-end/tests/C100Remove-LegalRep.js
  src/test/end-to-end/tests/C100Respondent-Flow.js
  src/test/end-to-end/tests/C100RespondentAboutYou-Flow.js
  src/test/smoke/smoke.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1510

#1516 PRL-6071: Page title- Before you start your application - not appearing in Welsh
  src/main/steps/c100-rebuild/start/content.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1516

#1557 PRL-6119
  src/main/steps/common/documents/definitions.ts
  src/main/steps/common/documents/view/all-documents/content.ts
  src/main/steps/common/documents/view/application-pack-documents/content.ts
  src/main/steps/common/documents/view/config.ts
  src/main/steps/common/documents/view/content.test.ts
  src/main/steps/common/documents/view/doc/content.test.ts
  src/main/steps/common/documents/view/doc/content.ts
  src/main/steps/common/documents/view/doc/template.njk
  src/main/steps/common/documents/view/orders-from-the-court/content.test.ts
  src/main/steps/common/documents/view/orders-from-the-court/content.ts
  src/main/steps/common/documents/view/orders-from-the-court/template.njk
  src/main/steps/common/documents/view/template.njk
  src/main/steps/common/documents/view/utils.test.ts
  src/main/steps/common/documents/view/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1557

#1554 disabling nightly pipeline
  Jenkinsfile_nightly_disabled
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1554

#1499 dynamic button respondent summary confirmation screen
  src/main/steps/tasklistresponse/summary-confirmation/content.test.ts
  src/main/steps/tasklistresponse/summary-confirmation/content.ts
  src/main/steps/tasklistresponse/summary-confirmation/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1499

#1475 feat(PRL-5788): Integrate dashboard notification closure feature
  config/development.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/common/task-list/components/notification-banner/config/base.config.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/config/index.ts
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/common/task-list/components/notification-banner/content/base.content.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/definitions.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/index.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  src/main/steps/common/task-list/components/tasklist/index.ts
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/common/task-list/content.ts
  src/main/steps/common/task-list/definitions.ts
  src/main/steps/common/task-list/utils.test.ts
  src/main/steps/common/task-list/utils.ts
  src/main/steps/common/tasklist/template.njk
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1475

#1457 feat(PRL-5301): Add SOS upload feature
  .nvmrc
  config/development.yaml
  package.json
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant/applicantCaseSequence.test.ts
  src/main/steps/applicant/applicantCaseSequence.ts
  src/main/steps/common/documents/upload/upload-your-documents/postController.test.ts
  src/main/steps/common/documents/upload/upload-your-documents/postController.ts
  src/main/steps/common/documents/upload/upload-your-documents/routeGuard.test.ts
  src/main/steps/common/documents/upload/utils.test.ts
  src/main/steps/common/documents/upload/utils.ts
  src/main/steps/common/fileupload/macro-v1.njk
  src/main/steps/common/statement-of-service/review/content.test.ts
  src/main/steps/common/statement-of-service/review/content.ts
  src/main/steps/common/statement-of-service/review/postController.test.ts
  src/main/steps/common/statement-of-service/review/postController.ts
  src/main/steps/common/statement-of-service/review/template.njk
  src/main/steps/common/statement-of-service/success/content.test.ts
  src/main/steps/common/statement-of-service/success/content.ts
  src/main/steps/common/statement-of-service/success/template.njk
  src/main/steps/common/statement-of-service/upload/content.test.ts
  src/main/steps/common/statement-of-service/upload/content.ts
  src/main/steps/common/statement-of-service/upload/postController.test.ts
  src/main/steps/common/statement-of-service/upload/postController.ts
  src/main/steps/common/statement-of-service/upload/routeGuard.test.ts
  src/main/steps/common/statement-of-service/upload/routeGuard.ts
  src/main/steps/common/statement-of-service/upload/template.njk
  src/main/steps/common/statement-of-service/utils.test.ts
  src/main/steps/common/statement-of-service/utils.ts
  src/main/steps/common/statement-of-service/who-was-served/content.test.ts
  src/main/steps/common/statement-of-service/who-was-served/content.ts
  src/main/steps/common/statement-of-service/who-was-served/template.njk
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  src/main/steps/common/task-list/utils.ts
  src/main/steps/urls.ts
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1457

#1456 PRL-5752: Cafcass - Child lives with changes
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/child-details/live-with/content.ts
  src/main/steps/c100-rebuild/child-details/live-with/living-arrangements/content.test.ts
  src/main/steps/c100-rebuild/child-details/live-with/living-arrangements/content.ts
  src/main/steps/c100-rebuild/child-details/live-with/living-arrangements/postController.test.ts
  src/main/steps/c100-rebuild/child-details/live-with/living-arrangements/postController.ts
  src/main/steps/c100-rebuild/child-details/live-with/living-arrangements/template.njk
  src/main/steps/c100-rebuild/child-details/live-with/mainly-live-with/content.test.ts
  src/main/steps/c100-rebuild/child-details/live-with/mainly-live-with/content.ts
  src/main/steps/c100-rebuild/child-details/live-with/mainly-live-with/form.njk
  src/main/steps/c100-rebuild/child-details/live-with/mainly-live-with/postController.test.ts
  src/main/steps/c100-rebuild/child-details/live-with/mainly-live-with/postController.ts
  src/main/steps/c100-rebuild/child-details/live-with/mainly-live-with/template.njk
  src/main/steps/c100-rebuild/child-details/live-with/template.njk
  src/main/steps/c100-rebuild/child-details/live-with/utils.test.ts
  src/main/steps/c100-rebuild/child-details/live-with/utils.ts
  src/main/steps/c100-rebuild/child-details/navigationController.test.ts
  src/main/steps/c100-rebuild/child-details/navigationController.ts
  src/main/steps/c100-rebuild/other-person-details/navigationController.test.ts
  src/main/steps/c100-rebuild/other-person-details/navigationController.ts
  src/main/steps/c100-rebuild/people/util.ts
  src/main/steps/urls.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1456

#1487 PRL-5757 - Added notification banner to show message about applicant & idam emails
  src/main/steps/c100-rebuild/applicant/contact-detail/content.ts
  src/main/steps/c100-rebuild/applicant/contact-detail/template.njk
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1487

#1544 Feature/prl 6062 serve order
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1544

#1607 fix/redis: Add pingInterval to redis client
  src/main/modules/session/index.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1607

#1491 PRL-5955
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/steps/applicant/confirm-contact-details/address/lookup/content.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/base.config.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/base.content.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/definitions.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1491

#1492 crnf3 DA cases
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1492

#1574 PRL-6052
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/definitions.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1574

#1594 functional tests for prl-4424 4425 and 4426
  src/test/end-to-end/codecept.conf.js
  src/test/end-to-end/config.js
  src/test/end-to-end/exuiSupport/restApiData/CaseDataSetupV2.js
  src/test/end-to-end/exuiSupport/restApiData/DataSetupManager.js
  src/test/end-to-end/exuiSupport/restApiData/caseDataSetup_Fl401.js
  src/test/end-to-end/exuiSupport/restApiData/common.js
  src/test/end-to-end/exuiSupport/restApiData/dataSetupRequest.json
  src/test/end-to-end/exuiSupport/restApiData/fl401.js
  src/test/end-to-end/pages/ActivateAccessCode.js
  src/test/end-to-end/pages/ConsentToApplication.js
  src/test/end-to-end/pages/CurrentOrPreviousProceedings.js
  src/test/end-to-end/pages/FL-401Applicant/ApplicantAboutYouFL401.js
  src/test/end-to-end/pages/FL-401Applicant/ConfirmOrEditYourContactDetails.js
  src/test/end-to-end/pages/FL-401Applicant/KeepYourDetailsPrivate.js
  src/test/end-to-end/pages/FL-401Applicant/SupportYouNeedDuringYourCase.js
  src/test/end-to-end/pages/FL401ApplicantEvents.js
  src/test/end-to-end/pages/FL401RespondentEvents.js
  src/test/end-to-end/pages/InternationalElement.js
  src/test/end-to-end/pages/RespondentEvents.js
  src/test/end-to-end/pages/SupportYouNeedDuringYourCase-Applicant.js
  src/test/end-to-end/pages/SupportYouNeedDuringYourCase-RespondentCADA.js
  src/test/end-to-end/pages/uploadDocuments.js
  src/test/end-to-end/tests/C100Rebuild-BaseFlow.js
  src/test/end-to-end/tests/FL401ApplicantFlow.js
  src/test/end-to-end/tests/FL401RespondentFlow.js
  src/test/reporters/accessibility-reporter/customReporter.js
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1594

#1486 feat(PRL-5675): Integrate fact API for c100 child post code validation
  charts/prl-citizen-frontend/Chart.yaml
  charts/prl-citizen-frontend/values.preview.template.yaml
  charts/prl-citizen-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/development.yaml
  src/main/app/case/C100CaseApi.test.ts
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/CosApiClient.ts
  src/main/steps/c100-rebuild/childaddress/content.test.ts
  src/main/steps/c100-rebuild/childaddress/content.ts
  src/main/steps/c100-rebuild/childaddress/postController.test.ts
  src/main/steps/c100-rebuild/childaddress/postController.ts
  src/main/steps/c100-rebuild/start/postController.test.ts
  src/main/steps/c100-rebuild/start/postController.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1486

#1611 feat(PRL-5945): Integrate CAN8 notification
  config/development.yaml
  src/main/steps/common/task-list/components/notification-banner/config/base.config.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/definitions.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1611

#1614 feat(PRL-6138): Refactor integration on hearings API for Citizen dashboard
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/steps/common/CaseDataController.ts
  src/main/steps/common/documents/view/all-categories/content.test.ts
  src/main/steps/common/documents/view/utils.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.test.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.ts
  src/main/steps/tasklistresponse/TasklistGetController.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1614

#1572 welsh and new link
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant/applicantCaseSequence.test.ts
  src/main/steps/applicant/confirm-contact-details/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.ts
  src/main/steps/c100-rebuild/confirmation-page/content.ts
  src/main/steps/common/documents/download/DownloadDocumentController.ts
  src/main/steps/common/documents/download/utils.ts
  src/main/steps/common/documents/view/content.test.ts
  src/main/steps/common/documents/view/content.ts
  src/main/steps/common/documents/view/template.njk
  src/main/steps/common/safety-concerns/review/util/safetyConcerns.util.test.ts
  src/main/steps/common/safety-concerns/review/util/safetyConcerns.util.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_applicant.test.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.test.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.ts
  src/main/steps/common/task-list/components/tasklist/config/da_applicant.test.ts
  src/main/steps/common/task-list/components/tasklist/config/da_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/da_respondent.test.ts
  src/main/steps/common/task-list/components/tasklist/config/da_respondent.ts
  src/main/steps/common/task-list/components/tasklist/content.ts
  src/main/steps/common/task-list/components/tasklist/index.test.ts
  src/main/steps/common/task-list/components/tasklist/index.ts
  src/main/steps/common/task-list/components/tasklist/utils.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/common/task-list/utils.ts
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/willing-to-respond/content.ts
  src/main/steps/tasklistresponse/responseCaseSequence.test.ts
  src/main/steps/tasklistresponse/summary-confirmation/content.test.ts
  src/main/steps/tasklistresponse/summary-confirmation/content.ts
  src/main/steps/urls.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1572
