Repository hmcts/prl-citizen-frontend, pull requests merged in 2024-03, with the labels that each got.

#1249 prl-5119/citizen_journey_remove_case_name_screen
  config/development.yaml
  src/main/app/case/C100CaseApi.test.ts
  src/main/app/case/C100CaseApi.ts
  src/main/app/controller/GetCaseController.test.ts
  src/main/app/controller/GetCaseController.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/case-name/content.test.ts
  src/main/steps/c100-rebuild/case-name/content.ts
  src/main/steps/c100-rebuild/case-name/template.njk
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/urls.ts
  src/test/end-to-end/contents/CheckYourAnswers-content.js
  src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1249

#1256 "complete this section" for empty DOB and Address history (#1252)
  src/main/steps/applicant/confirm-contact-details/addressdetails/template.njk
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/respondent/confirm-contact-details/addressdetails/template.njk
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1256

#1288 PRL 5060: Add new payment error messages
  config/development.yaml
  src/main/app/case/definition.ts
  src/main/app/controller/AppRequest.ts
  src/main/app/controller/GetController.ts
  src/main/modules/payments/paymentController.test.ts
  src/main/modules/payments/paymentController.ts
  src/main/steps/accessibility-statement/get.test.ts
  src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/template.njk
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1288

#1277 feat(PRL-5181): Fix status tag for CA respondent Confirm Contact Details fields
  src/main/steps/common/task-list/components/tasklist/index.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/tasklistresponse/start/utils.test.ts
  src/main/steps/tasklistresponse/start/utils.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1277

#1338 PRL-5427: Add welsh translations to citizen document upload screens
  src/main/steps/applicant/upload-document/content.test.ts
  src/main/steps/applicant/upload-document/content.ts
  src/main/steps/applicant/upload-document/document-sharing-details/content.test.ts
  src/main/steps/applicant/upload-document/document-sharing-details/content.ts
  src/main/steps/applicant/upload-document/has-the-court-asked-for-this-documents/content.test.ts
  src/main/steps/applicant/upload-document/has-the-court-asked-for-this-documents/content.ts
  src/main/steps/applicant/upload-document/other-party-not-see-this-document/content.test.ts
  src/main/steps/applicant/upload-document/other-party-not-see-this-document/content.ts
  src/main/steps/applicant/upload-document/sharing-your-documents/content.test.ts
  src/main/steps/applicant/upload-document/sharing-your-documents/content.ts
  src/main/steps/applicant/upload-document/submit-extra-evidence/content.test.ts
  src/main/steps/applicant/upload-document/submit-extra-evidence/content.ts
  src/main/steps/applicant/upload-document/upload-document-list-items.ts
  src/main/steps/applicant/upload-document/upload-documents-success/content.test.ts
  src/main/steps/applicant/upload-document/upload-documents-success/content.ts
  src/main/steps/applicant/upload-document/upload-your-documents/content.test.ts
  src/main/steps/applicant/upload-document/upload-your-documents/content.ts
  src/main/steps/common/breadcrumb/content.ts
  src/main/steps/common/task-list/components/tasklist/content.ts
  src/main/steps/respondent/upload-document/content.test.ts
  src/main/steps/respondent/upload-document/content.ts
  src/main/steps/respondent/upload-document/document-sharing-details/content.test.ts
  src/main/steps/respondent/upload-document/document-sharing-details/content.ts
  src/main/steps/respondent/upload-document/has-the-court-asked-for-this-documents/content.test.ts
  src/main/steps/respondent/upload-document/has-the-court-asked-for-this-documents/content.ts
  src/main/steps/respondent/upload-document/other-party-not-see-this-document/content.test.ts
  src/main/steps/respondent/upload-document/other-party-not-see-this-document/content.ts
  src/main/steps/respondent/upload-document/sharing-your-documents/content.test.ts
  src/main/steps/respondent/upload-document/sharing-your-documents/content.ts
  src/main/steps/respondent/upload-document/submit-extra-evidence/content.test.ts
  src/main/steps/respondent/upload-document/submit-extra-evidence/content.ts
  src/main/steps/respondent/upload-document/upload-documents-success/content.test.ts
  src/main/steps/respondent/upload-document/upload-documents-success/content.ts
  src/main/steps/respondent/upload-document/upload-your-documents/content.test.ts
  src/main/steps/respondent/upload-document/upload-your-documents/content.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1338

#1329 feat(PRL-4186): Initial commit - Integrate document upload API changes
  config/development.yaml
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/document/DocumentManagementController.test.ts
  src/main/app/document/DocumentManagementController.ts
  src/main/steps/applicant/upload-document/content.test.ts
  src/main/steps/applicant/upload-document/content.ts
  src/main/steps/applicant/upload-document/document-sharing-details/content.test.ts
  src/main/steps/applicant/upload-document/document-sharing-details/content.ts
  src/main/steps/applicant/upload-document/has-the-court-asked-for-this-documents/content.test.ts
  src/main/steps/applicant/upload-document/has-the-court-asked-for-this-documents/content.ts
  src/main/steps/applicant/upload-document/other-party-not-see-this-document/content.test.ts
  src/main/steps/applicant/upload-document/other-party-not-see-this-document/content.ts
  src/main/steps/applicant/upload-document/sharing-your-documents/content.test.ts
  src/main/steps/applicant/upload-document/sharing-your-documents/content.ts
  src/main/steps/applicant/upload-document/submit-extra-evidence/content.test.ts
  src/main/steps/applicant/upload-document/submit-extra-evidence/content.ts
  src/main/steps/applicant/upload-document/upload-document-list-items.ts
  src/main/steps/applicant/upload-document/upload-documents-success/content.test.ts
  src/main/steps/applicant/upload-document/upload-documents-success/content.ts
  src/main/steps/applicant/upload-document/upload-your-documents/content.test.ts
  src/main/steps/applicant/upload-document/upload-your-documents/content.ts
  src/main/steps/applicant/upload-document/upload-your-documents/template.njk
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/content.ts
  src/main/steps/common/breadcrumb/content.ts
  src/main/steps/common/task-list/components/tasklist/content.ts
  src/main/steps/common/task-list/utils.test.ts
  src/main/steps/common/upload-document/DocumentUploadPostController.test.ts
  src/main/steps/common/upload-document/DocumentUploadPostController.ts
  src/main/steps/common/upload-document/util.test.ts
  src/main/steps/common/upload-document/util.ts
  src/main/steps/respondent/upload-document/content.test.ts
  src/main/steps/respondent/upload-document/content.ts
  src/main/steps/respondent/upload-document/document-sharing-details/content.test.ts
  src/main/steps/respondent/upload-document/document-sharing-details/content.ts
  src/main/steps/respondent/upload-document/has-the-court-asked-for-this-documents/content.test.ts
  src/main/steps/respondent/upload-document/has-the-court-asked-for-this-documents/content.ts
  src/main/steps/respondent/upload-document/other-party-not-see-this-document/content.test.ts
  src/main/steps/respondent/upload-document/other-party-not-see-this-document/content.ts
  src/main/steps/respondent/upload-document/sharing-your-documents/content.test.ts
  src/main/steps/respondent/upload-document/sharing-your-documents/content.ts
  src/main/steps/respondent/upload-document/submit-extra-evidence/content.test.ts
  src/main/steps/respondent/upload-document/submit-extra-evidence/content.ts
  src/main/steps/respondent/upload-document/upload-documents-success/content.test.ts
  src/main/steps/respondent/upload-document/upload-documents-success/content.ts
  src/main/steps/respondent/upload-document/upload-your-documents/content.test.ts
  src/main/steps/respondent/upload-document/upload-your-documents/content.ts
  src/main/steps/respondent/upload-document/upload-your-documents/template.njk
  src/main/steps/tasklistresponse/proceedings/documentUpload/content.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1329

#1298 PRL5230-hearing screen
  src/main/app/case/definition.ts
  src/main/steps/common/task-list/components/tasklist/index.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/common/yourhearings/hearings/content.test.ts
  src/main/steps/common/yourhearings/hearings/content.ts
  src/main/steps/common/yourhearings/hearings/template.njk
  src/main/steps/common/yourhearings/hearings/utils.ts
  src/main/steps/constants.ts
  src/main/steps/respondent/yourhearings/hearings/content.test.ts
  src/main/steps/respondent/yourhearings/hearings/content.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1298

#1363 sonar fix
  src/main/steps/common/add-legal-representative/content.ts
  src/main/steps/common/contact-preferences/contact-preferences/content.ts
  src/main/steps/respondent/support-you-need-during-case/summary/content.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/content.test.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/content.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/helpers/satetyConcernHelper.ts
  src/main/steps/tasklistresponse/support-you-need-during-case/summary/content.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1363

#1367 Fixes for critical and major sonar issues
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/definition.ts
  src/main/app/controller/GetCaseController.test.ts
  src/main/app/controller/GetController.test.ts
  src/main/app/utils/progress-bar-utils.test.ts
  src/main/app/utils/progress-bar-utils.ts
  src/main/steps/applicant/support-you-need-during-case/summary/content.ts
  src/main/steps/applicant/task-list/utils.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.ts
  src/main/steps/common/summary-international/utils.ts
  src/main/steps/common/summary/utils.test.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/progress-bar/config/ca_respondent.ts
  src/main/steps/common/task-list/components/progress-bar/index.test.ts
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/prl-cases/dashboard/utils.test.ts
  src/main/steps/tasklistresponse/legalrepresentation/start/LegalRepresentationGetController.test.ts
  src/main/steps/tasklistresponse/start/utils.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1367

#1339 PRL-5152-Add a note on mini dashbaord for LIP
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/content.test.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1339

#1319 PRL-5117-Database call before HWF
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/routeGuard.test.ts
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/routeGuard.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1319

#1322 PRL-5346: Notifications for applicant LIP personal service
  charts/prl-citizen-frontend/values.preview.template.yaml
  src/main/app/case/definition.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/index.ts
  src/main/steps/common/task-list/components/notification-banner/notification-banner.macro.njk
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/common/task-list/definitions.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1322

#1362 UI Updates to align with business needs
  src/main/steps/c100-rebuild/applicant/add-applicants/content.test.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/content.ts
  src/main/steps/c100-rebuild/applicant/personal-details/content.test.ts
  src/main/steps/c100-rebuild/applicant/personal-details/content.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/applicant/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/child-details/add-children/content.test.ts
  src/main/steps/c100-rebuild/child-details/add-children/content.ts
  src/main/steps/c100-rebuild/child-details/other-children/names/content.test.ts
  src/main/steps/c100-rebuild/child-details/other-children/names/content.ts
  src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.ts
  src/main/steps/c100-rebuild/other-person-details/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/relationship-to-child/content.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/content.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/personal-details/content.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/relationship-to-child/content.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1362

#1361 Update README.md
  README.md
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1361

#1371 Link citizen changes
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.ts
  src/main/app/testingsupport/TSDraftController.ts
  src/main/modules/oidc/index.ts
  src/main/steps/common/controller/ViewAllDocumentsPostController.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1371

#1379 suppress warnings
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1379
