Repository hmcts/prl-citizen-frontend, pull requests merged in 2024-05, with the labels that each got.

#1422 Refactor CA respondent tasklist response submission
  config/development.yaml
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/controller/RespondentSubmitResponseController.test.ts
  src/main/app/controller/RespondentSubmitResponseController.ts
  src/main/app/document/DocumentManagementClient.test.ts
  src/main/app/document/DocumentManagementClient.ts
  src/main/app/document/__mocks__/DocumentManagementClient.ts
  src/main/app/form/Form.ts
  src/main/modules/properties-volume/index.ts
  src/main/routes.ts
  src/main/steps/common/form/form.njk
  src/main/steps/common/respondent-task-list/template.njk
  src/main/steps/respondent/respondentcaseSequence.test.ts
  src/main/steps/respondent/respondentcaseSequence.ts
  src/main/steps/tasklistresponse/responseCaseSequence.test.ts
  src/main/steps/tasklistresponse/responseCaseSequence.ts
  src/main/steps/tasklistresponse/start/content.ts
  src/main/steps/tasklistresponse/start/template.njk
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1422

#1412 PRL-5516 Before got to Court screen changes
  src/main/steps/c100-rebuild/screening-questions/alternative-resolution/content.test.ts
  src/main/steps/c100-rebuild/screening-questions/alternative-resolution/content.ts
  src/main/steps/c100-rebuild/screening-questions/alternative-resolution/template.njk
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1412

#1418 feat(PRL-5658, PRL-5660, PRL-5662): Fix sonar issues and tech improvements
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.test.ts
  src/main/app/controller/PostController.ts
  src/main/modules/oidc/index.ts
  src/main/routes.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/common/CaseDataController.ts
  src/main/steps/common/controller/ViewAllDocumentsPostController.test.ts
  src/main/steps/common/controller/ViewAllDocumentsPostController.ts
  src/main/steps/common/documents/view/utils.test.ts
  src/main/steps/common/documents/view/utils.ts
  src/main/steps/common/reasonable-adjustments/intro/routeGuard.ts
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/index.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.ts
  src/main/steps/common/task-list/components/tasklist/index.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/common/task-list/utils.ts
  src/main/steps/prl-cases/CaseActivationPostController.test.ts
  src/main/steps/prl-cases/CaseActivationPostController.ts
  src/main/steps/prl-cases/citizenSequence.test.ts
  src/main/steps/prl-cases/citizenSequence.ts
  src/main/steps/prl-cases/pin-activation/case-activated/content.test.ts
  src/main/steps/prl-cases/pin-activation/case-activated/content.ts
  src/main/steps/prl-cases/pin-activation/case-activated/template.njk
  src/main/steps/prl-cases/pin-activation/enter-pin/content.test.ts
  src/main/steps/prl-cases/pin-activation/enter-pin/content.ts
  src/main/steps/prl-cases/pin-activation/enter-pin/postController.ts
  src/main/steps/respondent/respondentcaseSequence.test.ts
  src/main/steps/respondent/respondentcaseSequence.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/mainUtil.ts
  src/main/steps/tasklistresponse/legalrepresentation/solicitordirect/content.test.ts
  src/main/steps/tasklistresponse/legalrepresentation/solicitordirect/content.ts
  src/main/steps/tasklistresponse/legalrepresentation/solicitordirect/template.njk
  src/main/steps/tasklistresponse/legalrepresentation/solicitornotdirect/content.test.ts
  src/main/steps/tasklistresponse/legalrepresentation/solicitornotdirect/content.ts
  src/main/steps/tasklistresponse/legalrepresentation/solicitornotdirect/template.njk
  src/main/steps/tasklistresponse/legalrepresentation/start/LegalRepresentationGetController.test.ts
  src/main/steps/tasklistresponse/legalrepresentation/start/LegalRepresentationGetController.ts
  src/main/steps/tasklistresponse/legalrepresentation/start/LegalRepresentationPostController.ts
  src/main/steps/tasklistresponse/legalrepresentation/start/content.test.ts
  src/main/steps/tasklistresponse/legalrepresentation/start/content.ts
  src/main/steps/tasklistresponse/legalrepresentation/start/postController.test.ts
  src/main/steps/tasklistresponse/legalrepresentation/start/postController.ts
  src/main/steps/tasklistresponse/legalrepresentation/start/template.njk
  src/main/steps/tasklistresponse/start/content.ts
  src/main/steps/tasklistresponse/start/get.test.ts
  src/main/steps/tasklistresponse/start/get.ts
  src/main/steps/tasklistresponse/start/routeGuard.ts
  src/main/steps/tasklistresponse/start/utils.test.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1418

#1420 feat(PRL-5369, PRL-5659): Fix sonar issues
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/app/case/C100CaseApi.test.ts
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/CaseApi.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/GetCaseController.ts
  src/main/app/controller/PostController.ts
  src/main/app/testingsupport/TSDraftController.test.ts
  src/main/modules/payments/paymentApi.test.ts
  src/main/modules/payments/paymentApi.ts
  src/main/modules/payments/paymentController.ts
  src/main/modules/payments/paymentHelper.test.ts
  src/main/modules/payments/paymentHelper.ts
  src/main/steps/applicant/applicantCaseSequence.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/confirmation-page/content.ts
  src/main/steps/c100-rebuild/other-proceedings/documentUpload/postController.ts
  src/main/steps/c100-rebuild/uploadDocumentController.ts
  src/main/steps/common/CaseDataController.ts
  src/main/steps/common/add-legal-representative/content.ts
  src/main/steps/common/common.content.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ContactDetailsMapper.ts
  src/main/steps/common/contact-preference/navigationController.ts
  src/main/steps/common/documents/download/DownloadDocumentController.ts
  src/main/steps/common/documents/upload/utils.ts
  src/main/steps/common/summary-international/utils.test.ts
  src/main/steps/common/summary-international/utils.ts
  src/main/steps/common/summary/utils.test.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/common/url-parser.ts
  src/main/steps/tasklistresponse/proceedings/documentUpload/postController.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1420

#1406 PRL-5517: MIAM - Reaching an agreement without going to court content changes
  src/main/steps/c100-rebuild/screening-questions/alternative-routes/content.test.ts
  src/main/steps/c100-rebuild/screening-questions/alternative-routes/content.ts
  src/main/steps/c100-rebuild/screening-questions/alternative-routes/template.njk
  src/test/end-to-end/contents/ScreeningQuestions-content.js
  src/test/end-to-end/pages/C100-Rebuild/ScreeningQuestions.js
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1406

#1404 PRL-5546 - Miam attend Changes
  src/main/steps/c100-rebuild/miam/get-mediator/content.test.ts
  src/main/steps/c100-rebuild/miam/get-mediator/content.ts
  src/main/steps/c100-rebuild/miam/get-mediator/template.njk
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1404

#1407 PRL-5550
  src/main/app/case/case.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/miamHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/miamHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/util/miam.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/miam.util.ts
  src/main/steps/c100-rebuild/miam/child-protection/content.test.ts
  src/main/steps/c100-rebuild/miam/child-protection/content.ts
  src/main/steps/c100-rebuild/miam/child-protection/template.njk
  src/main/steps/c100-rebuild/miam/navigationController.test.ts
  src/main/steps/c100-rebuild/miam/no-need-with-reasons/content.ts
  src/test/unit/mocks/mocked-requests/miam-mock.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1407

#1405 Updated content for Miam - valid reasons for not attending miam
  config/development.yaml
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/miam/general-reasons/content.test.ts
  src/main/steps/c100-rebuild/miam/general-reasons/content.ts
  src/main/steps/c100-rebuild/miam/general-reasons/template.njk
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1405

#1425 PRL-5554, PRL-5549: MIAM - Domestic abuse new screens and content changes
  config/development.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/util/miam.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/miam.util.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/common.content.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/content.test.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/content.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/domestic-abuse/content.test.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/domestic-abuse/content.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/domestic-abuse/routeGuard.test.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/domestic-abuse/routeGuard.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/domestic-abuse/template.njk
  src/main/steps/c100-rebuild/miam/domestic-abuse/providing-evidence/content.test.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/providing-evidence/content.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/providing-evidence/template.njk
  src/main/steps/c100-rebuild/miam/domestic-abuse/template.njk
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/content.test.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/content.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/postController.test.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/postController.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/routeGuard.test.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/routeGuard.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/template.njk
  src/main/steps/c100-rebuild/miam/navigationController.test.ts
  src/main/steps/c100-rebuild/miam/navigationController.ts
  src/main/steps/c100-rebuild/miam/no-need-with-reasons/content.test.ts
  src/main/steps/c100-rebuild/miam/no-need-with-reasons/content.ts
  src/main/steps/c100-rebuild/miam/upload-evidence-of-attending-miam-or-ncdr/postController.ts
  src/main/steps/c100-rebuild/miam/upload-evidence-of-attending-miam-or-ncdr/routeGuard.ts
  src/main/steps/c100-rebuild/miam/util.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1425

#1439 PRL-5549: Hotfix to update providing-evidence screen
  src/main/steps/c100-rebuild/miam/domestic-abuse/providing-evidence/content.test.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/providing-evidence/content.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/providing-evidence/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1439

#1438 PRL-5557
  config/development.yaml
  src/main/app/case/definition.ts
  src/main/modules/properties-volume/index.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/miam/child-protection/content.ts
  src/main/steps/c100-rebuild/miam/miam-excemptions-summary/content.test.ts
  src/main/steps/c100-rebuild/miam/miam-excemptions-summary/content.ts
  src/main/steps/c100-rebuild/miam/miam-excemptions-summary/template.njk
  src/main/steps/c100-rebuild/miam/navigationController.test.ts
  src/main/steps/c100-rebuild/miam/navigationController.ts
  src/main/steps/c100-rebuild/miam/no-need-with-reasons/content.ts
  src/main/steps/c100-rebuild/miam/no-need-with-reasons/template.njk
  src/main/steps/c100-rebuild/pageStepConfig.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1438

#1436 feat(PRL-5605): Add FM5 doc upload feature
  src/main/steps/applicant/applicantCaseSequence.ts
  src/main/steps/common/documents/common/content.ts
  src/main/steps/common/documents/definitions.ts
  src/main/steps/common/documents/upload/config.test.ts
  src/main/steps/common/documents/upload/config.ts
  src/main/steps/common/documents/upload/content.test.ts
  src/main/steps/common/documents/upload/content.ts
  src/main/steps/common/documents/upload/document-sharing-details/content.test.ts
  src/main/steps/common/documents/upload/document-sharing-details/content.ts
  src/main/steps/common/documents/upload/document-sharing-details/template.njk
  src/main/steps/common/documents/upload/upload-documents-success/content.test.ts
  src/main/steps/common/documents/upload/upload-documents-success/content.ts
  src/main/steps/common/documents/upload/upload-documents-success/template.njk
  src/main/steps/common/documents/upload/upload-your-documents/content.test.ts
  src/main/steps/common/documents/upload/upload-your-documents/content.ts
  src/main/steps/common/documents/upload/upload-your-documents/postController.test.ts
  src/main/steps/common/documents/upload/upload-your-documents/postController.ts
  src/main/steps/common/documents/upload/upload-your-documents/template.njk
  src/main/steps/common/documents/upload/utils.test.ts
  src/main/steps/common/documents/upload/utils.ts
  test/java/.gradle/buildOutputCleanup/buildOutputCleanup.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1436

#1397 FPET-946 fixing CVE for citizen front end
  charts/prl-citizen-frontend/Chart.yaml
  charts/prl-citizen-frontend/values.preview.template.yaml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1397

#1442 fix/plaintext_credentials : removed plaintext
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  broker-compose.yaml
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1442

#1440 fix/health-check: Added health check code to dockerfile.
  Dockerfile
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1440

#1447 Duplication fix
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/check-your-answers/util/otherProceeding.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/otherProceeding.util.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/tasklistresponse/proceedings/mainUtils.ts
  src/main/steps/tasklistresponse/proceedings/proceedingUtils.test.ts
  src/main/steps/tasklistresponse/proceedings/proceedingUtils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1447

#1443 PCQ for main applicant CA during application submission
  charts/prl-citizen-frontend/Chart.yaml
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/default.yaml
  config/docker.yaml
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/case.ts
  src/main/modules/properties-volume/index.ts
  src/main/routes.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts
  src/main/steps/c100-rebuild/check-your-answers/PcqPostController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PcqPostController.ts
  src/main/steps/c100-rebuild/check-your-answers/PostControllerAfterPcq.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PostControllerAfterPcq.ts
  src/main/steps/common/equality/createToken.ts
  src/main/steps/common/equality/get.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1443

#1452 PRL-5771, PRL-5772: Add AWP welsh translations
  src/main/steps/application-within-proceedings/agreement-for-request/content.test.ts
  src/main/steps/application-within-proceedings/agreement-for-request/content.ts
  src/main/steps/application-within-proceedings/application-submitted/content.test.ts
  src/main/steps/application-within-proceedings/application-submitted/content.ts
  src/main/steps/application-within-proceedings/checkanswers/content.test.ts
  src/main/steps/application-within-proceedings/checkanswers/content.ts
  src/main/steps/application-within-proceedings/checkanswers/utils.ts
  src/main/steps/application-within-proceedings/content.test.ts
  src/main/steps/application-within-proceedings/content.ts
  src/main/steps/application-within-proceedings/document-upload/content.test.ts
  src/main/steps/application-within-proceedings/document-upload/content.ts
  src/main/steps/application-within-proceedings/download-form/content.test.ts
  src/main/steps/application-within-proceedings/download-form/content.ts
  src/main/steps/application-within-proceedings/guidance/content.test.ts
  src/main/steps/application-within-proceedings/guidance/content.ts
  src/main/steps/application-within-proceedings/help-with-fees/apply-for-hwf/content.test.ts
  src/main/steps/application-within-proceedings/help-with-fees/apply-for-hwf/content.ts
  src/main/steps/application-within-proceedings/help-with-fees/content.test.ts
  src/main/steps/application-within-proceedings/help-with-fees/content.ts
  src/main/steps/application-within-proceedings/help-with-fees/reference/content.test.ts
  src/main/steps/application-within-proceedings/help-with-fees/reference/content.ts
  src/main/steps/application-within-proceedings/inform-other-parties/content.test.ts
  src/main/steps/application-within-proceedings/inform-other-parties/content.ts
  src/main/steps/application-within-proceedings/pay-and-submit/content.test.ts
  src/main/steps/application-within-proceedings/pay-and-submit/content.ts
  src/main/steps/application-within-proceedings/select-hearing/content.test.ts
  src/main/steps/application-within-proceedings/select-hearing/content.ts
  src/main/steps/application-within-proceedings/supporting-document-upload/content.test.ts
  src/main/steps/application-within-proceedings/supporting-document-upload/content.ts
  src/main/steps/application-within-proceedings/supporting-documents/content.test.ts
  src/main/steps/application-within-proceedings/supporting-documents/content.ts
  src/main/steps/application-within-proceedings/upload-your-application/content.test.ts
  src/main/steps/application-within-proceedings/upload-your-application/content.ts
  src/main/steps/application-within-proceedings/urgent-request/content.test.ts
  src/main/steps/application-within-proceedings/urgent-request/content.ts
  src/main/steps/applicationWithinProceedingsSequence.test.ts
  src/main/steps/applicationWithinProceedingsSequence.ts
  src/main/steps/common/common.content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1452

#1444 Updated angular js to latest version
  package-lock.json
  package.json
  src/main/steps/applicant/confirm-contact-details/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/util/safetyConcerns.util.test.ts
  src/main/steps/tasklistresponse/allegations-of-harm-and-violence/check-your-answers/util/safetyConcerns.util.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1444

#1437 fix/codeowners file : added codeowners file
  CODEOWNERS
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1437

#1434 Respondent LiP responding to AoH
  charts/prl-citizen-frontend/values.preview.template.yaml
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/RespondentSubmitResponseController.test.ts
  src/main/app/controller/RespondentSubmitResponseController.ts
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/respondToAOHMapper.test.ts
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/respondToAOHMapper.ts
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/review/content.test.ts
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/review/content.ts
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/review/postController.test.ts
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/review/postController.ts
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/review/template.njk
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/willing-to-respond/content.test.ts
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/willing-to-respond/content.ts
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/willing-to-respond/routeGuard.test.ts
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/willing-to-respond/routeGuard.ts
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/willing-to-respond/template.njk
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/your-response/content.test.ts
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/your-response/content.ts
  src/main/steps/tasklistresponse/respond-to-allegations-of-harm/your-response/template.njk
  src/main/steps/tasklistresponse/responseCaseSequence.ts
  src/main/steps/tasklistresponse/start/content.test.ts
  src/main/steps/tasklistresponse/start/tasklist-items.ts
  src/main/steps/tasklistresponse/start/tasklist.test.ts
  src/main/steps/tasklistresponse/start/tasklist.ts
  src/main/steps/tasklistresponse/start/utils.ts
  src/main/steps/tasklistresponse/summary/content.test.ts
  src/main/steps/tasklistresponse/summary/content.ts
  src/main/steps/tasklistresponse/summary/postController.test.ts
  src/main/steps/tasklistresponse/summary/postController.ts
  src/main/steps/tasklistresponse/utils.ts
  src/main/steps/urls.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1434

#1431 C100 ITHC Vulnerabilities fix
  CODEOWNERS
  Dockerfile
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  broker-compose.yaml
  charts/prl-citizen-frontend/values.preview.template.yaml
  package-lock.json
  package.json
  src/main/steps/applicant/confirm-contact-details/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.ts
  src/main/steps/common/safety-concerns/review/util/safetyConcerns.util.test.ts
  src/main/steps/common/safety-concerns/review/util/safetyConcerns.util.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1431

#1450 PRL-5665
  Jenkinsfile_CNP
  charts/prl-citizen-frontend/values.preview.template.yaml
  charts/prl-citizen-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/development.yaml
  src/main/app/controller/AppRequest.ts
  src/main/app/utils/featureToggles.ts
  src/main/modules/oidc/index.ts
  src/main/server.ts
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/common/task-list/content.ts
  src/main/steps/common/task-list/template.njk
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1450

#1455 PRL-5781
  config/development.yaml
  src/main/app/case/definition.ts
  src/main/steps/common/documents/definitions.ts
  src/main/steps/common/documents/download/DownloadDocumentController.ts
  src/main/steps/tasklistresponse/summary-confirmation/content.test.ts
  src/main/steps/tasklistresponse/summary-confirmation/content.ts
  src/main/steps/tasklistresponse/summary-confirmation/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1455

#1408 feat(PRL-5515): Add c100 start screen designs with fee API
  src/main/app/fees/fees-lookup-api.test.ts
  src/main/app/fees/fees-lookup-api.ts
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/routeGuard.ts
  src/main/steps/c100-rebuild/start/content.test.ts
  src/main/steps/c100-rebuild/start/content.ts
  src/main/steps/c100-rebuild/start/routeGuard.ts
  src/main/steps/c100-rebuild/start/template.njk
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1408

#1465 sonar fix
  config/development.yaml
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/check-your-answers/util/otherProceeding.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.ts
  src/main/steps/common/safety-concerns/navigationController.ts
  src/main/steps/common/safety-concerns/review/common/htmlSelectors.test.ts
  src/main/steps/common/safety-concerns/review/common/htmlSelectors.ts
  src/main/steps/common/safety-concerns/review/helpers/satetyConcernHelper.ts
  src/main/steps/common/safety-concerns/review/mainUtil.ts
  src/main/steps/common/safety-concerns/review/safetyConcernMapper.ts
  src/main/steps/common/safety-concerns/yourself/report-abuse/postController.ts
  src/main/steps/common/summary/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1465
