Repository hmcts/prl-citizen-frontend, pull requests merged in 2024-01, with the labels that each got.

#1239 feat(PRL-4497): Integrate CUIRA for C100 application creation journey
  config/development.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/modules/reasonable-adjustments/controller.test.ts
  src/main/modules/reasonable-adjustments/controller.ts
  src/main/modules/reasonable-adjustments/definitions.ts
  src/main/modules/reasonable-adjustments/service.test.ts
  src/main/modules/reasonable-adjustments/service.ts
  src/main/modules/reasonable-adjustments/util.ts
  src/main/steps/c100-rebuild/PageStepConfigurator.test.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/content.test.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
  src/main/steps/c100-rebuild/applicant/util.test.ts
  src/main/steps/c100-rebuild/applicant/util.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/pageStepConfig.ts
  src/main/steps/c100-rebuild/safety-concerns/navigationController.test.ts
  src/main/steps/common/reasonable-adjustments/confirmation/content.ts
  src/main/steps/common/reasonable-adjustments/confirmation/postController.ts
  src/main/steps/common/reasonable-adjustments/confirmation/template.njk
  src/main/steps/urls.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1239

#1240 suppress warnings
  charts/prl-citizen-frontend/values.preview.template.yaml
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1240

#1241 feat(PRL-4892, PRL-4815): Integrate CUIRA for C100 application check your answers & co-applicants from case dashboard journey
  src/main/app/case/C100CaseApi.ts
  src/main/assets/js/go-back.ts
  src/main/modules/reasonable-adjustments/controller.ts
  src/main/modules/reasonable-adjustments/index.test.ts
  src/main/modules/reasonable-adjustments/index.ts
  src/main/modules/reasonable-adjustments/route.ts
  src/main/modules/reasonable-adjustments/util.ts
  src/main/server.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/check-your-answers/util/reasonableAdjustmentContent.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/reasonableAdjustmentContent.util.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/attending-court/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/attending-court/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/attending-court/template.njk
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/communication-help/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/communication-help/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/communication-help/template.njk
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/document-information/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/document-information/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/document-information/template.njk
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/feel-comfortable/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/feel-comfortable/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/feel-comfortable/template.njk
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/support-court/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/support-court/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/support-court/template.njk
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/template.njk
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/travelling-court/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/travelling-court/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/disability-requirements/travelling-court/template.njk
  src/main/steps/c100-rebuild/reasonable-adjustments/language-requirements/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/language-requirements/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/language-requirements/template.njk
  src/main/steps/c100-rebuild/reasonable-adjustments/special-arrangements/content.test.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/special-arrangements/content.ts
  src/main/steps/c100-rebuild/reasonable-adjustments/special-arrangements/template.njk
  src/main/steps/common/reasonable-adjustments/confirmation/postController.ts
  src/main/steps/common/reasonable-adjustments/guidance/content.ts
  src/main/steps/common/reasonable-adjustments/guidance/template.njk
  src/main/steps/common/task-list/components/tasklist/config/ca_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.ts
  src/main/steps/common/task-list/components/tasklist/utils.test.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1241
