Repository hmcts/prl-citizen-frontend, pull requests merged in 2024-06, with the labels that each got.

#1464 Review comments for PRL-5655
  src/main/app/case/case.ts
  src/main/modules/oidc/index.ts
  src/main/modules/pcq/controller.test.ts
  src/main/modules/pcq/controller.ts
  src/main/modules/pcq/definitions.ts
  src/main/modules/pcq/index.test.ts
  src/main/modules/pcq/index.ts
  src/main/modules/pcq/route.ts
  src/main/modules/pcq/service.test.ts
  src/main/modules/pcq/service.ts
  src/main/routes.ts
  src/main/server.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts
  src/main/steps/c100-rebuild/check-your-answers/PcqPostController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PcqPostController.ts
  src/main/steps/c100-rebuild/check-your-answers/PostControllerAfterPcq.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PostControllerAfterPcq.ts
  src/main/steps/common/equality/PcqNavigationController.test.ts
  src/main/steps/common/equality/PcqNavigationController.ts
  src/main/steps/tasklistresponse/summary/postController.test.ts
  src/main/steps/tasklistresponse/summary/postController.ts
  src/main/steps/tasklistresponse/summary/postControllerAfterPcq.test.ts
  src/main/steps/tasklistresponse/summary/postControllerAfterPcq.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1464

#1467 feat(PRL-5780): Add partyType to AWP module to enable access restriction
  src/main/app/case/CosApiClient.ts
  src/main/steps/application-within-proceedings/agreement-for-request/content.test.ts
  src/main/steps/application-within-proceedings/agreement-for-request/content.ts
  src/main/steps/application-within-proceedings/checkanswers/content.test.ts
  src/main/steps/application-within-proceedings/checkanswers/content.ts
  src/main/steps/application-within-proceedings/checkanswers/postController.test.ts
  src/main/steps/application-within-proceedings/checkanswers/postController.ts
  src/main/steps/application-within-proceedings/checkanswers/utils.test.ts
  src/main/steps/application-within-proceedings/checkanswers/utils.ts
  src/main/steps/application-within-proceedings/document-upload/content.test.ts
  src/main/steps/application-within-proceedings/document-upload/content.ts
  src/main/steps/application-within-proceedings/document-upload/postController.test.ts
  src/main/steps/application-within-proceedings/document-upload/postController.ts
  src/main/steps/application-within-proceedings/download-form/content.test.ts
  src/main/steps/application-within-proceedings/download-form/content.ts
  src/main/steps/application-within-proceedings/guidance/content.ts
  src/main/steps/application-within-proceedings/guidance/routeGuard.test.ts
  src/main/steps/application-within-proceedings/guidance/routeGuard.ts
  src/main/steps/application-within-proceedings/guidance/template.njk
  src/main/steps/application-within-proceedings/help-with-fees/apply-for-hwf/content.test.ts
  src/main/steps/application-within-proceedings/help-with-fees/apply-for-hwf/content.ts
  src/main/steps/application-within-proceedings/help-with-fees/content.test.ts
  src/main/steps/application-within-proceedings/help-with-fees/content.ts
  src/main/steps/application-within-proceedings/help-with-fees/reference/content.test.ts
  src/main/steps/application-within-proceedings/help-with-fees/reference/content.ts
  src/main/steps/application-within-proceedings/inform-other-parties/content.test.ts
  src/main/steps/application-within-proceedings/inform-other-parties/content.ts
  src/main/steps/application-within-proceedings/list-of-applications/config.test.ts
  src/main/steps/application-within-proceedings/list-of-applications/content.test.ts
  src/main/steps/application-within-proceedings/list-of-applications/content.ts
  src/main/steps/application-within-proceedings/list-of-applications/template.njk
  src/main/steps/application-within-proceedings/navigationController.test.ts
  src/main/steps/application-within-proceedings/navigationController.ts
  src/main/steps/application-within-proceedings/pay-and-submit/content.test.ts
  src/main/steps/application-within-proceedings/pay-and-submit/content.ts
  src/main/steps/application-within-proceedings/pay-and-submit/postController.test.ts
  src/main/steps/application-within-proceedings/pay-and-submit/postController.ts
  src/main/steps/application-within-proceedings/select-hearing/content.ts
  src/main/steps/application-within-proceedings/supporting-document-upload/content.test.ts
  src/main/steps/application-within-proceedings/supporting-document-upload/content.ts
  src/main/steps/application-within-proceedings/supporting-documents/content.test.ts
  src/main/steps/application-within-proceedings/supporting-documents/content.ts
  src/main/steps/application-within-proceedings/upload-your-application/content.test.ts
  src/main/steps/application-within-proceedings/upload-your-application/content.ts
  src/main/steps/application-within-proceedings/urgent-request/content.ts
  src/main/steps/application-within-proceedings/utils.test.ts
  src/main/steps/application-within-proceedings/utils.ts
  src/main/steps/applicationWithinProceedingsSequence.test.ts
  src/main/steps/applicationWithinProceedingsSequence.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.ts
  src/main/steps/common/task-list/components/tasklist/config/da_applicant.ts
  src/main/steps/common/task-list/components/tasklist/index.test.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1467

#1471 PRL-5815: Contact preferences - Show message and disable button when address not present
  src/main/app/form/Form.ts
  src/main/steps/common/contact-preference/review/content.test.ts
  src/main/steps/common/contact-preference/review/content.ts
  src/main/steps/common/contact-preference/review/template.njk
  src/main/steps/common/form/form.njk
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1471

#1476 PRL-5680: Add CRNF-2 dashboard notification
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/applicant/confirm-contact-details/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.ts
  src/main/steps/common/documents/definitions.ts
  src/main/steps/common/safety-concerns/review/util/safetyConcerns.util.test.ts
  src/main/steps/common/safety-concerns/review/util/safetyConcerns.util.ts
  src/main/steps/common/task-list/components/notification-banner/config/base.config.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.test.ts
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/common/task-list/components/notification-banner/definitions.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  src/main/steps/common/task-list/content.test.ts
  src/main/steps/common/task-list/utils.test.ts
  src/main/steps/common/tasklist/template.njk
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1476

#1477 PRL 5429
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  src/main/steps/common/task-list/content.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1477

#1423 Base PR for PCQ Tech integration
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/prl-citizen-frontend/values.preview.template.yaml
  charts/prl-citizen-frontend/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  config/development.yaml
  config/docker.yaml
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/definition.ts
  src/main/app/utils/featureToggles.ts
  src/main/modules/payments/paymentController.ts
  src/main/modules/pcq/controller.test.ts
  src/main/modules/pcq/controller.ts
  src/main/modules/pcq/definitions.ts
  src/main/modules/pcq/index.test.ts
  src/main/modules/pcq/index.ts
  src/main/modules/pcq/routes.ts
  src/main/modules/pcq/service.test.ts
  src/main/modules/pcq/service.ts
  src/main/modules/properties-volume/index.ts
  src/main/routes.ts
  src/main/server.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts
  src/main/steps/common/safety-concerns/concern-about/content.ts
  src/main/steps/tasklistresponse/summary/postController.test.ts
  src/main/steps/tasklistresponse/summary/postController.ts
  src/main/steps/urls.ts
  src/test/smoke/smoke.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1423

#1489 FPET-1019: Fix CVE issues
  charts/prl-citizen-frontend/values.preview.template.yaml
  package.json
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/CaseApi.ts
  src/main/app/case/CosApiClient.ts
  src/main/app/document/DocumentManagementController.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1489

#1493 Bug fix/downloadresponseto c1 a
  src/main/app/case/definition.ts
  src/main/steps/tasklistresponse/summary-confirmation/content.test.ts
  src/main/steps/tasklistresponse/summary-confirmation/content.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1493
