Repository hmcts/prl-citizen-frontend, pull requests merged in 2024-12, with the labels that each got.

#1715 fix(PRL-6716-build-issue): Fix build issue
  package.json
  src/main/modules/error-handler/index.ts
  src/main/modules/i18n/index.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1715

#1704 Fix for CA DA tech handover feedback items
  README.md
  package.json
  src/main/steps/common/documents/upload/upload-your-documents/content.ts
  src/main/steps/common/documents/upload/upload-your-documents/postController.ts
  src/main/steps/common/documents/upload/upload-your-documents/template.njk
  src/main/steps/common/documents/upload/utils.ts
  src/main/steps/common/safety-concerns/child/report-abuse/content.test.ts
  src/main/steps/common/safety-concerns/child/report-abuse/content.ts
  src/main/steps/common/safety-concerns/child/report-abuse/postController.ts
  src/main/steps/common/safety-concerns/review/content.test.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/test/end-to-end/contents/SafetyConcerns-content.js
  src/test/end-to-end/pages/C100-Rebuild/SafetyConcerns.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1704

#1719 fix aks deploy
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1719

#1716 PRL-6715
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/steps/application-within-proceedings/list-of-applications/content.test.ts
  src/main/steps/application-within-proceedings/utils.test.ts
  src/main/steps/application-within-proceedings/utils.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1716

#1712 Medium priority fix
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/app/case/case.ts
  src/main/steps/application-within-proceedings/list-of-applications/content.test.ts
  src/main/steps/application-within-proceedings/utils.test.ts
  src/main/steps/application-within-proceedings/utils.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.ts
  src/main/steps/common/task-list/components/tasklist/config/da_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/da_respondent.ts
  src/main/steps/common/task-list/components/tasklist/index.test.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1712

#1723 feat(6783): Add access control for AWP
  sonar-project.properties
  src/main/routes.ts
  src/main/steps/application-within-proceedings/routeGuard.ts
  src/main/steps/common/documents/definitions.ts
  src/main/steps/common/documents/upload/config.ts
  src/main/steps/common/documents/upload/content.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.ts
  src/main/steps/common/task-list/components/tasklist/config/da_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/da_respondent.ts
  src/main/steps/common/task-list/components/tasklist/index.test.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1723

#1721 Bat uat contigency
  config/development.yaml
  sonar-project.properties
  src/main/routes.ts
  src/main/steps/application-within-proceedings/checkanswers/content.test.ts
  src/main/steps/application-within-proceedings/checkanswers/content.ts
  src/main/steps/application-within-proceedings/routeGuard.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.ts
  src/main/steps/common/confirm-contact-details/checkanswers/content.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/content.ts
  src/main/steps/common/contact-preference/choose-a-contact-preference/ReviewContactPreferencePostController.test.ts
  src/main/steps/common/contact-preference/choose-a-contact-preference/ReviewContactPreferencePostController.ts
  src/main/steps/common/contact-preference/review/ReviewContactPreferencePostController.ts
  src/main/steps/common/contact-preference/review/content.test.ts
  src/main/steps/common/contact-preference/review/content.ts
  src/main/steps/common/documents/definitions.ts
  src/main/steps/common/documents/upload/config.ts
  src/main/steps/common/documents/upload/content.ts
  src/main/steps/common/documents/upload/upload-documents-success/content.test.ts
  src/main/steps/common/documents/upload/upload-documents-success/content.ts
  src/main/steps/common/safety-concerns/child/report-abuse/content.ts
  src/main/steps/common/statement-of-service/success/content.test.ts
  src/main/steps/common/statement-of-service/success/content.ts
  src/main/steps/common/statement-of-service/success/template.njk
  src/main/steps/common/summary/form.njk
  src/main/steps/common/task-list/components/notification-banner/content/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.ts
  src/main/steps/common/task-list/components/tasklist/config/da_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/da_respondent.ts
  src/main/steps/common/task-list/components/tasklist/index.test.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1721
