Repository hmcts/prl-citizen-frontend, pull requests merged in 2024-09, with the labels that each got.

#1648 fix FT
  charts/prl-citizen-frontend/values.preview.template.yaml
  charts/prl-citizen-frontend/values.yaml
  config/default.yaml
  config/development.yaml
  src/main/steps/c100-rebuild/childaddress/postController.ts
  src/test/end-to-end/contents/ChildrenDetails-content.js
  src/test/end-to-end/contents/OtherPersonDetails-content.js
  src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswers.js
  src/test/end-to-end/pages/C100-Rebuild/OtherPersonDetails.js
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1648

#1640 Citizen AwP Fee Change
  config/development.yaml
  src/main/steps/application-within-proceedings/list-of-applications/content.test.ts
  src/main/steps/application-within-proceedings/utils.ts
Labels: enable_keep_helm

#1650 fix(FT): Fix functional test
  charts/prl-citizen-frontend/Chart.yaml
  charts/prl-citizen-frontend/values.preview.template.yaml
  charts/prl-citizen-frontend/values.yaml
  config/default.yaml
  config/development.yaml
  src/main/steps/c100-rebuild/childaddress/postController.ts
  src/test/end-to-end/contents/ChildrenDetails-content.js
  src/test/end-to-end/contents/OtherPersonDetails-content.js
  src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswers.js
  src/test/end-to-end/pages/C100-Rebuild/OtherPersonDetails.js
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1650

#1657 Update node image
  .nvmrc
  Dockerfile
  package.json
  src/main/steps/applicant/confirm-contact-details/address/lookup/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/safetyConcerns.util.ts
  src/main/steps/common/safety-concerns/review/util/safetyConcerns.util.test.ts
  src/main/steps/common/safety-concerns/review/util/safetyConcerns.util.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1657

#1654 feat(6201): DAC fix - Focus Positioning/DAC_Focus_Positioning_01
  config/development.yaml
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/content.test.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/content.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/getController.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/child-details/add-children/content.test.ts
  src/main/steps/c100-rebuild/child-details/add-children/content.ts
  src/main/steps/c100-rebuild/child-details/other-children/names/content.test.ts
  src/main/steps/c100-rebuild/child-details/other-children/names/content.ts
  src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/add-other-persons/content.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/postController.ts
  src/main/steps/c100-rebuild/people/AddPeoplePostContoller.ts
  src/main/steps/c100-rebuild/people/util.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/add-respondents/content.ts
  src/main/steps/tasklistresponse/proceedings/order-details/content.test.ts
  src/main/steps/tasklistresponse/proceedings/order-details/content.ts
  src/main/steps/tasklistresponse/proceedings/order-details/postController.ts
  src/test/end-to-end/pages/C100-Rebuild/CaseNameAndPostCode.js
Labels: enable_keep_helm

#1661 Suppress audit issues
  src/test/end-to-end/contents/OtherPersonDetails-content.js
  src/test/end-to-end/pages/C100-Rebuild/OtherPersonDetails.js
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1661

#1667 FPET-1126 fixed vulnarability issues
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1667

#1665 6267-6268
  config/development.yaml
  src/main/modules/properties-volume/index.ts
  src/main/steps/applicant/confirm-contact-details/addressdetails/template.njk
  src/main/steps/application-within-proceedings/guidance/template.njk
  src/main/steps/application-within-proceedings/help-with-fees/reference/content.test.ts
  src/main/steps/application-within-proceedings/help-with-fees/reference/content.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/content.test.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/content.ts
  src/main/steps/c100-rebuild/applicant/add-applicants/template.njk
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/content.test.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/content.ts
  src/main/steps/c100-rebuild/applicant/confidentiality/details-know/template.njk
  src/main/steps/c100-rebuild/applicant/contact-detail/template.njk
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/check-your-answers/common/htmlSelectors.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.ts
  src/main/steps/c100-rebuild/check-your-answers/util/otherProceeding.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/otherProceeding.util.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/template.njk
  src/main/steps/c100-rebuild/consent-order/upload-confirmation/template.njk
  src/main/steps/c100-rebuild/document-submission/content.test.ts
  src/main/steps/c100-rebuild/document-submission/content.ts
  src/main/steps/c100-rebuild/document-submission/template.njk
  src/main/steps/c100-rebuild/hearing-urgency/urgent-details/template.njk
  src/main/steps/c100-rebuild/help-with-fees/fees-applied/content.test.ts
  src/main/steps/c100-rebuild/help-with-fees/fees-applied/content.ts
  src/main/steps/c100-rebuild/miam/upload-confirmation/template.njk
  src/main/steps/c100-rebuild/other-proceedings/current-previous-proceedings/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/current-previous-proceedings/content.ts
  src/main/steps/c100-rebuild/other-proceedings/current-previous-proceedings/template.njk
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/template.njk
  src/main/steps/c100-rebuild/screening-questions/alternative-resolution/template.njk
  src/main/steps/common/documents/upload/upload-documents-success/template.njk
  src/main/steps/common/form/fields.njk
  src/main/steps/common/form/fields/input.njk
  src/main/steps/common/safety-concerns/child/template.njk
  src/main/steps/common/safety-concerns/no-feedback/template.njk
  src/main/steps/common/safety-concerns/orders-required/unsupervised/template.njk
  src/main/steps/common/safety-concerns/yourself/template.njk
  src/main/steps/common/statement-of-service/review/template.njk
  src/main/steps/common/task-list/components/notification-banner/notification-banner.macro.njk
  src/main/steps/common/yourhearings/hearings/template.njk
  src/main/steps/complete-your-application-guidance/template.njk
  src/main/steps/respondent/confirm-contact-details/addressdetails/template.njk
  src/main/steps/tasklistresponse/proceedings/document-summary/template.njk
  src/main/steps/tasklistresponse/summary/content.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1665

#1543 Lived at this address for less than 5 years
  package-lock.json
  package.json
  src/main/steps/applicant/confirm-contact-details/addresshistory/content.test.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-manual.test.ts
  src/main/steps/c100-rebuild/applicant/address/common/address-manual.ts
  src/main/steps/c100-rebuild/applicant/address/manual/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.ts
  src/main/steps/c100-rebuild/people/address/address-manual.test.ts
  src/main/steps/c100-rebuild/people/address/address-manual.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.test.ts
  src/main/steps/c100-rebuild/respondent-details/address/manual/content.ts
  src/main/steps/common/confirm-contact-details/addresshistory/content.test.ts
  src/main/steps/common/confirm-contact-details/addresshistory/content.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ContactDetailsMapper.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ContactDetailsMapper.ts
  src/main/steps/respondent/confirm-contact-details/addresshistory/content.test.ts
  src/test/end-to-end/contents/ApplicantDetails-content.js
  src/test/end-to-end/contents/RespondentDetails-content.js
  src/test/end-to-end/pages/C100-Rebuild/C100CreateCaseE2E.js
  src/test/end-to-end/pages/RespondentEvents.js
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1543
