Repository hmcts/prl-citizen-frontend, pull requests merged in 2024-02, with the labels that each got.

#1243 suppress warnings
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1243

#1244 HotFix- Handle task list when legal rep is set during case progression
  src/main/steps/common/task-list/components/tasklist/config/ca_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.ts
  src/main/steps/common/task-list/components/tasklist/config/da_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/da_respondent.ts
  src/main/steps/common/task-list/content.ts
  src/main/steps/common/task-list/utils.ts
  src/main/steps/tasklistresponse/utils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1244

#1245 Max Replicas needed only 2
  charts/prl-citizen-frontend/Chart.yaml
  charts/prl-citizen-frontend/values.yaml
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1245

#1251 PRL-5174: C100 confirmation screen content change
  src/main/steps/c100-rebuild/confirmation-page/content.test.ts
  src/main/steps/c100-rebuild/confirmation-page/content.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1251

#1250 PRL-5073: Citizen C100 Applications - Spelling corrections/UI changes
  src/main/steps/c100-rebuild/confirmation-page/content.test.ts
  src/main/steps/c100-rebuild/confirmation-page/content.ts
  src/main/steps/common/components/address-lookup.test.ts
  src/main/steps/common/components/address-lookup.ts
  src/main/steps/common/confirm-contact-details/addressdetails/content.ts
  src/main/steps/common/task-list/components/notification-banner/content.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/yourhearings/hearings/content.ts
  src/main/steps/common/yourhearings/hearings/template.njk
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1250

#1252 "complete this section" for empty DOB and Address history
  src/main/modules/oidc/index.ts
  src/main/steps/applicant/confirm-contact-details/addressdetails/template.njk
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/respondent/confirm-contact-details/addressdetails/template.njk
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1252

#1258 Sonar coverage experiments
  config/development.yaml
  sonar-project.properties
  src/main/steps/common/summary/utils.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1258

#1267 Revert "Sonar coverage experiments"
  config/development.yaml
  sonar-project.properties
  src/main/steps/common/summary/utils.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1267

#1272 CA application- updated content on confirmation screen
  src/main/steps/c100-rebuild/confirmation-page/content.test.ts
  src/main/steps/c100-rebuild/confirmation-page/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1272

#1280 Revert "Bump @babel/traverse from 7.21.0 to 7.23.9"
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1280

#1257 PRL-5182: Current/previous proceedings CYA back link - International elements CYA content updates
  src/main/steps/tasklistresponse/international-factors/summary/content.test.ts
  src/main/steps/tasklistresponse/international-factors/summary/content.ts
  src/main/steps/tasklistresponse/proceedings/summary/template.njk
  src/main/steps/tasklistresponse/summary/content.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1257

#1284 downgrade playwright version
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1284
