Repository hmcts/prl-citizen-frontend, pull requests merged in 2024-10, with the labels that each got.

#1669 6268-poc
  src/main/assets/scss/main.scss
  src/main/steps/application-within-proceedings/checkanswers/utils.test.ts
  src/main/steps/application-within-proceedings/checkanswers/utils.ts
  src/main/steps/c100-rebuild/check-your-answers/common/htmlSelectors.test.ts
  src/main/steps/c100-rebuild/check-your-answers/common/htmlSelectors.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/form.njk
  src/main/steps/c100-rebuild/check-your-answers/helpers/InternationElementsHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/InternationElementsHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/courtOrderHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/generalHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/hearingdetailHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/hearingdetailHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/miamHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/miamHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/peopleHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/peopleHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/safetyConcernHelper.test.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/satetyConcernHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/lib/lib.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/check-your-answers/util/otherProceeding.util.ts
  src/main/steps/common/confirm-contact-details/checkanswers/content.test.ts
  src/main/steps/common/reasonable-adjustments/review/content.test.ts
  src/main/steps/common/reasonable-adjustments/review/content.ts
  src/main/steps/common/respondent-summary/form.njk
  src/main/steps/common/safety-concerns/review/content.test.ts
  src/main/steps/common/safety-concerns/review/form.njk
  src/main/steps/common/safety-concerns/review/helpers/safetyConcernHelper.test.ts
  src/main/steps/common/safety-concerns/review/helpers/satetyConcernHelper.ts
  src/main/steps/common/safety-concerns/review/mainUtil.test.ts
  src/main/steps/common/safety-concerns/review/mainUtil.ts
  src/main/steps/common/summary/utils.test.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/tasklistresponse/international-factors/summary/content.test.ts
  src/main/steps/tasklistresponse/international-factors/summary/content.ts
  src/main/steps/tasklistresponse/international-factors/summary/template.njk
  src/main/steps/tasklistresponse/proceedings/mainUtils.test.ts
  src/main/steps/tasklistresponse/proceedings/mainUtils.ts
  src/main/steps/tasklistresponse/proceedings/proceedingUtils.ts
  src/main/steps/tasklistresponse/proceedings/summary/content.ts
  src/main/steps/tasklistresponse/proceedings/summary/template.njk
  src/main/steps/tasklistresponse/summary/content.ts
  src/main/steps/urls.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1669

#1518 PRL-6089
  charts/prl-citizen-frontend/values.preview.template.yaml
  sonar-project.properties
  src/main/app/case/C100CaseApi.test.ts
  src/main/app/case/C100CaseApi.ts
  src/main/modules/payments/paymentApi.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/childaddress/postController.ts
  src/main/steps/tasklistresponse/summary/handler.test.ts
  src/main/steps/tasklistresponse/summary/handler.ts
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswers.js
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1518

#1689 fix FT
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswers.js
Labels: enable_keep_helm

#1693 fix DA issues and FT
  Jenkinsfile_CNP
  charts/prl-citizen-frontend/values.preview.template.yaml
  sonar-project.properties
  src/main/steps/applicant/yourhearings/hearings/content.test.ts
  src/main/steps/applicant/yourhearings/hearings/content.ts
  src/main/steps/common/confirm-contact-details/personaldetails/content.ts
  src/main/steps/common/dashboard-page.njk
  src/main/steps/common/documents/definitions.ts
  src/main/steps/common/documents/upload/submit-extra-evidence/content.test.ts
  src/main/steps/common/documents/upload/submit-extra-evidence/content.ts
  src/main/steps/common/documents/upload/submit-extra-evidence/template.njk
  src/main/steps/common/documents/upload/upload-your-documents/postController.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.ts
  src/main/steps/common/task-list/components/tasklist/config/da_applicant.ts
  src/main/steps/common/task-list/components/tasklist/content.ts
  src/main/steps/common/task-list/components/tasklist/index.test.ts
  src/main/steps/common/task-list/components/tasklist/utils.ts
  src/main/steps/prl-cases/dashboard/tabView.ts
  src/main/steps/respondent/yourhearings/hearings/content.test.ts
  src/main/steps/respondent/yourhearings/hearings/content.ts
  src/test/end-to-end/pages/C100-Rebuild/CheckYourAnswers.js
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1693

#1699 feat(PRL-6536): Add changes to core framework for date field translation
  src/main/modules/nunjucks/index.ts
  src/main/steps/c100-rebuild/applicant/personal-details/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1699

#1696 feat(PRL-6319): Integrate CAN6 Service of docs notification
  src/main/steps/common/task-list/components/notification-banner/config/base.config.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.test.ts
  src/main/steps/common/task-list/components/notification-banner/config/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/definitions.ts
  src/main/steps/common/task-list/components/notification-banner/utils.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1696
