Repository hmcts/prl-citizen-frontend, pull requests merged in 2025-03, with the labels that each got.

#1779 PRL-6439-optional pages
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/content.test.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/content.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.test.ts
  src/main/steps/c100-rebuild/other-proceedings/order-details/content.ts
  src/main/steps/common/contact-preference/choose-a-contact-preference/ReviewContactPreferencePostController.test.ts
  src/main/steps/common/contact-preference/choose-a-contact-preference/ReviewContactPreferencePostController.ts
  src/main/steps/common/safety-concerns/yourself/report-abuse/content.test.ts
  src/main/steps/common/safety-concerns/yourself/report-abuse/content.ts
  src/main/steps/tasklistresponse/proceedings/order-details/content.test.ts
  src/main/steps/tasklistresponse/proceedings/order-details/content.ts
  src/main/steps/tasklistresponse/proceedings/order-details/template.njk
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1779

#1786 FPVTL-80-renovate
  .github/renovate.json
  .github/stale.yml
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1786

#1796 PRL-6322: Labels Not Programmatically Associated fixes
  src/main/steps/application-within-proceedings/help-with-fees/reference/content.test.ts
  src/main/steps/application-within-proceedings/help-with-fees/reference/content.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/child-details/further-information/content.test.ts
  src/main/steps/c100-rebuild/child-details/further-information/content.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/content.test.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/content.ts
  src/main/steps/c100-rebuild/child-details/parental-responsibility/template.njk
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part2/content.test.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part2/content.ts
  src/main/steps/c100-rebuild/hearing-without-notice/hearing-part2/template.njk
  src/main/steps/c100-rebuild/help-with-fees/fees-applied/content.test.ts
  src/main/steps/c100-rebuild/help-with-fees/fees-applied/content.ts
  src/main/steps/c100-rebuild/help-with-fees/fees-applied/template.njk
  src/main/steps/c100-rebuild/screening-questions/consent-agreement/template.njk
  src/main/steps/c100-rebuild/screening-questions/permissions-request/content.test.ts
  src/main/steps/c100-rebuild/screening-questions/permissions-request/content.ts
  src/main/steps/c100-rebuild/screening-questions/permissions-request/template.njk
  src/main/steps/c100-rebuild/screening-questions/permissions-why/content.test.ts
  src/main/steps/c100-rebuild/screening-questions/permissions-why/content.ts
  src/main/steps/c100-rebuild/typeoforder/shortstatement/template.njk
  src/main/steps/common/documents/upload/upload-your-documents/template.njk
  src/main/steps/common/form/fields/text.njk
  src/main/steps/common/safety-concerns/abduction/child-location/content.ts
  src/main/steps/common/safety-concerns/abduction/child-location/template.njk
  src/main/steps/common/safety-concerns/abduction/previousabductions/content.test.ts
  src/main/steps/common/safety-concerns/abduction/previousabductions/content.ts
  src/main/steps/common/safety-concerns/abduction/previousabductions/template.njk
  src/main/steps/common/safety-concerns/child/report-abuse/content.test.ts
  src/main/steps/common/safety-concerns/child/report-abuse/content.ts
  src/main/steps/common/safety-concerns/orders-required/court-action/template.njk
  src/main/steps/common/safety-concerns/review/content.test.ts
  src/main/steps/common/safety-concerns/yourself/report-abuse/content.test.ts
  src/main/steps/common/safety-concerns/yourself/report-abuse/content.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1796

#1799 removal of tabindex=0 attribute from non interactive div element
  src/main/steps/common/documents/upload/upload-your-documents/template.njk
  src/main/steps/common/fileupload/macro.njk
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1799

#1800 FPVTL-103 put stale github actions in right path
  .github/stale.yml
  .github/workflows/stale.yml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, enable-prl-e2e-tests, rel:prl-citizen-frontend-pr-1800

#1801 PRL-7011: Fix DAC_Hint_Text_Association_01
  src/main/steps/common/documents/upload/upload-your-documents/content.test.ts
  src/main/steps/common/documents/upload/upload-your-documents/content.ts
  src/main/steps/common/documents/upload/upload-your-documents/template.njk
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1801

#1803 Fix VA issues
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/validation/util.ts
  src/main/steps/common/CaseDataController.test.ts
  src/main/steps/common/CaseDataController.ts
  src/main/steps/common/task-list/components/progress-bar/config/c100-case-creation.ts
  src/main/steps/common/task-list/components/progress-bar/content.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, enable-prl-e2e-tests, rel:prl-citizen-frontend-pr-1803

#1804 PRL-6112: Add missing welsh content for RA
  src/main/steps/common/reasonable-adjustments/intro/content.test.ts
  src/main/steps/common/reasonable-adjustments/intro/content.ts
  src/main/steps/common/reasonable-adjustments/language-requirements-and-special-arrangements/review/content.test.ts
  src/main/steps/common/reasonable-adjustments/language-requirements-and-special-arrangements/review/content.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, enable-prl-e2e-tests, rel:prl-citizen-frontend-pr-1804

#1806 Welsh translation implemented on reasonable adjustments confirmation …
  src/main/steps/common/reasonable-adjustments/confirmation/content.test.ts
  src/main/steps/common/reasonable-adjustments/confirmation/content.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, enable-prl-e2e-tests, rel:prl-citizen-frontend-pr-1806

#1807 Update Jenkinsfile_CNP with aat staging url
  Jenkinsfile_CNP
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1807
