Repository hmcts/prl-citizen-frontend, pull requests merged in 2025-01, with the labels that each got.

#1724 FPET-1226 ITHC issue fixes
  src/main/app/case/definition.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/steps/application-within-proceedings/document-upload/content.test.ts
  src/main/steps/application-within-proceedings/document-upload/content.ts
  src/main/steps/application-within-proceedings/document-upload/postController.test.ts
  src/main/steps/application-within-proceedings/document-upload/postController.ts
  src/main/steps/application-within-proceedings/supporting-document-upload/content.test.ts
  src/main/steps/application-within-proceedings/supporting-document-upload/content.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/content.test.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/content.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/postController.test.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/postController.ts
  src/main/steps/common/documents/upload/upload-your-documents/content.test.ts
  src/main/steps/common/documents/upload/upload-your-documents/content.ts
  src/main/steps/common/documents/upload/upload-your-documents/postController.test.ts
  src/main/steps/common/documents/upload/upload-your-documents/postController.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1724

#1730 feat(PRL-6755): Integrate DT RUM based on environment
  src/main/modules/nunjucks/index.ts
  src/main/steps/common/dashboard-page.njk
  src/main/steps/common/page.njk
  src/main/steps/common/views/includes/script-dt_rum.njk
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1730

#1735 Update TEST URL back to aat
  Jenkinsfile_CNP
  src/test/end-to-end/pages/C100-Rebuild/ApplicantDetails.js
  src/test/end-to-end/pages/C100-Rebuild/OtherPersonDetails.js
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1735

#1743 Fortify fixes
  src/main/app/controller/GetController.ts
  src/main/modules/oidc/index.ts
  src/main/steps/c100-rebuild/consent-order/upload/getController.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.test.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.ts
  src/main/steps/common/utils.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, enable_keep_helm

#1740 PRL-6808: Fix sonar issues
  src/main/app/controller/GetController.ts
  src/main/app/utils/progress-bar-utils.test.ts
  src/main/modules/oidc/index.ts
  src/main/steps/applicant/task-list/index.test.ts
  src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
  src/main/steps/c100-rebuild/childaddress/postController.ts
  src/main/steps/c100-rebuild/consent-order/upload/getController.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsPostController.ts
  src/main/steps/common/refuge/upload-refuge-document/postController.ts
  src/main/steps/common/statement-of-service/upload/postController.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.test.ts
  src/main/steps/common/task-list/controllers/CaseDetailsGetController.ts
  src/main/steps/common/task-list/controllers/TaskListGetController.test.ts
  src/main/steps/common/utils.ts
  src/main/steps/tasklistresponse/start/routeGuard.test.ts
  src/main/steps/tasklistresponse/summary/postController.test.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1740

#1726 FPET-1227: Add middleware to sanitise form data
  jest.config.js
  package.json
  src/main/app/case/definition.ts
  src/main/app/form/validation.test.ts
  src/main/app/form/validation.ts
  src/main/modules/sanitize-request/index.test.ts
  src/main/modules/sanitize-request/index.ts
  src/main/routes.test.ts
  src/main/routes.ts
  src/main/steps/application-within-proceedings/document-upload/content.test.ts
  src/main/steps/application-within-proceedings/document-upload/content.ts
  src/main/steps/application-within-proceedings/document-upload/postController.test.ts
  src/main/steps/application-within-proceedings/document-upload/postController.ts
  src/main/steps/application-within-proceedings/supporting-document-upload/content.test.ts
  src/main/steps/application-within-proceedings/supporting-document-upload/content.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/content.test.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/content.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/postController.test.ts
  src/main/steps/c100-rebuild/miam/domestic-abuse/upload-evidence/postController.ts
  src/main/steps/common/documents/upload/upload-your-documents/content.test.ts
  src/main/steps/common/documents/upload/upload-your-documents/content.ts
  src/main/steps/common/documents/upload/upload-your-documents/postController.test.ts
  src/main/steps/common/documents/upload/upload-your-documents/postController.ts
  tsconfig.json
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1726

#1731 PRL-6809: Pipeline changes to run citizen smoke playwright tests in master & preview builds
  Jenkinsfile_CNP
  package.json
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1731

#1744 prl-6817/hearing changes welsh
  src/main/steps/applicant/yourhearings/hearings/content.test.ts
  src/main/steps/common/yourhearings/hearings/content.test.ts
  src/main/steps/common/yourhearings/hearings/content.ts
  src/main/steps/respondent/yourhearings/hearings/content.test.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1744

#1742 Updated Can4 notification
  src/main/steps/common/task-list/components/notification-banner/content/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
Labels: ns:private-law, prd:prl, enable_keep_helm

#1759 update s2s token endpoint
  src/main/app/auth/service/get-service-auth-token.integration.test.ts
  src/main/app/auth/service/get-service-auth-token.ts
Labels: ns:private-law, prd:prl, enable_keep_helm

#1745 PRL-6807: Integrate new fee api for complete application page
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/app/fees/fees-lookup-api.test.ts
  src/main/app/fees/fees-lookup-api.ts
  src/main/steps/complete-your-application-guidance/content.test.ts
  src/main/steps/complete-your-application-guidance/content.ts
  src/main/steps/complete-your-application-guidance/routeGuard.test.ts
  src/main/steps/complete-your-application-guidance/routeGuard.ts
Labels: ns:private-law, prd:prl, enable_keep_helm

#1718 FPET-1218: Add other people confidentiality screen
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/app/case/definition.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.ts
  src/main/steps/c100-rebuild/check-your-answers/content.test.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/child-details/live-with/living-arrangements/postController.test.ts
  src/main/steps/c100-rebuild/child-details/live-with/living-arrangements/postController.ts
  src/main/steps/c100-rebuild/child-details/navigationController.test.ts
  src/main/steps/c100-rebuild/child-details/navigationController.ts
  src/main/steps/c100-rebuild/other-person-details/confidentiality/content.test.ts
  src/main/steps/c100-rebuild/other-person-details/confidentiality/content.ts
  src/main/steps/c100-rebuild/other-person-details/confidentiality/postController.test.ts
  src/main/steps/c100-rebuild/other-person-details/confidentiality/postController.ts
  src/main/steps/c100-rebuild/other-person-details/confidentiality/template.njk
  src/main/steps/c100-rebuild/other-person-details/navigationController.test.ts
  src/main/steps/c100-rebuild/other-person-details/navigationController.ts
  src/main/steps/c100-rebuild/other-person-details/utils.test.ts
  src/main/steps/c100-rebuild/other-person-details/utils.ts
  src/main/steps/urls.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1718

#1758 Fix tasklist when returning before the case is created
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/modules/properties-volume/index.ts
  src/main/steps/common/dashboard-page.njk
  src/main/steps/common/page.njk
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  src/main/steps/common/task-list/components/progress-bar/config/ca_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_applicant.ts
  src/main/steps/common/task-list/utils.ts
Labels: ns:private-law, prd:prl, enable_keep_helm

#1755 prl-6821/allign_confidentiality_details
  charts/prl-citizen-frontend/values.preview.template.yaml
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
Labels: ns:private-law, prd:prl, enable_keep_helm

#1762 Release 6 0 changes
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/modules/properties-volume/index.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.ts
  src/main/steps/common/dashboard-page.njk
  src/main/steps/common/page.njk
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  src/main/steps/common/task-list/components/notification-banner/utils.ts
  src/main/steps/common/task-list/components/progress-bar/config/ca_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_applicant.ts
  src/main/steps/common/task-list/utils.ts
Labels: ns:private-law, prd:prl, enable_keep_helm
