Repository hmcts/prl-citizen-frontend, pull requests merged in 2025-04, with the labels that each got.

#1812 FPVTL-547 Upgrade dependencies for Citizen frontend
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, enable-prl-e2e-tests, rel:prl-citizen-frontend-pr-1812

#1818 Update cookie dependency to fix vulnerabllity
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, enable-prl-e2e-tests, rel:prl-citizen-frontend-pr-1818

#1802 FPVTL-119 oci helm
  charts/prl-citizen-frontend/Chart.yaml
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1802
