Repository hmcts/prl-citizen-frontend, pull requests merged in 2025-02, with the labels that each got.

#1764 PRL-6936: Fix PCQ issue
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/case.ts
  src/main/app/case/definition.ts
  src/main/app/controller/PostController.ts
  src/main/app/testingsupport/TSDraftController.test.ts
  src/main/modules/pcq/controller.test.ts
  src/main/modules/pcq/controller.ts
  src/main/steps/c100-rebuild/check-your-answers/CheckYourAnswersGetController.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.ts
  src/main/steps/c100-rebuild/help-with-fees/need-help-with-fees/routeGuard.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1764

#1766 PRL-6945: Fix perftest RA issue
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/modules/reasonable-adjustments/controller.ts
  src/main/modules/reasonable-adjustments/index.test.ts
  src/main/modules/reasonable-adjustments/index.ts
  src/main/modules/reasonable-adjustments/service.test.ts
  src/main/modules/reasonable-adjustments/service.ts
  src/main/modules/reasonable-adjustments/util.ts
  src/main/steps/common/reasonable-adjustments/intro/routeGuard.ts
  src/main/steps/common/reasonable-adjustments/language-requirements-and-special-arrangements/review/postController.test.ts
  src/main/steps/common/reasonable-adjustments/language-requirements-and-special-arrangements/review/postController.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1766

#1765 Revised English Translation of the Accessibility Statement
  src/main/steps/accessibility-statement/content.test.ts
  src/main/steps/accessibility-statement/content.ts
  src/main/steps/accessibility-statement/template.njk
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1765

#1768 FPET 1254
  package-lock.json
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1768

#1773 Va sonar fix
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/miamHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/helpers/peopleHelper.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/consent-order/upload/content.ts
  src/main/steps/c100-rebuild/miam/upload/content.ts
  src/main/steps/c100-rebuild/utils.ts
  src/main/steps/c100-rebuild/validation/util.ts
  src/main/steps/common/otherProceeding/getController.ts
  src/main/steps/common/summary/utils.ts
  src/main/steps/tasklistresponse/proceedings/mainUtils.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1773

#1774 FPET-1254
  .dockerignore
  .eslintrc.js
  .gitignore
  .yarn/releases/yarn-3.8.7.cjs
  .yarn/releases/yarn-4.6.0.cjs
  .yarnrc.yml
  Dockerfile
  charts/prl-citizen-frontend/Chart.yaml
  jest.config.js
  package.json
  src/main/app/auth/service/get-service-auth-token.integration.test.ts
  src/main/app/auth/service/get-service-auth-token.ts
  src/main/app/auth/user/oidc.integration.test.ts
  src/main/app/auth/user/oidc.ts
  src/main/app/case/C100CaseApi.ts
  src/main/app/case/CaseApi.ts
  src/main/app/case/CosApiClient.test.ts
  src/main/app/case/CosApiClient.ts
  src/main/modules/payments/paymentApi.test.ts
  src/main/modules/reasonable-adjustments/index.ts
  src/main/steps/applicant/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.test.ts
  src/main/steps/common/confirm-contact-details/checkanswers/ConfirmContactDetailsGetController.test.ts
  src/main/steps/tasklistresponse/TasklistGetController.test.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1774

#1784 FPET-1293: Add tests for missing coverage
  src/main/app/case/C100CaseApi.test.ts
  src/main/steps/c100-rebuild/check-your-answers/PayAndSubmitPostController.test.ts
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1784

#1772 PRL-6985: RPA fix
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/app/case/C100CaseApi.test.ts
  src/main/app/case/C100CaseApi.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1772

#1775 removed third party content and adjusted fonts of headings
  charts/prl-citizen-frontend/values.preview.template.yaml
  src/main/steps/accessibility-statement/content.test.ts
  src/main/steps/accessibility-statement/content.ts
  src/main/steps/accessibility-statement/template.njk
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1775

#1767 Feature/prl 6941 bring your paper update
  src/main/steps/common/task-list/components/notification-banner/content/ca_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/ca_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_applicant.ts
  src/main/steps/common/task-list/components/notification-banner/content/da_respondent.ts
  src/main/steps/common/task-list/components/notification-banner/index.test.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1767

#1788 Check for label before running prl-e2e-tests
  Jenkinsfile_CNP
  README.md
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1788
