Repository hmcts/prl-citizen-frontend, pull requests merged in 2025-06, with the labels that each got.

#1865 FPVTL-770 switch to terser and us-parser-js because we are using browser tools and devtools using 2.0.2 and update dependency check
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1865

#1866 FPVTL-737: Cases progressing offline should be treated as draft for MVP
  src/main/app/case/definition.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/ca_respondent.ts
  src/main/steps/common/task-list/components/tasklist/config/da_applicant.ts
  src/main/steps/common/task-list/components/tasklist/config/da_respondent.ts
  src/main/steps/common/task-list/components/tasklist/index.test.ts
  src/main/steps/common/task-list/utils.test.ts
  src/main/steps/common/task-list/utils.ts
  src/main/steps/prl-cases/dashboard/tabView.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, enable-prl-e2e-tests, rel:prl-citizen-frontend-pr-1866

#1859 FPVTL-679-synchSafeTimeToCall
  src/main/steps/common/confirm-contact-details/checkanswers/ContactDetailsMapper.ts
Labels: ns:private-law, prd:prl, enable_keep_helm, rel:prl-citizen-frontend-pr-1859
