Repository hmcts/prl-citizen-frontend, pull requests merged in 2025-05, with the labels that each got.

#1823 Upgrade version of formidable to non-vulnerable version
  package.json
  yarn.lock
Labels: ns:private-law, prd:prl, enable-prl-e2e-tests, rel:prl-citizen-frontend-pr-1823

#1817 FPVTL-533 Fix confidentiality flow
  charts/prl-citizen-frontend/values.preview.template.yaml
  config/development.yaml
  src/main/steps/c100-rebuild/applicant/add-applicants/postController.ts
  src/main/steps/c100-rebuild/applicant/navigationController.test.ts
  src/main/steps/c100-rebuild/applicant/navigationController.ts
  src/main/steps/c100-rebuild/c100sequence.test.ts
  src/main/steps/c100-rebuild/c100sequence.ts
  src/main/steps/c100-rebuild/check-your-answers/content.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.test.ts
  src/main/steps/c100-rebuild/check-your-answers/mainUtil.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.test.ts
  src/main/steps/c100-rebuild/check-your-answers/util/applicant.util.ts
  src/main/steps/c100-rebuild/validation/applicantValidation.test.ts
  src/main/steps/c100-rebuild/validation/applicantValidation.ts
  src/main/steps/c100-rebuild/validation/fields-config/sections/people.ts
  src/main/steps/c100-rebuild/validation/util.test.ts
  src/main/steps/c100-rebuild/validation/util.ts
  src/main/steps/common/refuge/navigationController.test.ts
  src/main/steps/common/refuge/navigationController.ts
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1817

#1836 FPVTL-620 restore other person flow
  src/main/steps/common/refuge/navigationController.test.ts
  src/main/steps/common/refuge/navigationController.ts
  test/java/build.gradle
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1836

#1844 FPVTL-690: Nightly pipeline fixes
  test/java/build.gradle
  yarn-audit-known-issues
Labels: ns:private-law, prd:prl, enable_fortify_scan, rel:prl-citizen-frontend-pr-1844

#1845 Java 21
  test/java/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  test/java/.gradle/buildOutputCleanup/cache.properties
  test/java/.gradle/checksums/checksums.lock
  test/java/.gradle/checksums/md5-checksums.bin
  test/java/.gradle/checksums/sha1-checksums.bin
  test/java/.gradle/vcs-1/gc.properties
  test/java/build.gradle
  test/java/gradle/wrapper/gradle-wrapper.jar
  test/java/gradle/wrapper/gradle-wrapper.properties
  test/java/gradlew
  test/java/gradlew.bat
Labels: ns:private-law, prd:prl, rel:prl-citizen-frontend-pr-1845
